### PR TITLE
new pane locators for the new Message Box

### PR DESCRIPTION
**Pull request by 2is10**
`/messages:all` - the All tab (corresponds to old `/notices`)
`/messages:sent`
`/messages:unread`
`/messages:page` or `/messages` - the This Page tab (same as old `/messages`)

`/messages/<thread_id>` - a thread (unchanged)

It seems that the only locators we persist are of the `/messages/...` variety, which aren’t changing. The website uses `/messages`, which is unchanged.

It appears that `/notices` has only ever been used within the extension.

I’d appreciate any opinions @andrewconner @stkem @joonho1101

### CODE REVIEW

**Comment by andrewconner** [comment]
> It appears that /notices has only ever been used within the extension.

Correct, I haven't seen that on the server.

**Comment by 2is10** [comment]
This alternative approach is also a possibility:

`/messages#all` - formerly `/notices`
`/messages#sent`
`/messages#unread`
`/messages` - same as today (message threads on this page)
`/messages/<thread_id>` - same as today (a specific thread)

The hash (`#`) is used to designate subpanes. Transitions between subpanes are handled by a pane itself (e.g. notices.js), rather than by the pane container (pane.js).

**Comment by andrewconner** [comment]
Either is fine with me. The 2nd is better for backwards compatibility which is nice.

**Comment by 2is10** [comment]
I think I like the second one better too. Switching to it...

**Pull request merged**
