### PR TITLE
Sprite tweaks

### PR DESCRIPTION
**Pull request by andrewconner**

### CODE REVIEW

**Comment by andrewconner** [comment]
@martinraison

**Comment by martinraison** [comment]
looks good - does that solve the problem with non-retina screens or is it something else?

**Comment by andrewconner** [comment]
Sorta. Still working on all the problems with sprites. Most are caused by non-even dimensions of the images.

**Comment by 2is10** [comment]
Or, to be more precise, retina images whose dimensions aren’t exactly 2x the non-retina versions. (A dimension could be incorrect even if even.)

**Comment by andrewconner** [comment]
@2is10 I added a check for image dimensions, and turns out over 10 were wrong. So I fixed them and many of the problems have gone. Thanks!

**Comment by 2is10** [comment]
glad to hear it. nice work!

**Comment by 2is10** [comment]
oh, i see. it looks like we _only_ have retina images now. didn’t realize that.

**Comment by andrewconner** [comment]
Yeah, simplified the design process a bit, and when sprited, the larger images really don't use significantly more space. You see any problems with that? We can have both fairly easily if needed using the sprite generator task.

**Comment by 2is10** [comment]
Mobile bandwidth/memory consumption, I guess, is the main reason (other than latency due to size), but people should be using our app on mobile devices. I don’t see a reason to bother with 1x sprites right now. Keep images/screenshots will probably be quite a bit bigger anyway, and those are probably harder to create 1x and 2x versions of.

**Comment by andrewconner** [comment]
Yeah, in the scheme of what's on the page now, it's tiny (we have many large images now). We'll actually want to clean up the DOM as the user scrolls a lot — it gets heavy quick.

Many mobile devices have a pixel density over 1 anyways, so retina would look nicer.

**Comment by 2is10** [comment]
Yes, assuming they’re fully zoomed in and care more about looks than
latency / data usage.​

**Pull request merged**
