### PR TITLE
add getDiscoveryCountByKeeper endpoint

### PR DESCRIPTION
**Pull request by raymondng**
Will be porting stuff over and then clean-up.

@yingjieMiao

### CODE REVIEW

**Comment by eishay** [comment]
who is using this end point? is it the cortex?

**Comment by yingjieMiao** [comment]
i think it's curator

**Comment by eishay** [comment]
oh, just wondered why @yingjieMiao was tagged vs @stkem

**Comment by raymondng** [comment]
It's shoebox (see UserCommander). @yingjieMiao is familiar with the relevant code (count stuff). 

@eishay @stkem your comments are appreciated.

FWIW I am porting stuff over to eliminate dependency in shoebox. There'll be quite a lot more.

**Pull request merged**
