### PR TITLE
reducing most common logs entries. 

### PR DESCRIPTION
**Pull request by eishay**
@ymatsuda @raymondng @stkem @andrewconner 
We are spitting tons of logs to logentries, a bit inefficient and many are not useful now (they did make sense back then). Our quota is almost up and we're only mid-month. I removed some logs, we can always put them back.

Using "tail -100000 app.log | sed 's/\* (c._) -._/\1/' | grep -v "at " | sort | uniq -c | sort -n -k 1 | less" to find them

### CODE REVIEW

**Comment by andrewconner** [comment]
Looks good to me.

**Comment by ymatsuda** [comment]
ok to me

**Comment by raymondng** [comment]
Looks reasonable.

**Comment by stkem** [comment]
lgtm. So debug log messages don't go to logentries?

**Pull request merged**
