### PR TITLE
[#88215048593788] Add a ftue for moving the keeper

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner @JRuff42 

screen shot 2016-02-16 at 6 13 11 pm

### CODE REVIEW

**Comment by cvializ** [comment]
move_keeper

**Comment by andrewconner** [comment]
Sweet!

**Comment by cvializ** [comment]
Final version:

screen shot 2016-02-22 at 3 03 08 pm

**Comment by andrewconner** [comment]
Neato :+1:

**Pull request merged**
