### PR TITLE
send keepers info to heimdal

### PR DESCRIPTION
**Pull request by yingjieMiao**
@raymondng  @stkem

### CODE REVIEW

**Comment by raymondng** [comment]
Thanks @yingjieMiao @stkem 

It looks like the contract for Heimdal eventing is pretty weak -- I think you have mentioned this before. As this is for internal processing and persisting to relational db, I am thinking a stronger contract might be appropriate. That's admittedly a bigger change (so, no immediate impact). Thoughts?

**Comment by stkem** [comment]
lgtm

**Comment by stkem** [comment]
and yes, we should think about having some stronger contracts (ideally enfornced with types) on the heimdal events used in help rank. Not really sure how to go about that yet though.

**Comment by raymondng** [comment]
Cool -- good to know there's consensus (in principle). We'll sort things out along the way.

**Pull request merged**
