### PR TITLE
check for isUnscrapable prior to assignment

### PR DESCRIPTION
**Pull request by raymondng**
@yingjieMiao @leogrim @ymatsuda

### CODE REVIEW

**Comment by yingjieMiao** [comment]
lgm. but I wonder how the url rules were applied before we have this.

**Comment by raymondng** [comment]
I did a quick check -- we also check the same in scraper, but I think this is probably more efficient. Let me know if I have missed anything.

**Comment by yingjieMiao** [comment]
I agree this is more efficient. thanks.

**Comment by raymondng** [comment]
Incorporated excellent feedback from @ymatsuda  and @yingjieMiao

**Comment by ymatsuda** [comment]
lgtm!

**Pull request merged**
