### PR TITLE
More undefined me.emails

### PR DESCRIPTION
**Pull request by cvializ**
ditto to last PR

https://fortytwo.airbrake.io/projects/113130/groups/1622436999197533574/notices/1622436998035300394

### CODE REVIEW

**Comment by andrewconner** [comment]
Why are they empty?

**Comment by andrewconner** [comment]
Race condition?

**Comment by cvializ** [comment]
New user? I am not sure.

**Comment by cvializ** [comment]
It's somebody on Firefox OS on IP 103.240.169.19, maybe we could find that user in the admin tool and see what their state looks like

**Comment by andrewconner** [comment]
Oh weird, backend shouldn't be giving nothing for this field. I bet it's a race, because from the code I see, it's explicitly set.

**Comment by cvializ** [comment]
Alright, I'm glad we caught it. Does this mean I should wait to merge this PR until we resolve the larger issue, or you think it's good to go now?

**Comment by andrewconner** [comment]
By race, I mean client side race, if that's possible. I just don't see how nothing would come here (empty list is possible). So the PR is fine, but perhaps we should wait until `me` is loaded? Not sure if what I think is happening is possible...

**Comment by cvializ** [comment]
Well `me` is definitely loaded, otherwise `me` would be undefined and not `me.emails`. I'm not sure I understand where the race would be

**Pull request merged**
