### PR TITLE
hand written count queries (much faster!)

### PR DESCRIPTION
**Pull request by eishay**

### CODE REVIEW

**Comment by stkem** [comment]
Out of curiosity, what did the slick generated queries look like?

**Comment by eishay** [comment]
``` sql
select x2.x3 
from (
select count(1) as x3 
from (
select x4.`ID`, x4.`created_at`, x4.`updated_at`, x4.`external_id`, x4.`title`, x4.`uri_id`, x4.`url_id`, x4.`url`, x4.`bookmark_path`, x4.`is_private`, x4.`user_id`, x4.`state`, x4.`source`, x4.`kifi_installation`, x4.`seq` 
from `bookmark` x4 
where ((x4.`updated_at` >= {ts '2014-01-16 08:00:00.0'}) and (x4.`updated_at` <= {ts '2014-01-17 01:06:48.515'})) 
and (x4.`state` = 'active')) x5) x2
```

**Comment by eishay** [comment]
which is not that optimal

**Comment by stkem** [comment]
oh, wow

**Pull request merged**
