### PR TITLE
Alternative design for org selector

### PR DESCRIPTION
**Pull request by adamjgrant**

### CODE REVIEW

**Comment by adamjgrant** [comment]
This also handles overflow when orgs > 3

@cvializ @andrewconner 

screen shot 2015-08-05 at 11 07 12 am

**Comment by cvializ** [comment]
The check mark size/placement strikes me as odd, but if you believe in it, :+1:

**Comment by ryanpbrewster** [comment]
Can we just put a happy black/green border around it?

**Comment by adamjgrant** [comment]
@cvializ How about this?

screen shot 2015-08-05 at 11 36 11 am

**Comment by cvializ** [comment]
I think I liked the first one better, not to jerk you back and forth. I think it's the two checkmarks with different meanings so close together

**Comment by adamjgrant** [comment]
I see what you mean. I wonder if it would help if it were indented.

**Comment by adamjgrant** [comment]
@cvializ 

screen shot 2015-08-05 at 11 55 06 am

**Comment by adamjgrant** [comment]
We can keep changing this up but I'm going to merge this in for now so I'm not blocking Dafne.

**Comment by cvializ** [comment]
Alright!

**Pull request merged**
