### PR TITLE
Rename System Libraries

### PR DESCRIPTION
**Pull request by raymondng**
The names are converted when we read from Db. AFAIK this should do the trick. 

@andrewconner @ymatsuda -- please take a look.

### CODE REVIEW

**Comment by andrewconner** [comment]
Great. One sec, will get the name.

**Comment by ymatsuda** [comment]
lgtm

**Comment by andrewconner** [comment]
Keep it, you got the right ones.

**Comment by raymondng** [comment]
Cool. Thanks!

**Pull request merged**
