### PR TITLE
add slack CTA on home feed

### PR DESCRIPTION
**Pull request by camhashemi**
@cvializ @andrewconner 

completes https://app.asana.com/0/inbox/32728208409722/74081614846649/74089349456006, the only difference from the spec is that we don't go to the server to check if the user's org already has slack integrations on it. I'd prefer not to do that.

### CODE REVIEW

**Comment by andrewconner** [comment]
Check out https://github.com/kifi/keepit/pull/18907, once merged, it'll tell you whether you should show this.

**Comment by camhashemi** [comment]
one problem with linking to the Slack auth page (if applicable) is that it takes forever. do you guys know if we have a "hover" loading spinner, that darkens the current page while the next one loads? as opposed to the in-page spinners we already have. alternatively, I can add a little spinner within the element to signal that a new page is on its way.

**Comment by camhashemi** [comment]
@andrewconner nice, I'll have a look

**Comment by camhashemi** [comment]
screen shot 2015-12-15 at 3 43 39 pm

**Comment by camhashemi** [comment]
screen shot 2015-12-15 at 3 52 41 pm

**Comment by andrewconner** [comment]
Nice!

**Comment by cvializ** [comment]
nice UI :sunglasses:

**Comment by camhashemi** [comment]
@cvializ @andrewconner added 
screen shot 2015-12-15 at 6 26 44 pm

if you go to /teams/new?slack or pass in `showSlackPromo: true` to `$stateParams`

**Comment by cvializ** [comment]
love the text size and color :+1:

**Pull request merged**
