### PR TITLE
Adding analytics tracking when users click on import bookmarks (from bro...

### PR DESCRIPTION
**Pull request by ahsu1230**
...wser or from file (pocket/delicious/etc.))

@eishay @stkem @martinraison @2is10 @lawzlo @andrewconner

### CODE REVIEW

**Comment by ahsu1230** [comment]
Just a note: this is for specifically only for when the popup comes up (hence why user_viewed vs. user_clicked)
We already have user_clicked trackers for the actual importing functions

**Comment by martinraison** [comment]
lgtm!

**Comment by stkem** [comment]
lgtm

**Comment by 2is10** [comment]
:+1:

**Pull request merged**
