### PR TITLE
Update move card for design consistency.

### PR DESCRIPTION
**Pull request by cvializ**
| Old | New |
| --- | --- |
| screen shot 2015-08-10 at 11 33 08 am | screen shot 2015-08-10 at 11 32 52 am |

@adamjgrant

### CODE REVIEW

**Comment by adamjgrant** [comment]
Looks good, but the drop shadow is a bit offputting. I think we might have that in the follow buttons, but this is because they overlay with images (whose color mapping we don't know). Could we do it without the shadow?

**Comment by adamjgrant** [comment]
Looks a lot better with the text smaller.

**Comment by cvializ** [comment]
Right that makes sense, I'll take out the drop shadow. Yeah when I saw you make the text smaller, I thought it was a big improvement.

**Comment by cvializ** [comment]
Now with 100% less box shadow.

screen shot 2015-08-10 at 11 43 12 am

**Pull request merged**
