### PR TITLE
2.6.15: refactoring of messaging code in the extension

### PR DESCRIPTION
**Pull request by 2is10**
I’m hoping this will clarify the code a bit and fix more border-case consistency issues than it introduces.

Changes:
- `pageData` now only contains actual page data from shoebox (e.g. kept status).
  - The thread summary data is now in `pageThreadData`.
  - The list of tabs currently at each normalized URI is now kept in `tabsByUrl`.
- No longer waiting until page data from shoebox returns before requesting a page’s thread summaries.
- No longer waiting until both page data from shoebox and thread data from eliza arrive before initializing pages.
  - Instead, we initialize pages with data from each service independently, as it arrives.
- The objects in `pageThreadData` are instances of `ThreadData`, which have methods for convenience and to help maintain data consistency/constraints.
- Utilizing the `lastMessageRead` field inside the JSON of each `ThreadInfo` to track read state instead of the separate map we were using since pre-eliza.
- Using `threadDataCallbacks` both to hold callbacks for when a page’s thread summaries arrive and to signal that there is an outstanding request for a page’s thread summaries.
- Using `threadCallbacks` in a similar manner for specific threads.
- Leveraging our knowledge of which pane is currently open on each tab to decide which messaging/notification updates to send them (see `forEachTabAtLocator`).
- Introduced a new `participants` extension message for requesting a thread’s participants.
  - It responds faster than `thread` b/c it can use either the thread summary or the thread’s first message.
- Renamed the `subscribe` method to `kifify` since we no longer have page subscriptions and the method’s main job is to make sure the browser tab is properly kifified™.
- Renamed the `tab.inited` flag to `tab.engaged` to try be clearer that it represents initialization of a page’s auto-engagement behavior (showing the tile and auto-expanding the keeper).

### CODE REVIEW

**Comment by andrewconner** [comment]
I will be using this extension to check for bugs for the next day.

**Comment by andrewconner** [comment]
I'm running into a bug fairly often where the threads pane isn't being populated, so it's appearing blank. Trying to isolate what it takes to reproduce, but since you're familiar with the new code, it seems something is blocking messages from getting to the content script.

I'm able to do this most often when I'm loading a new page and quickly opening the threads pain. Interestingly, if I blur then re-focus the tab, it seems to get unclogged.

Content script:

```
[Tu 20:06:57.276] [keeper_scout] nymag.com keeper_scout.js:11
[Tu 20:06:57.416] [api:respond] session     Object  api.js:13
[Tu 20:06:57.417] [onMessage] counts    Object  api.js:23
[Tu 20:06:57.417] [onMessage] init  Object  api.js:23
[Tu 20:06:57.504] [api:respond] api:require     Array[1]    api.js:13
[Tu 20:06:57.836] [api:respond] api:require     Array[1]    api.js:13
[Tu 20:06:59.256] [api:respond] api:require     Array[7]    api.js:13
[Tu 20:06:59.257] [show] tile slider2.js:686
[Tu 20:06:59.257] [showSlider] tile slider2.js:251
[Tu 20:06:59.258] [createSlider] kept: no counts:   Object  slider2.js:65
[Tu 20:06:59.514] [api:respond] api:require     Array[1]    api.js:13
[Tu 20:07:00.001] [api:respond] get_keepers     Object  api.js:13
[Tu 20:07:00.011] [api:respond] api:require     Array[1]    api.js:13
[Tu 20:07:00.139] [slider.mouseout] hiding slider2.js:85
[Tu 20:07:00.140] [hideSlider] mouseout slider2.js:277
[Tu 20:07:00.668] [show] tile slider2.js:686
[Tu 20:07:00.668] [showSlider] tile slider2.js:251
[Tu 20:07:00.668] [createSlider] kept: no counts:   Object  slider2.js:65
[Tu 20:07:00.688] [api:respond] get_keepers     Object  api.js:13
[Tu 20:07:01.422] [mouseup] slider2.js:106
[Tu 20:07:01.425] [showPane] /messages  slider2.js:393
[Tu 20:07:01.426] [showPane2] /messages threads slider2.js:403
[Tu 20:07:01.429] [api:respond] session     Object  api.js:13
[Tu 20:07:01.585] [api:respond] api:require     Array[1]    api.js:13
[Tu 20:07:01.599] [api:respond] api:require     Array[2]    api.js:13
[Tu 20:07:02.088] [api:respond] api:require     Array[17]   api.js:13
--- blur and re-focus tab ---
[Tu 20:07:06.487] [onMessage] counts    Object  api.js:23
[Tu 20:07:06.492] [api:respond] threads     Array[0]    api.js:13
[Tu 20:07:06.522] [api:respond] session     Object  api.js:13
[Tu 20:07:06.556] [updateMaxHeight] undefined -> 393 compose.js:278
[Tu 20:07:06.558] [setFocus] compose.js:267
[Tu 20:07:06.590] [api:respond] get_friends     Array[450]  api.js:13
[Tu 20:07:09.508] [api:respond] get_keepers     Object  api.js:13
[Tu 20:07:10.195] [hidePane] slider2.js:598
[Tu 20:07:10.307] [api:respond] get_keepers     Object  api.js:13
[Tu 20:07:10.407] [slider.mouseout] hiding slider2.js:85
[Tu 20:07:10.407] [hideSlider] mouseout slider2.js:277
[Tu 20:07:11.785] [onMessage] counts    Object
```

Background:

```
[Tu 20:06:59.189] [onMessage] 1157 api:handling ["kept", "counts"] api.js:280
[Tu 20:06:59.265] [onMessage] 1157 api:require  Object {paths: Array[1], injected: Object}  api.js:280
[Tu 20:06:59.266] [injectWithDeps] 1157 scripts/html/metro/slider2.js api.js:348
[Tu 20:06:59.483] [tabs.onUpdated] 1157 change:     Object  api.js:154
[Tu 20:06:59.526] [onMessage] 1157 log_event 
["slider", "sliderShown", Object]   api.js:280
[Tu 20:06:59.527] [logEvent] sliderShown    Object  main.js:165
[Tu 20:06:59.527] [socket.send] 
["log_event", Object]   api.js:561
[Tu 20:06:59.528] [onMessage] 1157 keeper_shown  api.js:280
[Tu 20:07:00.000] [onMessage] 1157 get_keepers  api.js:280
[Tu 20:07:00.000] [get_keepers] 1157 main.js:367
[Tu 20:07:00.002] [onMessage] 1157 api:require  Object {paths: Array[1], injected: Object}  api.js:280
[Tu 20:07:00.003] [injectWithDeps] 1157 scripts/html/keeper/titled_tip.js api.js:348
[Tu 20:07:00.141] [onMessage] 1157 log_event 
["slider", "sliderClosed", Object]  api.js:280
[Tu 20:07:00.142] [logEvent] sliderClosed   Object  main.js:165
[Tu 20:07:00.142] [socket.send] 
["log_event", Object]   api.js:561
[Tu 20:07:00.672] [onMessage] 1157 log_event 
["slider", "sliderShown", Object]   api.js:280
[Tu 20:07:00.672] [logEvent] sliderShown    Object  main.js:165
[Tu 20:07:00.673] [socket.send] 
["log_event", Object]   api.js:561
[Tu 20:07:00.673] [onMessage] 1157 keeper_shown  api.js:280
[Tu 20:07:00.687] [onMessage] 1157 get_keepers  api.js:280
[Tu 20:07:00.687] [get_keepers] 1157 main.js:367
[Tu 20:07:01.427] [onMessage] 1157 session  api.js:280
[Tu 20:07:01.430] [onMessage] 1157 api:require  Object {paths: "styles/metro/pane.css", injected: Object}   api.js:280
[Tu 20:07:01.431] [injectWithDeps] 1157 styles/metro/pane.css api.js:348
[Tu 20:07:01.586] [onMessage] 1157 api:require  Object {paths: Array[2], injected: Object}  api.js:280
[Tu 20:07:01.586] [injectWithDeps] 1157 scripts/html/metro/pane.js api.js:348
[Tu 20:07:01.587] [injectWithDeps] 1157 scripts/html/metro/pane_threads.js api.js:348
[Tu 20:07:01.605] [onMessage] 1157 pane Object {new: "/messages"} api.js:280
[Tu 20:07:01.656] [onMessage] 1157 api:require  Object {paths: "scripts/threads.js", injected: Object}  api.js:280
[Tu 20:07:01.657] [injectWithDeps] 1157 styles/antiscroll.css api.js:348
[Tu 20:07:01.658] [injectWithDeps] 1157 styles/metro/threads.css api.js:348
[Tu 20:07:01.659] [injectWithDeps] 1157 styles/metro/compose.css api.js:348
[Tu 20:07:01.660] [injectWithDeps] 1157 scripts/html/metro/threads.js api.js:348
[Tu 20:07:01.661] [injectWithDeps] 1157 scripts/html/metro/thread.js api.js:348
[Tu 20:07:01.661] [injectWithDeps] 1157 scripts/html/metro/compose.js api.js:348
[Tu 20:07:01.662] [injectWithDeps] 1157 scripts/lib/jquery.timeago.js api.js:348
[Tu 20:07:01.663] [injectWithDeps] 1157 scripts/lib/jquery-tokeninput.js api.js:348
[Tu 20:07:01.663] [injectWithDeps] 1157 scripts/formatting.js api.js:348
[Tu 20:07:01.664] [injectWithDeps] 1157 scripts/look.js api.js:348
[Tu 20:07:01.665] [injectWithDeps] 1157 scripts/throttle.js api.js:348
[Tu 20:07:01.665] [injectWithDeps] 1157 scripts/scrollable.js api.js:348
[Tu 20:07:01.666] [injectWithDeps] 1157 scripts/compose.js api.js:348
[Tu 20:07:01.667] [injectWithDeps] 1157 scripts/snapshot.js api.js:348
[Tu 20:07:01.667] [injectWithDeps] 1157 scripts/lib/antiscroll.min.js api.js:348
[Tu 20:07:01.668] [injectWithDeps] 1157 scripts/prevent_ancestor_scroll.js api.js:348
[Tu 20:07:01.669] [injectWithDeps] 1157 scripts/threads.js api.js:348
[Tu 20:07:02.089] [onMessage] 1157 threads  api.js:280
[Tu 20:07:05.403] [RWS.ping] rwsocket.js:115
[Tu 20:07:05.416] [RWS.pong] rwsocket.js:93
[Tu 20:07:05.905] [tabs.onActivated] tab info: Object {tabId: 130, windowId: 71} api.js:81
[Tu 20:07:05.905] [tabs.on.blur] 1157   Object  main.js:1176
[Tu 20:07:05.906] [tabs.on.focus] 130   Object  main.js:1162
[Tu 20:07:05.906] [kifify] 130 http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html# icons/keep.png http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html  main.js:929
[Tu 20:07:05.907] [socket.send] ["get_threads", 301, "http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html#"] api.js:561
[Tu 20:07:05.907] [scheduleAutoShow] scheduling tab: 130 main.js:1241
[Tu 20:07:05.949] [socket.receive] response 301 (42ms) api.js:534
[Tu 20:07:05.950] [gotThreadDataFor] 130  http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html# http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html [] main.js:1052
[Tu 20:07:06.423] [tabs.onActivated] tab info: Object {tabId: 1157, windowId: 71} api.js:81
[Tu 20:07:06.423] [tabs.on.blur] 130    Object  main.js:1176
[Tu 20:07:06.424] [tabs.on.focus] 1157  Object  main.js:1162
[Tu 20:07:06.425] [kifify] 1157 http://nymag.com/daily/intelligencer/2013/09/house-gops-legislative-strike.html?imw=Y&f=most-viewed-24h10 icons/keep.png http://nymag.com/daily/intelligencer/2013/09/house-gops-legislative-strike.html?f=most-viewed-24h10&imw=Y  main.js:929
[Tu 20:07:06.425] [socket.send] 
["get_threads", 302, "http://nymag.com/daily/intelligencer/2013/09/house…legislative-strike.html?imw=Y&f=most-viewed-24h10"]  api.js:561
[Tu 20:07:06.425] [scheduleAutoShow] scheduling tab: 1157 main.js:1241
[Tu 20:07:06.457] [socket.receive] response 302 (32ms) api.js:534
[Tu 20:07:06.458] [gotThreadDataFor] 1157  http://nymag.com/daily/intelligencer/2013/09/house-gops-legislative-strike.html?imw=Y&f=most-viewed-24h10 http://nymag.com/daily/intelligencer/2013/09/house-gops-legislative-strike.html?f=most-viewed-24h10&imw=Y [] main.js:1052
[Tu 20:07:06.458] [api.tabs.emit] 1157 counts   Object  api.js:611
[Tu 20:07:06.510] [onMessage] 1157 session  api.js:280
[Tu 20:07:06.559] [onMessage] 1157 get_friends  api.js:280
[Tu 20:07:06.573] [onMessage] 1157 api:handling ["thread_info", "message", "threads"] api.js:280
[Tu 20:07:09.505] [onMessage] 1157 get_keepers  api.js:280
[Tu 20:07:09.505] [get_keepers] 1157 main.js:367
[Tu 20:07:10.200] [onMessage] 1157 pane Object {old: "/messages"} api.js:280
[Tu 20:07:10.306] [onMessage] 1157 get_keepers  api.js:280
[Tu 20:07:10.306] [get_keepers] 1157 main.js:367
[Tu 20:07:10.408] [onMessage] 1157 log_event 
["slider", "sliderClosed", Object]  api.js:280
[Tu 20:07:10.409] [logEvent] sliderClosed   Object  main.js:165
[Tu 20:07:10.409] [socket.send] 
["log_event", Object]   api.js:561
[Tu 20:07:11.175] [tabs.onActivated] tab info: Object {tabId: 130, windowId: 71} api.js:81
[Tu 20:07:11.175] [tabs.on.blur] 1157   Object  main.js:1176
[Tu 20:07:11.175] [tabs.on.focus] 130   Object  main.js:1162
[Tu 20:07:11.176] [kifify] 130 http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html# icons/keep.png http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html  main.js:929
[Tu 20:07:11.176] [socket.send] ["get_threads", 303, "http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html#"] api.js:561
[Tu 20:07:11.176] [scheduleAutoShow] scheduling tab: 130 main.js:1241
[Tu 20:07:11.215] [socket.receive] response 303 (39ms) api.js:534
[Tu 20:07:11.215] [gotThreadDataFor] 130  http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html# http://nymag.com/news/business/boom-brands/tumblr-2013-10/index1.html [] main.js:1052
[Tu 20:07:11.718] [tabs.onActivated] tab info: Object {tabId: 1157, windowId: 71} api.js:81
[Tu 20:07:11.718] [tabs.on.blur] 130    Object  main.js:1176
[Tu 20:07:11.719] [tabs.on.focus] 1157  Object  main.js:1162
[Tu 20:07:11.719] [kifify] 1157 http://nymag.com/daily/intelligencer/2013/09/house-gops-legislative-strike.html?imw=Y&f=most-viewed-24h10 icons/keep.png http://nymag.com/daily/intelligencer/2013/09/house-gops-legislative-strike.html?f=most-viewed-24h10&imw=Y  main.js:929
[Tu 20:07:11.719] [api.tabs.emit] 1157 counts   Object  api.js:611
[Tu 20:07:11.720] [scheduleAutoShow] scheduling tab: 1157 
```

I think I can reproduce this consistently enough to demonstrate it for you tomorrow morning if I haven't figured out why it's happening.

**Comment by 2is10** [comment]
Thanks for testing it. I see the problem. Looks like sometimes eliza’s `"get_threads"` handler replies with `null` for the normalized URI, and I wasn’t expecting that. The `getPageData` response contains the prenormalized URI in the case that a URL has no corresponding `NormalizedURI` row in the database, and I was thinking eliza did the same.

**Comment by andrewconner** [comment]
Ah, I can fix that on the server side.

**Comment by 2is10** [comment]
That’d be awesome. I guess shoebox needs a new internal route that effectively exposes `NormalizedURIRepo.getByUriOrPrenormalize`.

**Comment by andrewconner** [comment]
I have it done, but have a couple questions for @stkem or @leogrim:

Is there a reason `getNormalizedURIByURL()` in ShoeboxController is using a readWrite? Is it because it needs retries often? If it's that, when does it fail? Should we build retries into readOnly db transactions?

I'm assuming there's a good reason for it, so would a `getNormalizedUriByUrlOrPrenormalize()` (good grief that's long) need the same (since it's basically the same call)?

Also, it looks like the Shoebox service client and controllers have grown to be quite large and unwieldy. Any objections if I break functionality into groups (ie, requests dealing with uris, etc)?

**Comment by leogrim** [comment]
I've seen and fixed the same pattern in some other place, not sure why this
is readWrite. You can go ahead and make it a readOnly. + Breaking up the
controller sounds like a good idea.

**Comment by 2is10** [comment]
I’ve tested a bit more and I think this is ready.

**Pull request merged**
