### PR TITLE
normalizeduri: always update sequence number on save

### PR DESCRIPTION
**Pull request by ymatsuda**
After this change, we update the sequence number of NormalizedURI whenever it is saved.

### CODE REVIEW

**Comment by 2is10** [comment]
@andrewconner is probably best to review, but out of curiosity, why the change? thanks.

**Comment by andrewconner** [comment]
Actually @gmethvin might be the best. He and Yasu moved to using sequence numbers.

**Comment by ymatsuda** [comment]
Indexer uses the sequence number of a URI as a high-water mark of indexing. Currently, the scraper is the only place that trigger the sequence number change. There is another place that changes URI state, OrphanClear, which changes the state from SCRAPED etc. to ACTIVE when no one is referencing the URI. When this happens, we want to delete the corresponding document from the index. So, I want to update the sequence number whenever the state changes. Doing the sequence number change in save may be an bit over generalization, but it is simpler API, and indexer won't miss any change.

**Comment by gmethvin** [comment]
lgtm

**Pull request merged**
