### PR TITLE
keeps: unkeep with extIds

### PR DESCRIPTION
**Pull request by raymondng**
Initial pass. This version only deals with (requires) external id.

The single version is basically a stricter version of what we have today. It's based on external id instead of relying url lookup. It also improves on robustness by attempting to catch/report (via Try) on error conditions.

The batch version will return two sets of results: "removedKeeps" and "errors". 

The error reporting likely needs some work -- right now it's really just some human readable string -- would love to talk to you about how to properly report/handle various error types.

cc: @ymatsuda @andrewconner @2is10 @eishay

### CODE REVIEW

**Comment by 2is10** [comment]
Haven’t looked at the code, but I’m generally okay with the idea.

One of the initial advantages we considered when sending a URL was that it
would allow the server to unkeep the passed URL and any duplicate keeps
that our system might have due to normalization issues. I understand that
the approach seems to have backfired. We might also consider sending both
an external ID and a URL to get the best of both worlds, if we think it’s
safe and worth the trouble.

**Comment by raymondng** [comment]
Thanks Jared for the feedback! 

Re: url -- I think as long as we keep the original url with the bookmark entry in the db (we didn't -- that bug was identified on Friday and fixed yesterday) then we have the relevant information for de-dup, so extId is probably sufficient for the purpose of this endpoint. Let me know if this makes sense.

**Comment by 2is10** [comment]
That seems fine to me.

Are we certain that renormalizations never result in a user having two keeps that normalize to same URI? In other words, are two keeps merged when a change in normalization logic makes them equivalent? If so, are we sure this operation is 100% reliable? Do we have a database constraint enforcing it, or an ongoing consistency check that will notify us if this invariant is violated? If not, then during an unkeep operation, it might be a good idea to look for any other keeps the user might have with the same normalized URI as the specified keep and unkeep them as well.

Don’t feel the need to respond here on github. Just something to think about if you haven’t already.

**Comment by raymondng** [comment]
What I realized in the last few days (I knew about it but it didn't sink
it) is that normalization is never perfect, given the state of the web urls
... I do think we have some safeguards and processes in place to mitigate
things, but I'd let yasuhiro and other experts to chime in on this -- yeah
probably not on github :)

**Pull request merged**
