### PR TITLE
open the members invite modal upon team creation

### PR DESCRIPTION
**Pull request by camhashemi**
@cvializ @andrewconner 

@JRuff42 this isn't exactly to-spec. the members invite modal is really easy to open from the /members page. would be extra work to get it to open from the boards page. so I'm just linking to the /members page upon team creation. maybe @cvializ knows a workaround?

### CODE REVIEW

**Comment by andrewconner** [comment]
@JRuff42's call, you may want to ask her in person in case she's not up-to-date on the guthubs.

**Comment by andrewconner** [comment]
Otherwise looks good :+1:

**Comment by JRuff42** [comment]
Whats the estimate on popping this up from the boards page?  If users close
it, I'd like for them to be on the boards/libraries page

**Comment by camhashemi** [comment]
I'll work on it before lunch and have it ready or an estimate by then.

**Comment by camhashemi** [comment]
@andrewconner @cvializ @JRuff42 opens from the libraries tab. right now just opens the 'add extra emails' tab since recos are not likely to be strong upon creation. once I add a threshold for PYMN, this will change.

**Comment by andrewconner** [comment]
:us:

**Pull request merged**
