### PR TITLE
starting to return some library info in /ext/page response

### PR DESCRIPTION
**Pull request by 2is10**
@eishay 
You’ve been in meetings, so I made a quick start on this. If the approach is not what you had in mind, then I’ll be happy to scrap this.

cc @leogrim

### CODE REVIEW

**Comment by 2is10** [comment]
We may need to ask `searchClient.augment` for more libraries than we want in case we need to filter some out. It would be cool if that endpoint supported the kind of filtering we need.

**Comment by eishay** [comment]
@2is10 you're too fast for me. Thanks!

**Comment by leogrim** [comment]
Which kind of filtering would be needed?

**Comment by 2is10** [comment]
There are still some TODOs for you!

**Pull request merged**
