### PR TITLE
I think we can safely remove this now

### PR DESCRIPTION
**Pull request by 2is10**
@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
There is one installation with 2.6.6 still installed (and the user does not have a newer one), but they appear to be largely inactive in terms of deliberate kifi activity. Mind waiting until we have version in the websocket, so we can tell if they're connecting?

I'm only concerned because it causes an exception on the server

edit: Silly me, version on the websocket doesn't help us with old clients. Up to you if you want it in.

**Comment by 2is10** [comment]
Sure. Happy to wait, although I don’t think adding the version to the
socket connection in the new extension code will help us figure out whether
this user is still connecting with 2.6.6.

**Comment by andrewconner** [comment]
Hah right after I said that I realized it wouldn't. I guess message edits don't get emailed too.

**Comment by andrewconner** [comment]
I checked logs, this user does not appear to be active.

**Comment by 2is10** [comment]
Jared invites you to Kifi:
Jared Jacobs is waiting for you to join Kifi

What is Kifi and Why should I join?

Kifi (short for keep it find it) allows you to easily keep and tag anything you find online - an article, video, picture, email, anything - then quickly find it on top of your favorite search engine results, together with relevant pages that your friends kept, too.

Kifi also lets you message your friends about what you keep and find alongside any webpage, to get their opinion and gain from their expertise.
Join Kifi: https://www.kifi.com

Kifi is available for desktop only on chrome and firefox.
Safari, Internet Explorer and mobile are coming soon!

Don't want to recieve these messages from Kifi? Unsubscribe here: https://www.kifi.com/unsubscribe/9vhBIIF2fltl-XvDtup4jF2b-EPB6YWDEYEJ-IDRvqUOfckuCj-5cRzauV2mSzAewpTEcvNSiN5y
LkqADvTrOQec-DMZWe9li2tEQX1lcNe_1rR5v6JKbQ

Kifi.com | 883 N Shoreline Blvd, Bldg A200, Mountain View, CA 94043 United States

**Pull request merged**
