### PR TITLE
non-kifi users can be invited to Libraries

### PR DESCRIPTION
**Pull request by ahsu1230**
added email_address field to LibraryInvites & tested
also added a numKeeps to LibraryInfo

@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Cool, will review. Are we including the `authToken` as well (primary for email invites)?

**Comment by ahsu1230** [comment]
just added!

**Comment by andrewconner** [comment]
Great! Will review tonight.

**Comment by ahsu1230** [comment]
thanks!

**Comment by andrewconner** [comment]
Sorry for the slow review! Looks great. When you're next in here, mind putting an index on the email address and auth token?

**Comment by ahsu1230** [comment]
oh ok sure thing!

**Pull request merged**
