### PR TITLE
Add entry points to create a team

### PR DESCRIPTION
**Pull request by cvializ**
@adamjgrant @andrewconner to be merged/modified after/with #17259

### CODE REVIEW

**Comment by andrewconner** [comment]
:+1:

**Comment by cvializ** [comment]
New icons, per Asana task
screen shot 2015-09-14 at 3 47 46 pm

**Comment by adamjgrant** [comment]
Forgot to comment. Good stuff! :+1:

**Comment by cvializ** [comment]
: D

**Pull request merged**
