### PR TITLE
cookie fix

### PR DESCRIPTION
**Pull request by raymondng**
This should fix the long-standing cookie issue wrt mobile.

@andrewconner 
cc: @thassss @jaredpetker @2is10

### CODE REVIEW

**Comment by andrewconner** [comment]
Great, thanks. Does the new actions support their existing cookie by itself?

**Comment by raymondng** [comment]
The new actions currently only support the play session cookie (i.e. there's no fallback). I'm a bit hesitant to add the fallback, but if it's needed, let me know.

**Comment by andrewconner** [comment]
Since mobile clients don't send the session cookie, it is needed.

**Comment by raymondng** [comment]
Sure. Just to confirm -- even if we set it, the mobile clients won't return it, right?

**Comment by andrewconner** [comment]
Yes, otherwise, this will never be fixed.

**Comment by jaredpetker** [comment]
To try and help, if this is about the kifi_session, older clients probably
don't send it, however we can make sure newer clients will be once it is
working properly.

**Comment by raymondng** [comment]
Sounds great. I'll add it then (the fallback)

**Comment by raymondng** [comment]
Merging this to make the play cookie available. Will add fallback in next PR.

**Comment by raymondng** [comment]
Pushed. @jaredpetker @thassss -- please let me know if you see any issues. Thanks!

**Pull request merged**
