### PR TITLE
UI to invite members with a comma separated list

### PR DESCRIPTION
**Pull request by cvializ**
@adamjgrant (for Tuesday : ) )

### CODE REVIEW

**Comment by cvializ** [comment]
screen shot 2015-09-04 at 5 32 11 pm
screen shot 2015-09-04 at 5 32 27 pm
screen shot 2015-09-04 at 5 32 01 pm
screen shot 2015-09-04 at 5 32 37 pm

**Comment by cvializ** [comment]
I'm unsure of the angle brackets in the "<< Back ..." link. It was in the spec in Asana, but I know those aren't always 1-1 specs. @adamjgrant do you think this is a good treatment for this use case?

**Comment by andrewconner** [comment]
I agree, I'd prefer even something unicode. ←, ◀, ↜, ⇜, ⇦

**Comment by adamjgrant** [comment]
What Andrew said.

and `&raquo; &laquo;` are nice too.

**Comment by adamjgrant** [comment]
This bit looks a little icky, but I know it's in the specs. 

screen shot 2015-09-08 at 10 06 54 am

**Comment by cvializ** [comment]
Do you think the text "Invite individuals..." is even necessary? I think we could remove it. Unless you think the "large team" text would seem like a misleading label for the content below it.

**Comment by andrewconner** [comment]
Agreed

**Comment by adamjgrant** [comment]
@cvializ I think you're on the right track. We could simplify the text here save some space.

**Comment by adamjgrant** [comment]
screen shot 2015-09-08 at 10 06 54 am

**Comment by cvializ** [comment]
Looks good to me, I'll add that in

**Comment by cvializ** [comment]
screen shot 2015-09-08 at 10 56 00 am
screen shot 2015-09-08 at 10 56 16 am

**Comment by adamjgrant** [comment]
Great! :+1:

**Pull request merged**
