### PR TITLE
add slack to registerModal

### PR DESCRIPTION
**Pull request by camhashemi**
@cvializ @andrewconner 

all auto-join flows except for login doesn't work (but login doesn't usually work anyways, I'm going to fix that)

screen shot 2016-02-05 at 12 34 15 pm

### CODE REVIEW

**Comment by cvializ** [comment]
I'd say it does look a bit large, but it's good for now. we can iterate on it later if need be. :ship:

**Comment by camhashemi** [comment]
that's cool, those buttons are a lot bigger than they need to be. the landing page has them all on one line.

**Comment by camhashemi** [comment]
@cvializ @andrewconner updated the buttons after @JRuff42 mentioned that we need the facebook logo on its auth buttons

**Comment by camhashemi** [comment]
updated again to use slack's monochrome logo

**Pull request merged**
