### PR TITLE
more consistent cache

### PR DESCRIPTION
**Pull request by yingjieMiao**
I found the old MemcachedCache a bit confusing. It is a FortyTwoCachePlugin that wraps a MemcachedPlugin, which in turn is a CachePlugin. MemcachedCache delegates three operations to MemcachedPlugin.api, and one other operation to MemcachedPlugin. 

I try to simplify things a bit and hope this is more consistent. 

@leogrim  @eishay @andrewconner

### CODE REVIEW

**Comment by ymatsuda** [comment]
Thanks. I had the same feeling. It was confusing. It looks much better after your refactoring.

**Comment by andrewconner** [comment]
Nice job!

**Comment by leogrim** [comment]
Much cleaner!
We could probably split the FortyTwoCache file into several, it's getting quite large with this new addition.

**Comment by yingjieMiao** [comment]
Indeed. I though that too.

**Pull request merged**
