### PR TITLE
library name truncate & rework library follower smart scrolling

### PR DESCRIPTION
**Pull request by ahsu1230**
@andrewconner @yipingliao 
@2is10 using the multi-line ellipsis! http://www.mobify.com/blog/multiline-ellipsis-in-pure-css/

normal-case:
library-card-title-normal

bad-case:
library card title worst

### CODE REVIEW

**Comment by andrewconner** [comment]
Let's clear this by product before merging, since it's unfortunately visually different. Looks like there's a script solution: http://dotdotdot.frebsite.nl/

**Comment by yipingliao** [comment]
Thanks for fixing these two issues. :+1: 

Looks like dotdotdot is almost 700 lines of code!

**Comment by 2is10** [comment]
Looks like that script solution uses binary search, like I suggested to Aaron/Yiping on Friday.
We could write just the functionality we need in 15-20 lines, I bet.

**Comment by andrewconner** [comment]
I vote for that. This implementation is a lot simpler, but doesn't look close to the designs. We should drop it entirely (ie, hard cut off) or try to get it close to the design.

**Comment by ahsu1230** [comment]
closing PR since stuff needs to get reworked anyway

**Pull request closed without merging**
