### PR TITLE
Safer access when there's no settings available

### PR DESCRIPTION
**Pull request by andrewconner**
@camhashemi @cvializ

### CODE REVIEW

**Comment by andrewconner** [comment]
This currently throws when a non-admin views this page. By the way, I don't think we should have such a monolithic object for organizations. Currently, the object is always there (even if you're not in an organization), and we're digging deep into it to get the settings (which may or may not be there).

So the router is happily sending people to pages that they shouldn't really have access to.

**Comment by cvializ** [comment]
so this throws and sends them to the whomp page?

**Comment by camhashemi** [comment]
no whomp, just a blank page. Happy to do more incremental get/set APIs for settings, the sets have already been transitioned to be incremental.

**Pull request merged**
