### PR TITLE
add slack icon to libraries that have lib-to-slack integrations

### PR DESCRIPTION
**Pull request by camhashemi**
@cvializ @andrewconner 

I couldn't find an SVG for the slack monochrome logo, but once I can get one the next step would be to replace the .png with that.

### CODE REVIEW

**Comment by camhashemi** [comment]
screen shot 2016-04-22 at 2 35 06 pm
screen shot 2016-04-22 at 2 35 10 pm
screen shot 2016-04-22 at 2 35 15 pm

**Comment by cvializ** [comment]
nice! the monochrome icon looks a little large/cramped to me in the hover card and the chip. what do you think?

**Comment by camhashemi** [comment]
yup, it did. here's them more tidy.

**Comment by camhashemi** [comment]
screen shot 2016-04-22 at 4 47 48 pm

**Comment by cvializ** [comment]
aw yea 👍 👍

**Pull request merged**
