### PR TITLE
[wip] start using jshint in the extension

### PR DESCRIPTION
**Pull request by cvializ**
We're going to get this thing linted.

### CODE REVIEW

**Comment by andrewconner** [comment]
Oh great. This may be a tricky process :)

**Comment by andrewconner** [comment]
... or did this fix everything?

**Comment by cvializ** [comment]
I wish, just quotes for now : P do you think it's a worthwhile investment of time?

**Comment by andrewconner** [comment]
How bad is it? We may be able to come up with a subset of the rules that catches most of the problems without getting in the way. Things like cyclomatic complexity, expressions not returning anything, etc may be annoying to "fix".

**Comment by cvializ** [comment]
Agreed. It isn't in a bad state, it's just noisy. Low-priority+easy is cosmetic stuff, like quotes. Low-priority+hard is the cyclomatic complexity, side-effecting expressions. Higher-priority+easy is incorrect use of semicolons and declaring variables correctly. Higher-priority+harder is undefined checking, because there are a lot of globals we're sharing across `@require`d moduled

**Comment by andrewconner** [comment]
Yep, awesome way of wording it. Let's cap this to the "Higher-priority+easy" for now. That will catch things like the extra `)` and such.

**Pull request closed without merging**
