### PR TITLE
non-linear scoring for library recommendations

### PR DESCRIPTION
**Pull request by ymatsuda**
@eishay @joshm1 @stkem @yingjieMiao 

Things done
- added non-linear scoring for library recommendations.
- added incrementDeliveredCount to LibraryRecommendationRepo and actually increment the counts when recommendations are delivered.

Things missing
- diversification is not in place because topic information is not available for each library reco, but I added the default selection strategy so that we can added the diversified selection strategy easily.
- analytics is missing
- feedback for library recos has not endpoint in shoebox.

### CODE REVIEW

**Comment by ymatsuda** [comment]
The library non-linear scoring is under the same experiment (curator_nonlinear_scoring).

**Comment by yingjieMiao** [comment]
lgtm

**Comment by joshm1** [comment]
nice. :+1:

**Comment by eishay** [comment]
Cool!

**Pull request merged**
