### PR TITLE
add a lock on settings page for members

### PR DESCRIPTION
**Pull request by camhashemi**
@cvializ @andrewconner 

screen shot 2015-10-21 at 4 13 34 pm

### CODE REVIEW

**Comment by andrewconner** [comment]
Nice

**Comment by cvializ** [comment]
Nice work. A few comments:
- I think Jen said she wanted the lock to be gray, even though it's red in the Asana task
- Design nitpick, it should probably be moved upward a few pixels. It doesn't look visually centered, even though it's probably numerically centered.
- Looks a slightly large to me. What do you think?

**Comment by andrewconner** [comment]
Whoops, picture didn't load for me initially. @cvializ's comments are spot on.

**Comment by camhashemi** [comment]
I love design nitpicks :) thanks guys. Jen agrees with the size, said that she prefers it red if it won't be too shocking.

**Comment by camhashemi** [comment]
screen shot 2015-10-22 at 10 17 03 am

**Comment by camhashemi** [comment]
screen shot 2015-10-22 at 10 12 20 am

**Comment by cvializ** [comment]
lgtm :+1:

**Comment by camhashemi** [comment]
@cvializ grey or red?

**Comment by cvializ** [comment]
I think grey makes more UX sense. Let's go with that and sync with Jen later. It's one line to change it afterward

**Comment by JRuff42** [comment]
@leogrim - You were a proponent of the lock, right?  Does grey seem obvoius enough?  I think it works quite well given the size.

**Comment by leogrim** [comment]
Whatever Carlos decides :)

**Comment by cvializ** [comment]
I decide grey : D

**Pull request merged**
