### PR TITLE
Supporting Slack extension redirects

### PR DESCRIPTION
**Pull request by andrewconner**
@cvializ Not sure if you've seen how our deep linking works. Currently, some email links are `https://www.kifi.com/r/some-uuid`. That url delivers basically a blank page, that attempts to inject data into the extension using a `data-kifi-deep-link` attribute populated with JSON. The extension listens on these URLs, and if it finds that attribute, redirects the browser and knows what to do next. If nothing happens in `x`ms, there's a `window.location = ...` on the page that completes the redirect.

This supports `/s`/ links too, which are redirects from Slack (the reason we're not using `/r/` is backend technical... the bit after the `/r/` is an id).

@camhashemi

### CODE REVIEW

**Comment by camhashemi** [comment]
If I understand correctly, we also want to add `/redir` to the `matches` list, since that also returns pages with `data-kifi-deep-link`.

**Comment by andrewconner** [comment]
Oh, weird. You're absolutely right. I have no idea how it's getting injected... _maybe_ the `@match` annotation is rewriting this json. Will update.

**Comment by camhashemi** [comment]
Today I've been having trouble getting the ext to open from `/redir`, but I'm pretty sure I've been able to before.

**Comment by andrewconner** [comment]
This is a head scratcher. I looked at our Chrome package, and `redir` isn't there at all. But it works in prod for me, which means the script is getting injected. Weeeirrrdddd

**Comment by andrewconner** [comment]
@camhashemi Updated to include `redir`. I still have no idea how it's working. Maybe @cvializ knows

**Comment by camhashemi** [comment]
:+1: this will help for the new slack redirects (no idea about how `/redir` is working)

**Comment by camhashemi** [comment]
is this entirely a browser-level change, or might we need to implement some logic depending on what version of the extension you have? (since new versions will accept deep links from `/s/` while others won't)

**Comment by cvializ** [comment]
Redir is working from an `@match` decoration in `deep_link_redirect.js`
The `@match` is parsed by a build step in the `gulpfile` that builds the data structure in `meta.js`. Essentially it makes the script with the decoration a content-script. I am not sure what the role of entries in `manifest.json` is, but I can vouch for the `@match` working

``` js
// from meta.js, constructed by the gulpfile
["scripts/deep_link_redirect.js", /^https?:\/\/(dev\.ezkeep\.com:9\d{3}|www\.kifi\.com)\/(r\/|redir).*/, 1],
```

**Pull request merged**
