### PR TITLE
Adding org selector to library widget

### PR DESCRIPTION
**Pull request by adamjgrant**
https://app.asana.com/0/42964066412484/49246122596873

### CODE REVIEW

**Comment by adamjgrant** [comment]
screen shot 2015-09-10 at 5 37 53 pm
screen shot 2015-09-10 at 5 37 58 pm

**Comment by adamjgrant** [comment]
@andrewconner @cvializ

**Comment by cvializ** [comment]
The top check mark looks cut off to me

**Comment by andrewconner** [comment]
Nice. The spacing of the bottom privacy section (very airy) and above it in the location section (tight) seem to conflict to me. What do you think?

**Comment by adamjgrant** [comment]
@cvializ You might be right, I'll take a look.

@andrewconner Yeah, maybe we can do something about that. We should also consider the spacing that appears on hover, it's justified a bit more

screen shot 2015-09-10 at 5 42 03 pm

That being said, I think we can tighten it. Stay tuned.

**Comment by andrewconner** [comment]
Thanks for the screenshots!

**Comment by cvializ** [comment]
^ what he said

**Comment by adamjgrant** [comment]
screen shot 2015-09-10 at 5 44 08 pm
screen shot 2015-09-10 at 5 44 18 pm

I thought it might have been due to `overflow: hidden` somewhere, but it's actually not cut off. However, it does appear differently than on the manage library modal.

Anyway, here are tweaks @andrewconner @cvializ 

screen shot 2015-09-10 at 5 52 21 pm

**Comment by andrewconner** [comment]
I like

**Comment by cvializ** [comment]
Oh I think it's the border radius is too large for the size of the
checkmark. Try decreasing those radii

**Comment by adamjgrant** [comment]
(discussed with @cvializ offline)

**Pull request merged**
