### PR TITLE
check count > 0

### PR DESCRIPTION
**Pull request by raymondng**
To accommodate default value of -1 for counts

@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Could we use `Option[Int]` for that field?

**Comment by raymondng** [comment]
Yes we could do that, though the "optionality" (?!) will be very short-lived (i.e. as soon as we remove the experiment, it'll likely not be optional).

**Comment by andrewconner** [comment]
Go for it. (My Kifi is logged out because I'm working on the marketing pages, sorry I missed your messages)

**Comment by raymondng** [comment]
Np. Thanks!

**Pull request merged**
