### PR TITLE
some refact in scrapeWorker

### PR DESCRIPTION
**Pull request by yingjieMiao**
@raymondng 

No essential logic changes. Just factored out a few methods to break down giant functions. 

factored out a `needReIndex` method to replace a giant if condition. Please double check. 

Thanks.

### CODE REVIEW

**Comment by raymondng** [comment]
long overdue. :+1:

**Comment by raymondng** [comment]
@leogrim please also take a look

**Comment by yingjieMiao** [comment]
later we might want to split the file into smaller ones.

**Comment by raymondng** [comment]
Sounds good to me!

**Comment by leogrim** [comment]
:+1:

**Pull request merged**
