### PR TITLE
only lowercasing the domain part of an email address during canonicalization

### PR DESCRIPTION
**Pull request by 2is10**
@leogrim I think it’d be better to preserve the case of the local part (mailbox name) since:
1. Some people have a strong preference for capitalizing their name in their email address.
2. We’re not strictly allowed to alter the case of the local part.
3. We can still do case-insensitive comparisons wherever we choose to.

Right now all email address columns in the database are case-insensitive, yes?

### CODE REVIEW

**Comment by leogrim** [comment]
I'm not sure about the database. We also do in-memory comparisons in some situations: ABook imports at least and I'm not sure about how type-ahead deals with case.

**Comment by leogrim** [comment]
Yes, it looks like MySQL is case-insensitive by default. Being aware of this, I can be careful in our current code. But in the future I'm a bit afraid of having a different equality behavior in the DB vs in the code, it may lead to unexpected integrity constraint violations. What do you think?

**Comment by 2is10** [comment]
Those are valid concerns. I think it should be the responsibility of each use case to decide whether it makes sense to ignore the case. For example, for typeahead, it’s pretty clear that case should not matter. When building the index and performing searches, the typeahead code should have the responsibility of handling case, and it does properly (see `PrefixFilter.normalize`, which is used both at index creation time and at query time).

I sent this pull request thinking that most (if not all) email address comparisons are done in the database (typeahead excluded because it’s a prefix search, not an actual comparison). You mentioned that in-memory comparisons are done for ABook imports. If you can be more specific, I’ll find the code and make sure this pull request preserves the current behavior.

If it turns out that we are in fact already doing in-memory comparisons that should be case insensitive, I’ll add a helper method in `EmailAddress` to perform those, and then use it instead of strict equality at those places in the code as part of this pull request. Sound good?

(I don’t think this pull request will increase the risk of integrity constraint violations because we generally query the database for a value before inserting. If we’re using email addresses as memcache keys anywhere, then we need to be sure to lowercase them first. Did you see that anywhere during your recent refactorings?)

**Comment by leogrim** [comment]
No worry, I'm (finally) getting to modifying EContactRepo and rewriting the relevant parts of EContactUpdater and ABookCommander tomorrow, so I will take care of ABook. 

Then, there's no constraint yet on UserEmailAddressRepo, but there should be if we want to avoid an email address to be claimed by two different users, so we need to be careful while interning there as well. 

Finally there's the "containsNonUser" method on NonUserThread that relies on EmailAddress for thread merging, so we probably want to use case-insensitive equality there as well.

That's all I can think of for now, adding @stkem and @andrewconner for additional recall :)

**Comment by 2is10** [comment]
I’ve added case-insensitive `EmailAddress` comparison for future use, as we discussed. Merging now.

Thanks again for the thoughtful review.

**Pull request merged**
