### PR TITLE
Using RequestConsolidator in cache

### PR DESCRIPTION
**Pull request by leogrim**
@ymatsuda @stkem @eishay 
Thoughts?

### CODE REVIEW

**Comment by ymatsuda** [comment]
I like it!

**Comment by eishay** [comment]
smart! I'm not sure that doing it in the in memory cache (ehcach) would give better performance as there's still some overhead. would we want to limit it to memecached access?

**Comment by leogrim** [comment]
orElse is only evaluated once we have run out of caches, so it's not so much about consolidating requests to Memcached (which I think are synchronous anyway) but about consolidating cross-server requests that will be used to populate the caches after a miss. Did I get this right? :)

**Comment by stkem** [comment]
:+1: Although it wood be nice if it were overridable per lookup when needed, e.g. a signature something like `get(key: Key[T], doConsolidate: Boolean = true)`

**Comment by eishay** [comment]
@leogrim missed it, looks cool

**Comment by leogrim** [comment]
@stkem increased flexibility

**Comment by eishay** [comment]
are we doing it?

**Comment by leogrim** [comment]
I haven't collected a clear use case yet, so I haven't merged it in order not to add dead code. Any idea where we could benefit from this? Everywhere?

**Comment by eishay** [comment]
is it still open?
What do you want to do with it?

**Comment by stkem** [comment]
closing time for now?

**Comment by leogrim** [comment]
Let's close it for now

**Pull request closed without merging**
