### PR TITLE
Capping tags to 500 (this does "break" some expected behavior, for instance connecting tags to keeps).

### PR DESCRIPTION
**Pull request by andrewconner**
Anything broken should probably use a join instead, rather than needing every tag.

I will go through all usages and see if I can make them more efficient.

### CODE REVIEW

**Comment by andrewconner** [comment]
@eishay Please review.

**Comment by andrewconner** [comment]
several minor fixes added. @raymondng @leogrim 

Analytics tweaks, fixing KeepImporter to not dump the world on failure :), capping tags to 500.

**Comment by andrewconner** [comment]
@martinraison This adds the new `KeepSource`s

**Comment by raymondng** [comment]
lgtm

**Pull request merged**
