### PR TITLE
remove singletons from controllers

### PR DESCRIPTION
**Pull request by eishay**
/cc @andrewconner @stkem

### CODE REVIEW

**Comment by eishay** [comment]
wooooooooo pull req #3000 :-)

**Comment by stkem** [comment]
Looks good to me. The only concern I have is wether all out controllers are actually stateless. If there is one that isn't this will cause possibly very strange problems. @eishay @andrewconner you know wether this is the case much better than me.

**Comment by yingjieMiao** [comment]
I recently wrote a ExpertRecommenderController, which is stateful.

What was the motivation for removing singleton from controllers?

**Comment by andrewconner** [comment]
@yingjieMiao Perhaps the statefullness should be in a separate singleton? /cc @eishay

**Comment by yingjieMiao** [comment]
yeah.  Eishay talked to me about this. 

emails have serious delay problem.

**Pull request merged**
