### PR TITLE
send down all orgs in one field

### PR DESCRIPTION
**Pull request by camhashemi**
@cvializ @leogrim cleaning up the API

### CODE REVIEW

**Comment by camhashemi** [comment]
@cvializ I've actually developed a position against this: it'll require us to use a `filter` or some other mapping function on the client to know the difference between orgs. for example, #18252 assumes that `me.orgs` is all orgs that you're in. I saw in `profileWidget.js` that we end up concatenating all orgs anyways, so saw an opportunity to clean up, but not sure it's best.

**Comment by cvializ** [comment]
we concatenate them in `profileWidget.js` because we want to show them all together. if we only need them concatenated in one place, then it makes sense to keep them separate. now that I think about it, this will also break the space selector at the top of the page (unless we want to show pending orgs at the top. we might, but it's a Product question I think)

**Comment by camhashemi** [comment]
:+1: thanks

**Comment by camhashemi** [comment]
we probably don't want to do that yet :)

**Pull request closed without merging**
