### PR TITLE
distributing tasks by simple hashing

### PR DESCRIPTION
**Pull request by ymatsuda**
@eishay 
FYI @stkem @andrewconner 
- allowing distribution of tasks, which are currently executed by a leader, by hashing task names
- using this only in curator for now to see the behavior in prod.

### CODE REVIEW

**Comment by andrewconner** [comment]
I like.

**Comment by eishay** [comment]
wohooooo!!!

**Comment by yingjieMiao** [comment]
nice!

**Comment by eishay** [comment]
I think we should kill `scheduleTaskOnLeader` and use only the new method to reduce load on the leader machine.
@all What do you think?

**Comment by stkem** [comment]
Sweet! +1 on what Eishay said, once this is validated.
I simple test for the hashing part in particular might be good, so people don't break it by accident in the future.

**Pull request merged**
