### PR TITLE
admin to config lda topics

### PR DESCRIPTION
**Pull request by yingjieMiao**
@stkem @eishay 
1. admin page to edit topic names, and enable/disable topics (e.g. hide certain topics). 
2. backend support to persist the config. In S3 store (and in memory)

### CODE REVIEW

**Comment by eishay** [comment]
I think @stkem would be much more knowledgeable about it then myself

**Comment by stkem** [comment]
Code looks good overall. What does it mean exactly to hide certain topics (i.e. what is the effect elsewhere)?
Also, again, this sort of thing belongs in a database. We are completely misusing S3.

**Comment by yingjieMiao** [comment]
hidden could imply: do not show this topic name to user (frontend), or, even do not report them at all from backend. e.g. do not report to graph. 

the configuration doesn't change frequently, so I opt out for the database.

**Comment by stkem** [comment]
It's not about the frequency of change, it's about visibility/emergency edit-ability.

**Pull request merged**
