### PR TITLE
Refactoring to use gulp-cached and gulp-remember

### PR DESCRIPTION
**Pull request by martinraison**
@2is10 I think this makes the code much easier to understand and maintain, and the performance is better too (no temporary files written to disk + caching is used not only for styles, but also scripts and meta snippets)
Also I switched back to using the official gulp-livereload plugin (more robust, even though we're not using all its capabilities)

### CODE REVIEW

**Comment by martinraison** [comment]
note: restarting gulp is probably required when creating/deleting a file (I think handling deletions is possible, creations is a bit more tricky)

**Comment by 2is10** [comment]
very nice!

**Comment by 2is10** [comment]
Hmm... I’m seeing a few differences in the generated output after this pull request. I’m afraid it might break things.

**Comment by 2is10** [comment]
I’ve been using `diff -r` to do tree diffs. It may come in handy for debugging. (kifi.zip and kifi.xpi can be unzipped and diffed too.)

Here are some of the diffs I’m seeing:

```
diff -r g_before/chrome/scripts/deep_link_site.js g_after/chrome/scripts/deep_link_site.js
14,15d13
< api.injected['scripts/deep_link_site.js']=1;
< //@ sourceURL=http://kifi/deep_link_site.js
```

```
diff -r g_before/chrome/scripts/html/guide/step_1.js g_after/chrome/scripts/html/guide/step_1.js
2c2
< api.injected['scripts/html/guide/step_1.js']=1;
---
> api.injected['html/guide/step_1.js']=1;
```

**Comment by martinraison** [comment]
Oh yes, sorry, I can observe that as well. Let me look into it.

**Pull request merged**
