### PR TITLE
Keeping search warm in the extension

### PR DESCRIPTION
**Pull request by stkem**
This should ensure that the DNS for search.kifi.com is always cached
locally and that we always have a valid SSL session, eliminating both
the DNS lookup and SSL handshake with high probability. 
Not sure if it's a good idea to do this way.
RFC @2is10 @ymatsuda @eishay

### CODE REVIEW

**Comment by eishay** [comment]
looks good, though a bit aggressive imo. a good short term solution in any case until we'll have many users. 
how about creating an end point in nginx so the call won't hit play?
even better, is there an end point in the elb we can hit?

**Comment by stkem** [comment]
There isn't anything in the ELB we can hit, but having nginx handle it is a great idea! Thinking about it, if there is a way we can not send to cookies in the request, that would be even better. @2is10 do you know if thats easily possible?

**Comment by 2is10** [comment]
I don’t think this is a very good idea. Too heavy. Anyone who know anything about HTTP or browser developer tools could observe this and write up an awful blog post about it.

Let’s do it when focus goes into the location bar or a search field, as discussed. If it’s important to have this right away, let’s prioritize it, and I’ll do it right away.

**Comment by 2is10** [comment]
Looks like the [chrome.webRequest API](http://developer.chrome.com/extensions/webRequest.html#life_cycle) would let you remove cookies from a specific request (in `onBeforeSendHeaders`). Probably not in Firefox, or at least not so easily.

**Pull request closed without merging**
