### PR TITLE
Settings page new design

### PR DESCRIPTION
**Pull request by stkem**
done modulo icons and possible the email and password editors.
@andrewconner @martinraison

### CODE REVIEW

**Comment by andrewconner** [comment]
Awesome!

**Comment by martinraison** [comment]
Great! looks good (as far as the CSS interpreter inside my brain goes)

**Comment by andrewconner** [comment]
I have noticed that Martin is using liberal use of `constants.styl`. Perhaps we should all do that?

**Comment by stkem** [comment]
Argh, accidentally merged master into this, so there is a bit of noise.
I'll move some colors and font settings to constants.styl and then merge

**Pull request merged**
