### PR TITLE
htpclient_json_not_null

### PR DESCRIPTION
**Pull request by raymondng**
This is what I alluded to earlier. This simple change should work but I am probably least familiar about json amongst folks here so ... let me know your take.

cc: @eishay 
cc: @ymatsuda

### CODE REVIEW

**Comment by andrewconner** [comment]
If I remember right, this is a bug in Jackson. So: not something you _should_ have to do, but you do for now.

(It bit us pretty bad in the past. @stkem and I spent a day on it.)

**Comment by raymondng** [comment]
Thanks. I figured this is likely not the intended behavior. We should probably file a bug in jackson and/or play ...

**Comment by andrewconner** [comment]
They know about it. I believe it's fixed in Play 2.2

**Comment by raymondng** [comment]
Good to know.

**Pull request merged**
