### PR TITLE
some statsd

### PR DESCRIPTION
**Pull request by yingjieMiao**
@stkem

### CODE REVIEW

**Comment by stkem** [comment]
:+1: :+1:

**Comment by yingjieMiao** [comment]
i don't think data are coming in. In fact, non of the statsd data.

I guess we didn't migrate statsd from marvin to arthur (or elsewhere)

**Comment by stkem** [comment]
marvin is still alive, so that should not be affected. _All_ statsd is broken?

**Comment by yingjieMiao** [comment]
i think so. just look at existing admin pages.

**Pull request merged**
