### PR TITLE
Tracking of deployments in StatsD.

### PR DESCRIPTION
**Pull request by leogrim**

### CODE REVIEW

**Comment by andrewconner** [comment]
Nice. We may want to keep track what type of service this is when it's deployed.

**Comment by leogrim** [comment]
That should be taken care of by the general settings of StatsD. StatsD has a different flag in the conf file for each service, that prefixes every metric recorded.

**Comment by yingjieMiao** [comment]
Great.

Is there a better place to increment this count?

like ShoeboxGlobal, SeachGlobal?

**Comment by leogrim** [comment]
FortyTwo Global I guess, I move it there.

**Comment by eishay** [comment]
nice

**Pull request merged**
