### PR TITLE
avoid autoboxing of Long in ProbabilityDensity

### PR DESCRIPTION
**Pull request by ymatsuda**
@eishay @leogrim @yingjieMiao @stkem 

It seems that the autoboxing of Long in ProbabilityDensity creates a huge number of objects and consuming Graph's heap rapidly (analyzed using yourkit). This could be a cause of full GCs.

### CODE REVIEW

**Comment by ymatsuda** [comment]
I meant Double, not Long. Sorry.

**Comment by stkem** [comment]
Nice find! Also, check out http://scala-miniboxing.org/index.html which might help with stuff like that if we find more occurrences.

**Comment by raymondng** [comment]
Nice :+1:

**Comment by leogrim** [comment]
Cool! @stkem even had a task to try Miniboxing out at some point, among other ideas: https://app.asana.com/0/11645953228207/14934497049443

**Pull request merged**
