### PR TITLE
renaming UserThread.notificationPending to UserThread.unread for clarity

### PR DESCRIPTION
**Pull request by 2is10**
What do you think of this rename @stkem and @andrewconner? It really helps me to think of the field as a property of the `UserThread` rather than the associated notification. I also find "pending" to be an ambiguous term, as a notification could be pending in many senses — pending creation, pending socket broadcast, pending mobile push, pending inclusion in an email, pending being seen by user, pending a user visit to the underlying thread, etc.

We can eventually rename the column in the database too.

I renamed related methods too.

### CODE REVIEW

**Comment by stkem** [comment]
I agree that "pending" isn't the best naming, however the "...UnreadThread..." parts in the methods isn't super clear either, since they could be global notifications. How about "...UnreadNotification..."?

**Comment by 2is10** [comment]
Thanks for reviewing. I agree that "...UnreadThread..." isn’t super clear when it refers to a "global notification". We did choose to represent those with one each of a `UserThread`, `MessageThread`, and `Message` in the database, though, so it seems consistent to use the same terminology in these method names. More importantly, perhaps, I’m afraid that the most natural interpretation of the phrasing "...UnreadNotification..." is that the notification (a summary of the thread) has not yet been read, when in fact what "unread" refers to here is the thread itself (whatever the notification represents and links to). So I prefer "...UnreadThread..." over "...UnreadNotification..." for its clarity. Convinced?

**Comment by 2is10** [comment]
Let me describe my thinking a little further. Based on the latest product designs, I’m thinking of the `lastNotification` field as a general-purpose thread summary JSON field instead of something specific to notifications. One of the field’s purposes is to make it convenient to format notifications (sent in real time over the socket or later via email). Another of its purposes is to make it easy to format thread lists like the new Inbox, the Sent view, the On This Page view, etc. In the new UI, those views are not labeled as “Notifications”. They directly represent the message threads. So in the new (product-driven) terminology, the term “notification” should really be limited to the things that we send in real time or near real-time. There will be no historical views of notifications. So we may want to eventually shy away from using the term “notification” in the name of the JSON field and some of the related fields, like `notificationUpdatedAt`. I’m not saying we need to do that right away, but I think it does make sense to avoid propagating the term “notification” even further throughout the domain model of messaging and message threads than it already is.

**Comment by 2is10** [comment]
Merging this now because I have another pull request ready that conflicts with this one. Happy to have a naming discussion in person tomorrow, Tuesday or whenever.

**Pull request merged**
