### PR TITLE
Public library search

### PR DESCRIPTION
**Pull request by yipingliao**
@andrewconner 

Public library search. Includes:
- Some tracking
- Turning tags back on.

It ended up being a long-ish project. My brain is all tied up right now but I do hope to refactor some of this code once my head clears up. Argh.

https://app.asana.com/0/19898402862947/19898402862983

### CODE REVIEW

**Comment by yipingliao** [comment]
FYI, after much wrangling with phantomjs and karma, all the tests passed in dev. :)

**Comment by andrewconner** [comment]
Pulled in locally. Found a few bugs, not pushing today.

**Comment by yipingliao** [comment]
Please catch me when you have a few minutes, or send me a quick email and I'll start tracking down the bugs.

**Comment by yipingliao** [comment]
@andrewconner I have addressed the issues you brought up this morning:
- Even when you type fast, public library search bar will not go into strange state where it reloads on every keystroke.
- Curator picture transition is a bit smoother.
- Removed opacity animation during transition for the search bar.
- Removed the horizontal scroll caused by CSS styling of white background for the library card header.

If you can do a sanity check, I think we can merge. :)

**Comment by andrewconner** [comment]
- Infinite scroll broken on search results (http://dev.ezkeep.com:8080/rick-powell/film-the-measure-of-all-things/find?q=film&f=a)
- I am still able to inconstantly reproduce the focus-losing issue, have done so on several tabs.
- Worried about performance when closing the search (after searching). Happy to show you. This may be a "later" sort of thing.

**Comment by andrewconner** [comment]
Just pulled and tested, looks good. Let's grab Mark this morning to get a product confirmation.

**Pull request closed without merging**
