### PR TITLE
remove need to pass/create db session to access normalized uri rules

### PR DESCRIPTION
**Pull request by eishay**
@leogrim @raymondng @yingjieMiao

### CODE REVIEW

**Comment by leogrim** [comment]
So that means we need to bounce to reload the rules?

**Comment by eishay** [comment]
this is not a change from the current state, is it?
right now we cache the rules in memory indefinitely unless there's a save action in this machine.

**Comment by leogrim** [comment]
Yes you're right. It looks like a good use case for @andrewconner 's use of Guava

**Comment by eishay** [comment]
in what way?
the caching part?

**Comment by leogrim** [comment]
Yes, so that they are asynchronously updated regularly. I'm just thinking
of a crisis mode where we need to update these rules quickly because a
server is stuck in some infinite loop. Though we could still bounce in such
a scenario, so this is probably not worth spending effort now.

2014-06-19 18:10 GMT+02:00 Eishay Smith notifications@github.com:

**Comment by eishay** [comment]
Sure

**Pull request merged**
