### PR TITLE
release new twitter library cta

### PR DESCRIPTION
**Pull request by ahsu1230**
@andrewconner @sterlingz

### CODE REVIEW

**Comment by ahsu1230** [comment]
ready whenever

**Comment by andrewconner** [comment]
Could you make it link directly to https://www.kifi.com/twitter/request, since they're clicking a "join" type button?

**Comment by ahsu1230** [comment]
yup, already does =)

```
<div ng-if="twitterHandle">
      <a class="kf-pbc-link kf-pbc-link-continue" ng-click="join($event, 'twitter')" href="/twitter/request" target="_self">Join Now</a>
    </div>
```

**Comment by andrewconner** [comment]
Oh dang, good. Good to go then.

**Pull request merged**
