### PR TITLE
Minor syntactical tweaks

### PR DESCRIPTION
**Pull request by andrewconner**
Some very minor syntactical tweaks, @ahsu1230. IntelliJ was offering suggestions for improvements, and I made `formatLibraryUrl` not need a BasicUser (since it isn't always available).

### CODE REVIEW

**Comment by ahsu1230** [comment]
Ok! I think I got the gist lol - will keep that in mind in the future.

**Comment by andrewconner** [comment]
IntelliJ puts yellow lines in code areas it recommends for improvement. The big one here was unnecessary `{}` in multi-line match statements. I think we follow not using them in most (all?) of the code so just changed it to be consistent.

**Comment by ahsu1230** [comment]
I see. I'll clean up as we add more BE stuff

**Comment by ahsu1230** [comment]
I guess how much of yellow lined recommendations from IntelliJ do you follow then?

**Pull request merged**
