### PR TITLE
scraper: always get multiple values from metadata

### PR DESCRIPTION
**Pull request by yingjieMiao**
@ymatsuda

### CODE REVIEW

**Comment by raymondng** [comment]
Please also modify the file in scraper service or this will be lost.

**Comment by yingjieMiao** [comment]
OK. I can wait until scraper migration is complete :)

**Comment by yingjieMiao** [comment]
@raymondng 

Now they are on the same page.

**Comment by raymondng** [comment]
Thanks @yingjieMiao!

**Pull request merged**
