### PR TITLE
suggested searches FE cleanup

### PR DESCRIPTION
**Pull request by stkem**
@2is10

### CODE REVIEW

**Comment by 2is10** [comment]
:+1: thanks

Do you know of any libraries that have suggested searches, so I can try this out for real?

**Comment by stkem** [comment]
https://www.kifi.com/stephen/mathematical-optimization
Is the only one I know of so far. I set that one up to test it.

**Comment by stkem** [comment]
oh, this one as well: https://www.kifi.com/df-tweney/dylan20

**Comment by 2is10** [comment]
Thanks!​

**Pull request merged**
