### PR TITLE
trying to fix a deadlock

### PR DESCRIPTION
**Pull request by ymatsuda**
@eishay @leogrim @yingjieMiao @andrewconner 

I found a possible cause of a deadlock.

BookmarkInterner may update NormalizedURIRepo first then BookmarkRepo while UriInterigyPlugin may update BookmarkRepo first then NormalizedURIRepo. To avoid a deadlock, we need to update the repos in the same order.

The code change moved BookmarkRepo update after NormalizedURIRepo update in UriInterigyPlugin.

### CODE REVIEW

**Comment by eishay** [comment]
lgtm, these deadlocks are killing me

**Comment by andrewconner** [comment]
Looks good

**Comment by yingjieMiao** [comment]
thanks!

**Comment by andrewconner** [comment]
Also, this may be the ultimate fix. The new importer rewrite won't likely change deadlocks, since it uses the same `readWriteBatch`.

**Pull request merged**
