### PR TITLE
Firefox/review feedback

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner Mozilla wants to see absolutely no `{{{value}}}`s in the template, so we'll skirt around that by passing our HTML strings into code that generates a JSON tree-structure. That structure will be passed into`kifi_mustache_tags.html`

Thoughts?

### CODE REVIEW

**Comment by andrewconner** [comment]
That is SO clever. A manual review may see what we're doing, but it's a solid attempt. (They didn't notice our `eval` hack right?)

**Comment by cvializ** [comment]
Heh I'm wondering what they'll think. I suppose on some level it is safer than just writing the raw string to the template. And we could argue that it's better since this template is the only place where we generate HTML. One of their problems with the `{{{ }}}`s was that they'd have to fully-re-review it every time to determine if it was still safely escaping everything.

That's right, but now our eval hack has been gone since merging #19081

**Comment by andrewconner** [comment]
Ah cool. Well looks good to me :+1:

**Comment by cvializ** [comment]
Thanks!

**Pull request merged**
