### PR TITLE
remove embedlyInfo class

### PR DESCRIPTION
**Pull request by yingjieMiao**
@martinraison @raymondng

### CODE REVIEW

**Comment by martinraison** [comment]
Cool - if we remove `EmbedlyInfo`, can we rename `ExtendedEmbedlyInfo` to just `EmbedlyInfo`? (not super-important)

**Comment by yingjieMiao** [comment]
that's the next thing.

**Comment by martinraison** [comment]
Awesome - looks good!

**Comment by raymondng** [comment]
Nice :+1:

**Pull request merged**
