### PR TITLE
removing uses of the raw string interpolater with multi-line strings, since it’s redundant

### PR DESCRIPTION
**Pull request by 2is10**
@42eng

### CODE REVIEW

**Comment by 2is10** [comment]
@andrewconner @eishay @martinraison @stkem Is this correct?

I looked multi-line strings up in the scala language reference and it’s clear to me that they do not respect simple backslash escapes like `\n` or `\t` or `\\`, just as raw interpolation does not. Are there any other differences I should know about (when used on a single line)?

**Comment by andrewconner** [comment]
Oh interesting, I didn't even know about `raw"xxx"`

**Comment by martinraison** [comment]
I'm wondering why multiline strings don't escape characters. The simplest way to get escaping in multiline strings seems to be to add the `s` prefix for string interpolation. Is there any benefit to the `raw` prefix other than being one-character shorter than switching the string to multiline mode?

**Comment by 2is10** [comment]
merging, but feel free to continue the discussion

**Comment by 2is10** [comment]
Martin has discovered and pointed out to me in pull request #8628 that removing `raw` prevents expression interpolation from occurring, of course. So it’s important to use `raw` or `s` when you need interpolation.

The triple quotes are redundant when using `raw` with a single-line string. Triple quotes are, of course, necessary for multi-line strings or to disable simple backslash escapes when _not_ using `raw` for interpolation.

Here’s a sequence of examples that illustrates how these work in combination:

```
scala> val name = "Jared"
name: String = Jared

scala> "Hi \\ $name"
res4: String = Hi \ $name

scala> """Hi \\ $name"""
res5: String = Hi \\ $name

scala> s"Hi \\ $name"
res6: String = Hi \ Jared

scala> raw"Hi \\ $name"
res7: String = Hi \\ Jared

scala> s"""Hi \\ $name"""
res8: String = Hi \ Jared

scala> raw"""Hi \\ $name"""
res9: String = Hi \\ Jared
```

**Comment by martinraison** [comment]
I was also confused because IntelliJ doesn't seem to recognize that `raw` disables backslash escapes (which is why I kept the triple quotation marks even when I was using `raw`).

Very useful examples - thanks Jared!

**Pull request merged**
