### PR TITLE
pushing non-linear scoring

### PR DESCRIPTION
**Pull request by ymatsuda**
@eishay @stkem 

Due to popular demand, pushing the non-linear scoring to production.

### CODE REVIEW

**Comment by eishay** [comment]
yey!
@stkem fyi we turned it on test accounts and the results did improve.

**Comment by stkem** [comment]
Great! Please add the change here: https://docs.google.com/a/kifi.com/spreadsheets/d/1KV6BYGEFsNJrLjqatRAIZ9GrAMtTEfIslF01STXbX4U/edit#gid=0

**Comment by ymatsuda** [comment]
I don't have the write access to that google doc.

**Comment by stkem** [comment]
Woops, sorry about that. You should have access now.

**Pull request merged**
