### PR TITLE
Update keeps by url on kifi site

### PR DESCRIPTION
**Pull request by gmethvin**
The /keeps/add endpoint is idempotent for the same url, so we can use that endpoint with the url in search results to update the state of existing keeps.

It may be useful to change the naming in the future to clarify this.

### CODE REVIEW

**Comment by 2is10** [comment]
cool

**Comment by 2is10** [comment]
We should also be able to easily move the server call out of the loop, to address the TODO, yes?

**Comment by 2is10** [comment]
Although, I think we decided we prefer referencing keeps by ID rather than by URL, when possible, to avoid the possibility of normalization issues.

**Comment by gmethvin** [comment]
I think we can allow BookmarkInterner to use a keep ID if it's there and update the existing keep. It would at least prevent us from creating multiple keeps as a result of normalization issues.

**Pull request merged**
