### PR TITLE
making loadUserPrefs go faster.

### PR DESCRIPTION
**Pull request by eishay**
most of the vals are already in memcached, so most likely we won't hit the db in any of the calls (or open sessions).
Hitting memcached will be done in parallel so it would be faster to return a value

@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Works for me :)

**Comment by 2is10** [comment]
Cool. Are we concerned about all the threads this will require?

It might be relevant to consider that the extension typically makes four HTTP requests for a user’s data in parallel at the beginning of a session or upon socket reconnect, this being one. The others are loading tags, friends, and keeper rules (not user-specific).

**Comment by eishay** [comment]
I'm not too concerned, its mostly IO blocking and its using the
"db-thread-pool-dispatcher" thread pool which is not that used.
Maybe we should consider merging some of these calls?

**Comment by 2is10** [comment]
By the way, this scenario sounds like a great use case for the “set and fetch by master key mode” (a way of optimizing memcached multigets) described in the “Part the next to last” section of [this post](http://dormando.livejournal.com/521163.html).

**Comment by eishay** [comment]
agree that we need multigets, I don't think that “set and fetch by master key mode” exist with the [MemcachedClient](http://dustin.sallings.org/java-memcached-client/apidocs/net/spy/memcached/MemcachedClient.html#gets%28java.lang.String%29) we use

**Comment by eishay** [comment]
closing for now, i'll push it after i'll integrate "bulk get on cache with Optional values" by @ymatsuda

**Pull request closed without merging**
