### PR TITLE
omit private libraries from grat email

### PR DESCRIPTION
**Pull request by camhashemi**
@andrewconner

### CODE REVIEW

**Comment by leogrim** [comment]
Do you think we should make the email less personal, especially not sent by a specific person, to reduce the creepiness potential? (feedback from Scott Ruffner)

**Comment by camhashemi** [comment]
I'm forwarding you the email thread about it.

**Comment by leogrim** [comment]
lol never mind, I didn't know he had actually written us this feedback :)

**Comment by andrewconner** [comment]
Looks good, thanks!

**Comment by camhashemi** [comment]
@andrewconner Closing this PR since it will be deprecated by the other one (keep views). I'm going to implement all the recent changes (minus owl images) on that one as well.

**Pull request closed without merging**
