### PR TITLE
Payback time! - Moves Database and all repos to Shoebox

### PR DESCRIPTION
**Pull request by leogrim**
@andrewconner @eishay

### CODE REVIEW

**Comment by gmethvin** [comment]
Looks good to me. Anything notable you changed besides moving stuff around? It's hard to tell from the diff.

**Comment by leogrim** [comment]
I have refactored many tests but there is no notable change in prod.

**Comment by eishay** [comment]
wohoooo! this is huge!
Fantastic !

**Comment by eishay** [comment]
Engines in place

**Pull request merged**
