### PR TITLE
Add url patterns for boosting and penalizing.

### PR DESCRIPTION
**Pull request by lawzlo**
@stkem @yingjieMiao @andrewconner 
Not a regex expert. Just verified several links per url regex through tool: http://regex101.com/#javascript

### CODE REVIEW

**Comment by yingjieMiao** [comment]
escape of `.` ? your tests pass because the char  `.` matches the pattern `.`

**Comment by lawzlo** [comment]
I thought if it doesn't need back slash for converting if we use """ in scala. But just verified, you are right. It needs converting. Adding back slash for all char need to convert.

**Comment by yingjieMiao** [comment]
lgtm

**Comment by stkem** [comment]
lgtm

**Comment by lawzlo** [comment]
tested, pushing to prod.

**Pull request merged**
