### PR TITLE
Adding the tag count as "numTags" on the profile stats

### PR DESCRIPTION
**Pull request by jaredpetker**
@andrewconner @eishay Unsure the best way to actually test this, it compiles, tests pass, but I don't think there are actual profile tests, I can look into adding them if desired.

### CODE REVIEW

**Comment by andrewconner** [comment]
So sorry for leaving this standing, I just noticed it was open and tagged me. Looks good, merging so you can use it.

**Comment by jaredpetker** [comment]
Cool beans, no worries.

**Comment by andrewconner** [comment]
Tests failed :). Hah, will fix and tag you. @jaredpetker

**Comment by jaredpetker** [comment]
Interesting, nothing failed at the time I thought, I can pull and run the
tests and see what happens.

**Pull request merged**
