### PR TITLE
don't call shoeboxclient with empty list

### PR DESCRIPTION
**Pull request by yingjieMiao**
@eishay

### CODE REVIEW

**Comment by eishay** [comment]
cool, thanks!

**Comment by 2is10** [comment]
I’d vote for putting this login in each service client class — a level lower than this. It’s let intrusive there and prevents the problem more broadly.

**Comment by eishay** [comment]
do you mean something like we have at
https://github.com/FortyTwoEng/keepit/pull/4926/files#diff-a6c6072acb038da71d6fe64cc6b136a0L265
@yingjieMiao would you pull in the lower level checks as well?

**Comment by yingjieMiao** [comment]
Sure. Maybe instead of using assume(), we could send airbrake errors?

**Comment by eishay** [comment]
sounds good

**Comment by 2is10** [comment]
​I meant transparently faking the RPC, since the client already knows the
answer. That way the callers don’t all have to check whether their ID lists
are empty before invoking client calls. It’s a kinder, more flexible API.

**Comment by eishay** [comment]
In some cases there's a valid reason for sending requests with empty list since they may have an additional side effects. I would rather have the runtime brake if the high level is doing something wrong then covering up smartly.
If the engineer didn't think of some case they may have few other cases unrelated to the rpc that was missing as well and we may rather fix the cause of the empty list being sent.

**Comment by 2is10** [comment]
I think side effects for simple "get" requests are rare, and we could
certainly _not_ fake the request for any specific endpoints that have side
effects, but I do understand your concerns, and it’s your call.

**Pull request merged**
