### PR TITLE
Add correct loadReason functionality. Add update tooltip

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Slick. This fires just when the backend tells it there's an update?

**Comment by cvializ** [comment]
I think so: there's a socket handler called `version` that calls `api.requestUpdateCheck`, so if the backend tells it there's an update by emitting `version`, yes

**Comment by andrewconner** [comment]
Ah cool, alright.

**Comment by cvializ** [comment]
also: you can test this functionality by opening the background page's console and entering `api.requestUpdateCheck(true)`

**Pull request merged**
