### PR TITLE
if timing out when trying to get uri resources (i.e. images) then just i...

### PR DESCRIPTION
**Pull request by eishay**
...gnore value and not try again until cache expires
@stkem

### CODE REVIEW

**Comment by stkem** [comment]
Actually, the second request often (not always) succeeds because embedly now knows about the uri and responds a lot quicker. This way we won't try again for 30 days. Just making sure that that is intended.

**Comment by eishay** [comment]
2 minutes ttl is very long, and  in cases of repeating timeouts for the same url its a churn on the system. How about reducing that cache to one or two days?

**Comment by stkem** [comment]
That could increase total load significantly (even if reducing timeouts). An alternative could be to set `waiting` to false in the request here (causing it to return immediately if there is nothing and fetch it in the background) and _not_ cache empty responses.

**Comment by eishay** [comment]
Good idea, I'm going to hold on this pull request for now as we're trying
alternative options.

**Pull request closed without merging**
