### PR TITLE
switchable topic model

### PR DESCRIPTION
**Pull request by yingjieMiao**
DO NOT MERGE.

still need to do some manual work in sql on b01.

### CODE REVIEW

**Comment by yingjieMiao** [comment]
@ymatsuda

**Comment by ymatsuda** [comment]
Looks like we apply all operations to the "current" repos only. Don't we have situations that we need to work with the "other" repos?

**Comment by yingjieMiao** [comment]
Just added a remodel function. we now select the 'right' repos.

**Comment by ymatsuda** [comment]
Look good!

**Pull request merged**
