### PR TITLE
We 202 you, no matter your life choices.

### PR DESCRIPTION
**Pull request by andrewconner**

### CODE REVIEW

**Comment by andrewconner** [comment]
@leogrim

**Comment by 2is10** [comment]
This is great but as I examine the extension code, I have to withdraw my earlier assessment. This upload happens only after `/kifi/start` succeeds. Only `/kifi/start` has a retry possibility, not this `/bookmarks/add` upload.

**Comment by 2is10** [comment]
The use of an `api.tabs.on.loading` event handler to retry starting the session after a failure is now my top suspect. It’s not immediately clear to me how to reproduce it.

**Comment by 2is10** [comment]
Oh, not being logged in.

**Pull request merged**
