### PR TITLE
Increase max size, lots of logging

### PR DESCRIPTION
**Pull request by andrewconner**
User is trying to upload 26,000 bookmarks from Delicious. Would love some help manning the servers when he tries again, but he's someone we want to be happy.

Two changes: lots of logging so we can see what's breaking and how long it's taking, and increasing max size to 12MB. Based on Eishay's export of 420 bookmarks, that should be enough for him.

### CODE REVIEW

**Comment by andrewconner** [comment]
@eishay @stkem Please review. Merging so we can test it again.

**Comment by eishay** [comment]
see `ClientResponse` 

``` scala
      case e: Throwable =>
        log.error(s"bad res: $body")
        //The file name is constant, don't change it. We don't want repeating bad jsons to fill up our disk. As a result we store to disk only the latest bad json.
        //Yes, this is not thread safe, but we can live with it.
        val file: File = new File("bad-json.json")
        val output = new FileOutputStream(file)
        try {
          IOUtils.write(bytes, output)
        } finally {
          Try(output.close())
        }
        throw new ClientResponseException(s"can't parse json on request ${request.httpUri} with charset [$charset], orig type is ${ahcResponse.getContentType} bytes are written to ${file.getAbsolutePath()}: $body ", e)
```

**Comment by eishay** [comment]
well, not json in this case but i'm sure you got it :-)

**Comment by eishay** [comment]
maybe with random filename with user id in it and spit it into log?

**Comment by eishay** [comment]
btw, that's fantastic!!!!!

**Pull request merged**
