### PR TITLE
Absolute URLs in attribution bar

### PR DESCRIPTION
**Pull request by andrewconner**
@eishay @yipingliao

### CODE REVIEW

**Comment by yipingliao** [comment]
:+1:

**Comment by eishay** [comment]
great!
how about tag searches?
`<a ng-href="/find?q=tag:OpenWrt" ng-click="onTagClick()" class="ng-binding" href="/find?q=tag:OpenWrt">OpenWrt</a>`

**Comment by eishay** [comment]
that actually has not `href`, only `ng-href`

**Comment by eishay** [comment]
can we add the `href` there?
in any rate, lets push this change asap to prod and reindex

**Comment by andrewconner** [comment]
Added tags links, switched to using `href` instead of `ng-href`. This _shouldn't_ make a difference, but you never know. A slight risk is if Google tries to crawl/index the raw unparsed string before it gets replaced. Unlikely, but something to watch for. If we see tons of broken links after this, that's why.

**Pull request merged**
