### PR TITLE
add evolutions for org/orgmembership sequence

### PR DESCRIPTION
**Pull request by camhashemi**
@leogrim @ryanpbrewster

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
:+1:

**Comment by leogrim** [comment]
:+1:

**Comment by camhashemi** [comment]
remembered last minute to use BIGINT(20) for ids and sequence numbers.

**Comment by leogrim** [comment]
And I missed it :)

**Comment by yingjieMiao** [comment]
it doesn't really matter though. it only affects display, not storage.

**Comment by camhashemi** [comment]
are evolutions just for record-keeping of the manual SQL queries?

**Comment by leogrim** [comment]
And they're applied in some tests (those that use an application)

**Pull request merged**
