### PR TITLE
typeahead -- dedup email addresses

### PR DESCRIPTION
**Pull request by raymondng**
This should do it

@andrewconner @leogrim

### CODE REVIEW

**Comment by 2is10** [comment]
thanks

**Comment by leogrim** [comment]
I think this doesn't account for potential case differences in email addresses and doesn't guarantee that we pick the duplicate address with the highest score. The original code did, see https://github.com/kifi/keepit/commit/dc6102371c7d3cc5aae6158484072c4cafb21c68

**Comment by raymondng** [comment]
Thanks. Will take care of it.

Didn't know that we now persist in varying cases. I distinctly remember
that we made an earlier decision to persist uniformly (via toLower). There
are different trade-offs ... I'll catch up with you when you come back.

**Comment by andrewconner** [comment]
Feel free to merge when you're happy — wasn't sure if @leogrim's comment needed new code?

**Comment by raymondng** [comment]
Thanks. Yes new code (or porting old code) will be required. I might merge
this first and handle it later.

**Comment by leogrim** [comment]
@raymondng about case, @2is10 and I then decided that it was best to keep user's data intact, even though we should always manipulate email addresses in a case insensitive fashion, like the database does.

**Comment by raymondng** [comment]
Thanks for the feedback. Will merge & iterate.

**Pull request merged**
