### PR TITLE
Support library search filter in the new website import

### PR DESCRIPTION
**Pull request by leogrim**
@2is10 
Note that I have changed the filter "f" parameter to "u". The reasoning is that our current filter is just about filtering by user, and searching within a library is actually about filtering by library. So this is an attempt to have a more symmetric API where it's just "u"sers and "l"ibrary. I'd like to move towards this more consistently.

### CODE REVIEW

**Comment by 2is10** [comment]
Okay, sounds good to me.

What would it take for “My Main Library” and “My Private Library” to show up in results? I could implement it in the browser, but I wouldn’t have a good idea of where they should be ranked among other matching libraries.

**Comment by leogrim** [comment]
We have not been indexing the names of system libraries in order to reduce noise in keep search. But now that search is becoming navigational for libraries and people I think we should. It's an easy change on the backend, we'll just have to reindex libraries.

**Comment by leogrim** [comment]
I've made the change.

**Comment by 2is10** [comment]
> I've made the change.

Wow, that was fast. Thanks. Will they begin showing up on google.com now too? I’m not sure that’s desirable.

**Comment by 2is10** [comment]
To answer my own question, I imagine this won’t affect how we do attribution for keeps.

**Comment by leogrim** [comment]
Nope it won't.

**Comment by leogrim** [comment]
Also, the user filter 'u' now accepts a user's external id in addition to the regular parameters for all, friends and mine. Results are then restricted to that user's keeps from libraries you have access to (for that reason it won't include results from main, a technical limitation in the current implementation, I only spent a few hours on this). This means we could have a search bar on user profile pages, very much like we do on library pages. :)

**Pull request merged**
