### PR TITLE
fix filter corruption

### PR DESCRIPTION
**Pull request by ymatsuda**

### CODE REVIEW

**Comment by ymatsuda** [comment]
@leogrim , @stkem , please review the change.

**Comment by stkem** [comment]
looks good overall. Maybe make `prefix` an option, so the code can be used in places where you don't want a prefix?

**Comment by leogrim** [comment]
Agree, and the BlobFormat may want to use it with None. As it is we're going to store the data in S3 with a 1 prefix

**Comment by ymatsuda** [comment]
If you want to remove the prefix, you can override public methods. I think that is cleaner.

**Pull request merged**
