### PR TITLE
SimpleGraph Implementation with Evil Black Magic API

### PR DESCRIPTION
**Pull request by leogrim**

### CODE REVIEW

**Comment by leogrim** [comment]
@stkem 
Made it work with type parameters.

**Comment by yingjieMiao** [comment]
Looks fancy. Maybe you could write a blog post about it ;-)

**Comment by leogrim** [comment]
I thought about it, but first I need to understand what I wrote.

**Comment by leogrim** [comment]
@stkem Cf. my last commit with changes discussed on Monday + some consequences. Not sure about that last one about VertexDataId, thoughts?

**Comment by leogrim** [comment]
@stkem 
I have added a SimpleGraph in-memory implementation.

**Pull request merged**
