### PR TITLE
Fix modal position after focus

### PR DESCRIPTION
**Pull request by cvializ**
Resolves https://app.asana.com/0/42816489233171/46149815816769.

@adamjgrant @andrewconner Not sure if this is the best way to fix it, but it works without changing too much

### CODE REVIEW

**Comment by andrewconner** [comment]
Oh that's weird.

**Comment by cvializ** [comment]
Too weird, or "okay weird"?

**Comment by andrewconner** [comment]
It's weird it's needed. Is it animating in or something?

**Comment by cvializ** [comment]
It sets a flag to be true, and then uses an `ng-show="flag"`, and I think when the focus calls in the middle of that, it scrolls the page which causes the problem. I think

**Comment by andrewconner** [comment]
Ah

**Comment by cvializ** [comment]
I think you'll feel somewhat better about it now

**Pull request merged**
