### PR TITLE
rolling out new "html-plain" welcome email

### PR DESCRIPTION
**Pull request by camhashemi**
@stkem Sterling gave the thumbs-up this morning

@eishay if eishay.smith@kifi.com is truly a dummy email (no sensitive info), feel free to send me the credentials or forward me the replies so that I can take care of any potential issues.

### CODE REVIEW

**Comment by andrewconner** [comment]
We have a mechanic for tracking differences between this email and the previous one?

**Comment by camhashemi** [comment]
each link has a tracking parameter (on this and the previous), so we can monitor the clickthrough rates as of 5/14/15 and compare it to the previous one.

**Comment by stkem** [comment]
Yes, although somewhat manual. It's basically a sequential A/B test. We have a bunch of data for the old email and we'll see how this one compares (open rate, click through, spam reports, ...)

**Comment by stkem** [comment]
Oh Concurrency :-)

**Comment by camhashemi** [comment]
@stkem @andrewconner I haven't tested that these clickthroughs are being saved, but I'm working with the framework that's already in place. let me know if I should work on that or merge.

**Comment by stkem** [comment]
Go ahead and merge. At the very least we'll have the clickthroughs in the Sendgrid (our backend email provider) dashboard.

**Pull request merged**
