### PR TITLE
don't deep link from external message links

### PR DESCRIPTION
**Pull request by camhashemi**
@andrewconner @eishay it's a bit more fragile than I would like, but I don't think we differentiate between discussion emails to users and non users any other way.

### CODE REVIEW

**Comment by andrewconner** [comment]
I thought we decided that emails to non-users (messages directly to email addresses, not Kifi users) will link directly to the correct page? ie, no `DeepLinkRouter`.

And why is the auth token sent?

**Comment by camhashemi** [comment]
This implements that behavior, auth tokens are sent with external message email deep links. I think you're getting at altering the template to not insert deep links at all, that's fine too. I'll do that.

**Comment by camhashemi** [comment]
@andrewconner updated the template to omit deep links for non-users, also leaves the door open if we want to be more nuanced in the future (i.e. redirect to the keep page on certain elements)

**Comment by andrewconner** [comment]
Thanks!

**Pull request merged**
