### PR TITLE
add link to user profile in the "user connected" emails

### PR DESCRIPTION
**Pull request by eishay**

### CODE REVIEW

**Comment by eishay** [comment]
@joshm1

**Comment by 2is10** [comment]
Cool, thanks. Can we linkify the user’s picture too?

**Comment by eishay** [comment]
good idea, sure

**Comment by eishay** [comment]
@2is10 update, thanks

**Comment by 2is10** [comment]
:smile:

**Comment by joshm1** [comment]
:+1:

**Pull request merged**
