### PR TITLE
don't shuffle hand picked with others

### PR DESCRIPTION
**Pull request by yingjieMiao**
@stkem

### CODE REVIEW

**Comment by stkem** [comment]
Nice, thanks!

**Comment by stkem** [comment]
lgtm

**Comment by yingjieMiao** [comment]
FYI, I didn't tune up from 5 to 10 libraries. That will affect overall user experience. I would prefer incremental changes here.

**Comment by stkem** [comment]
This does not appear to work correctly. The libraries are in there, but they are not at the top. Please investigate.
Also, with 2 libraries per persona, we'll need to increase the lib count to 10 to have good coverage.

**Pull request merged**
