### PR TITLE
Site and ext Facebook API update. Super simple.

### PR DESCRIPTION
**Pull request by andrewconner**
@2is10 Tested locally, this seems to be it for the clients.

### CODE REVIEW

**Comment by andrewconner** [comment]
Fortunately we don't use any parts of the API that changed client side anymore (we used to for login pages, but it's not used now).

**Comment by andrewconner** [comment]
Facebook is actually leaving the old script up for now, looks like, so I don't think we're rushed to get this out for the extension.

**Comment by 2is10** [comment]
> Fortunately we don't use any parts of the API that changed client side anymore (we used to for login pages, but it's not used now).

Are you referring to the bit that shows the Facebook picture if the user is logged in to Facebook and has authed previously? The extension still does that. I thought it was removed from the site in haste for the redesign. I was hoping we’d put it back there too.

**Comment by andrewconner** [comment]
I misspoke, we used more for the angular signup, but now it just redirects directly to /signup/facebook. The picture when user is logged in works still. In extension dev mode:

**Comment by 2is10** [comment]
Oh, I just merged this and tested it locally myself. It seems that, in the extension, it still works. But will it stop working for new users when FB starts giving us fake user IDs? Or will their graph API accept those fake user IDs?
https://graph.facebook.com/FAKE-USER-ID/picture?width=50&height=50

**Pull request merged**
