### PR TITLE
Org non-member/non-user ui

### PR DESCRIPTION
**Pull request by camhashemi**
@adamjgrant @cvializ @andrewconner 

the backend now passes invitation information for non-members viewing an org, this PR displays that info in the signup CTAs.

### CODE REVIEW

**Comment by camhashemi** [comment]
screen shot 2015-08-18 at 11 41 15 am

**Comment by camhashemi** [comment]
once the org experiment is killed, non-members will be able to see public libraries and members

screen shot 2015-08-18 at 11 41 30 am

**Comment by cvializ** [comment]
For the banner design, you'll want to put some space above it. It looks a little bit strange when it's flush with the header above.

**Comment by cvializ** [comment]
Besides that :+1:

**Comment by adamjgrant** [comment]
What @cvializ said :+1:

**Comment by camhashemi** [comment]
@cvializ @adamjgrant  updated. please see commit messages.

**Comment by cvializ** [comment]
:+1: nice and clean

**Comment by adamjgrant** [comment]
:+1:

**Pull request merged**
