### PR TITLE
Added an endpoint for uploading an org avatar

### PR DESCRIPTION
**Pull request by ryanpbrewster**
Also removed a deprecated use of Play implicit execution context

@leogrim @camhashemi @cvializ @ajkochanowicz

### CODE REVIEW

**Comment by adamjgrant** [comment]
Glorious!

**Comment by cvializ** [comment]
Beautimous. @ryanpbrewster, does this take the same arguments as the user profile image upload?

**Comment by ryanpbrewster** [comment]
@cvializ, I don't think either of those take any arguments (I may be wrong). It needs a request body that is a temporary file, and it returns a `{"uploaded": <path_to_image>}`.

**Comment by cvializ** [comment]
Ok! I'm going to try to reuse the userProfile upload dialogs, so as long as the org and user avatar uploads expect the same request structure we're good to go

**Comment by andrewconner** [comment]
Yeah if my memory serves right, should be the same. You ajax up a binary image, and get back a URL. You're responsible for error handling and some pleasant transition so the user knows that the upload is happening. Errors vary and probably will give you more details than you care; you can probably just simplify and say an error has occurred and they can retry or contact support.

**Comment by cvializ** [comment]
@ryanpbrewster if this is good to merge I'm ready for it :+1:

**Pull request merged**
