### PR TITLE
adding back .jpg extension in user search results (reverts 16153d5)

### PR DESCRIPTION
**Pull request by 2is10**
@andrewconner 
cc @joshm1

### CODE REVIEW

**Comment by 2is10** [comment]
@andrewconner, I don’t see a cache that uses this value.

**Comment by andrewconner** [comment]
Ah I see, yeah it's not using BasicUser. Carry on.

**Comment by 2is10** [comment]
FYI, Yingie is going to fix the 0.jpg.jpg URLs still showing up in the results. It’s happening because we’re storing full BasicUser JSON in a Kifi user lucene index. He’s going to rebuild the index.

**Comment by 2is10** [comment]
Just confirmed Yingie’s fix.

**Pull request merged**
