### PR TITLE
More resilient Zookeepering

### PR DESCRIPTION
**Pull request by stkem**
We already have a recovery mechanism for connection loss, but it had some weaknesses, perhaps most notably that it was async and not always called when there was a problem. This should help.

Also removed two unnecessary airbrakes which were responsible for some of the recent pagerduties.

No really all that much closer to understanding why this only recently started acting up, but this should (hopefully) reduce the problems.

This should be deployed carefully (i.e. probably in the morning)

@andrewconner @leogrim

### CODE REVIEW

**Comment by andrewconner** [comment]
Looks good to me. Hope we also find out what's going on network wise. Has it happened recently, or is it basically randomly continuous? Would love to see the topology and a ping from machines during the issues.

**Comment by stkem** [comment]
Still going to look at the topology if I catch it on time (whoever is on call should probably try as well), but baed on the exceptions and what I've seen in the ZK logs, the view of the world of the affected machines is almost certainly just frozen from what it was before the most recent deploy (of anything).

**Comment by leogrim** [comment]
I have tried looking up the topology when Rover is acting up, but I didn't catch anything interesting so far

**Comment by andrewconner** [comment]
> almost certainly just frozen from what it was before the most recent deploy

Oddly, I once bounced rover and it didn't fix. Then I deployed (new version) and it fixed. May be a red herring, but...

**Comment by stkem** [comment]
Yeah, the underlying issues seem to be something with the network, where it can't connect to ZK (hence the frozen state). This PR should help the process recover on it's own without needing a bounce/deploy (iff the network recovers). I think :-).

**Pull request merged**
