### PR TITLE
making the stats numbers a bit more explicit

### PR DESCRIPTION
**Pull request by eishay**
/cc @andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Works for me. Thanks. By the way, I moved the futures around in this controller. A for comprehension gets rewritten as a series of `flatMap`s, so unless you start the futures on the outside, it runs serially.

**Comment by eishay** [comment]
I didn't know that, its a big point. Think we have more of those in the codebase? Mind you doing a future comprehension discussion, tips, tricks and best practices in the next week's tech talk? Its a good follow up on what Yasu's talk about immediate context.

**Comment by andrewconner** [comment]
I'm happy to, but it's pretty quick. Basically,

```
for {
   v <- vF
   w <- wF
} yield (v,w)
```

is the same as:
`vF.flatMap(v => wf.map(w => (v,w)) )`

So, 

```
for {
   v <- future { vF() }
   w <- future { wF() }
} yield (v,w)
```

means that `wF()` isn't called until `vF()` finishes. We may have more, but I haven't noticed them.

**Comment by eishay** [comment]
and you say that this is actually really concurrent, right?

``` scala
val fv = future { vF() }
val fw = future { wF() }
for {
  v <- fv
  w <- fw
} yield (v, w)
```

**Comment by andrewconner** [comment]
Yep.

**Comment by eishay** [comment]
Good, I think I saw it in at least one other place.

**Pull request merged**
