### PR TITLE
Creating traits for LibraryCommander and LibraryInviteCommander

### PR DESCRIPTION
**Pull request by andrewconner**
@yingjieMiao @stkem @leogrim @eishay

You wouldn't believe how much faster this makes compilation.

Traits for large classes are great:
1. They serve as a table of contents for a large classes and form a contract for method signatures.
2. Aid in refactoring. Easy to know what my contracts are if I'm locked into a trait.
3. Speeds up compilation, since signatures are locked and the class constructor doesn't change based on dependency injection changes (one of the downsides of Guice).
4. Make it easier to encapsulate public vs private methods.

If everyone agrees, I will be converting our existing commanders to this pattern over time. If anyone wants to help, this makes it a pretty easy process (leaving cleaning up for later):

``` scala
def genTrait(filename: String) = {
  import scala.io.Source
  val name = filename.drop(filename.lastIndexOf('/')+1).dropRight(6)
  val lines = Source.fromFile(filename).getLines().dropWhile(!_.contains(s"class $name"))
  val methods = lines.filter(_.indexOf("  def ") == 0).map(_.reverse.dropWhile(c => c != '=').drop(1).reverse).mkString("\n")
  val t = s"""
@ImplementedBy(classOf[${name}Impl])
trait $name {
  // todo: For each method here, remove if no one's calling it externally, and set as private in the implementation
$methods
}
  """
  println(t)
}
```

### CODE REVIEW

**Comment by andrewconner** [comment]
Starting project for Max? Boring, but...

**Comment by yingjieMiao** [comment]
:+1:

**Comment by yingjieMiao** [comment]
even after refactoring, the table of content is too big for my taste, which can be subjective.

**Comment by andrewconner** [comment]
Yep, it is. And it's easy to see, and perhaps refactor.

**Pull request merged**
