### PR TITLE
new libraries feed

### PR DESCRIPTION
**Pull request by raymondng**
Factored out common logic to `FeedCommander`
Moved endpoint to `FeedController`
DRY-er implementation in general
Simple test added for new feed
More work to do (kcid, auto-ping google pubsubhub, etc.)

@eishay @andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Great thanks

**Comment by eishay** [comment]
Could not find in the code, are we having some quality measures like not showing libraries with less then three keeps?

**Comment by raymondng** [comment]
No not yet. For the new feed, I thought this is not necessary -- but it'd be trivial to add. Let me know.

**Comment by raymondng** [comment]
As discussed, we'll do filtering on the `top` feed.

**Comment by raymondng** [comment]
Merging to build on it. Thanks for the feedback!

**Pull request merged**
