### PR TITLE
Reintroducing dev mode improvements

### PR DESCRIPTION
**Pull request by andrewconner**
Tests pass locally.

### CODE REVIEW

**Comment by eishay** [comment]
interesting commit messages

**Comment by andrewconner** [comment]
I was fighting with git, reverting my revert.

**Comment by stkem** [comment]
looks ok as best as I can tell. I assume you ran the tests?

**Comment by andrewconner** [comment]
For future 42ers, more information here: https://github.com/kifi/keepit/pull/9423

**Pull request merged**
