### PR TITLE
rendering library keeps nicely, one at a time

### PR DESCRIPTION
**Pull request by 2is10**
@andrewconner 

I helped Yiping do this for search results a while back. I think it really helps with perceived page load time. I’m doing it now because it also fixes a UI glitch I’ve encountered while working on the new search suggestions feature.

### CODE REVIEW

**Comment by andrewconner** [comment]
Cool. It's a speed thing?

**Comment by eishay** [comment]
nice

**Comment by 2is10** [comment]
> Cool. It's a speed thing?

The blocking DOM manipulations done to compute the optimal layout for each keep card really add up. For 10 keeps, it takes about 1 second on my MacBook Pro. This can freeze other things going on in the page, sometimes very noticeably. I was seeing the search bar background-color transition pause halfway between dark and light, for example. I disabled that transition during page navigations, but then still saw the bar staying light for 1½ sec longer than it should have. This change avoids those issues.

**Comment by andrewconner** [comment]
Oh interesting, I never saw it that slowly. I'm looking forward to the more simple, static designs coming down the pipeline.

**Comment by 2is10** [comment]
Me too.

I think one reason we don’t often see it that slow is because I was specifically testing navigating back and forth between two libraries, which becomes much easier to do with the new empty search box suggestions. In this case, I think we have been synchronously rendering 20 or 30 keeps instead of just the initial 10, since prefetching was done using `.$evalAsync` (which runs before rendering) and because `Clutch` invokes callbacks synchronously when data is cached. I’m going on my memory of the code here and so could be wrong, but this explanation would be consistent with the behavior I was observing.

**Pull request merged**
