### PR TITLE
Serialize org handles in a more expected way.

### PR DESCRIPTION
**Pull request by ryanpbrewster**
@eishay

### CODE REVIEW

**Comment by andrewconner** [comment]
I don't think this is a good idea. It means we'll get more and more uses of implicit `.toString` being called on this object. It's a mistake for `Id` and `ExternalId` to do it, and too difficult now to fix. @leogrim @ryanpbrewster

**Comment by ryanpbrewster** [comment]
I agree. The question is, is it better to have bad emails or bad practices?

**Comment by ryanpbrewster** [comment]
Can we redefine `OrganizationHandle.toString` to throw an exception?

**Comment by andrewconner** [comment]
> is it better to have bad emails or bad practices?

Neither. If the toString is never overridden to just happen to work, it's a bug as soon as it's coded. Verses a hidden bug, waiting on someone changing or removing the toString

**Pull request merged**
