### PR TITLE
use LibraryCardInfo for LibraryController.getKeepableLibraries

### PR DESCRIPTION
**Pull request by camhashemi**
@ryanpbrewster @andrewconner @leogrim 

this allows us to return org-keepable libraries to the site without breaking things (keeping the same objects as used elsewhere). this endpoint isn't being used anywhere, going to deploy this then dev-mode QA the front-end.

### CODE REVIEW

**Comment by andrewconner** [comment]
Seems reasonable, only concern would be backwards compatibility, so if it's not being used, merge away :)

**Comment by camhashemi** [comment]
speaking of, talked with mobile about the old libraries endpoint `/m/1/libraries/` and they say it's not being used in the current build. A lot of the complexity in libraries is backwards compatibility for those clients, would love a process to clean up a bit here and there. 

Could we use your endpoint tracking used for killing routes to see which of these library endpoints we can kill, and the code with it?

**Comment by camhashemi** [comment]
my only concern is that maybe we don't want to return ALL keepable libraries wherever `libraryService.fetchLibraryInfos` is called on the frontend, but looking at the usage it seems like that's mostly accurate.

**Comment by andrewconner** [comment]
Sure, I'll do it next

**Pull request merged**
