### PR TITLE
Futuristic stuff

### PR DESCRIPTION
**Pull request by leogrim**
@andrewconner @stkem @eishay 
As it was, sequentialExec had a memory leak (recursive flatMaps...). I believe this new "fold" helper doesn't - basically it's asynchronous tail recursion - and sequentialExec is just a special case of it :)

### CODE REVIEW

**Comment by leogrim** [comment]
The more I think about this, the less I'm sure of it. Please twist carefully :)

**Comment by leogrim** [comment]
I'll merge this since I know the result is correct and I need it to wrap up with the ABook data migration - I just have a doubt whether I have solved the memory leak or not :)

**Comment by raymondng** [comment]
Thanks Leo. Can you elaborate on the following:

1) What is the nature of the memory leak with the original implementation?
2) How is the new implementation materially different from the old one (from a memory leak angle)?

As the recursive calls are async, there's no stack-safety issue traditionally associated with recursion.

FWIW I actually don't see memory leak issue with old _or_ new impl -- but that also means that (as you suggested) if there's a leak it's likely still there :) 

BTW if you still feel that there's a leak, we can likely test & catch it easily.

**Comment by leogrim** [comment]
I guess @andrewconner has been answering :)
Long story short, the memory leak comes from the Promise objects created by chained flatMaps. These Promises behave exactly like a call stack, each one relying on its predecessor for completion. My implementation relies on a single initial Promise that is passed down explicitly to the next asynchronous call, until it's resolved by the last one.

**Comment by raymondng** [comment]
Yes thanks @andrewconner and @leogrim for the explanations.
I was aware of the scala bug but I thought it's already fixed (well it apparently is fixed but we haven't picked it up yet ... so yes it's an issue for us :>) So ... look forward to it!

**Pull request merged**
