### PR TITLE
consolidating PageDetails code

### PR DESCRIPTION
**Pull request by 2is10**
ok @andrewconner?

### CODE REVIEW

**Comment by gmethvin** [comment]
lgtm

**Comment by andrewconner** [comment]
Great. Since we've been forward compatible for several versions, this should work with older extensions. Merge whenever you want it in :)

**Comment by 2is10** [comment]
Yeah, it’s been 9 days, so I figure it’s alright now. If people have
problems we can tell them to manually update.​

**Comment by stkem** [comment]
like

**Pull request merged**
