### PR TITLE
more frequent orphan cleaning

### PR DESCRIPTION
**Pull request by ymatsuda**
self-merging

### CODE REVIEW

**Comment by raymondng** [comment]
Based on logs there appears to be a lot of db activities triggered by OrphanCleaner -- may dial this back and observe for a bit.

**Comment by ymatsuda** [comment]
Why? The more frequent, the less work at a time. If there are task invocations with no actual work, it makes sense to run less frequently. Otherwise, it may increase occasional spikes.

**Comment by yingjieMiao** [comment]
Léo and I have found a bug in recent normalization code. Lots of "looping" normalization happened since May 30. e.g. one uri was redirected more than 2000 times. We are still trying to figure out the cause. 

So probably nothing wrong with orphan cleaner.

**Comment by yingjieMiao** [comment]
we have identified the problem. coming with commits.

**Comment by raymondng** [comment]
Great. I found a few issues as well. Please see pull request. Let's sync-up.

**Pull request merged**
