### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by eishay**

### CODE REVIEW

**Comment by andrewconner** [comment]
Awesome, pretty cool. Can't wait to play with this.

**Comment by eishay** [comment]
pushing it now, you'll have to add youself as an admin, the next thing i'll
to is to block it as well so only admin can add admin

**Comment by eishay** [comment]
i see you already did :-)

**Comment by andrewconner** [comment]
Yep I added everyone from FortyTwo to it. Feel free to lock it down now.

**Pull request merged**
