### PR TITLE
[do not merge] Play 2.2

### PR DESCRIPTION
**Pull request by andrewconner**
Only semi-stable, tests do not pass, needs cleaning up. Opened for review.

I'm trying to get this done ASAP, because a lot changes (101 files so far) and it'll be a really bad merge conflict otherwise.

### CODE REVIEW

**Comment by andrewconner** [comment]
Closing, continuing work on parent/play22. https://github.com/FortyTwoEng/keepit/tree/play22

Infrastructure people: @eishay @leogrim @stkem @raymondng

**Comment by raymondng** [comment]
Thanks for the heads-up! Tech talk maybe?

**Comment by eishay** [comment]
great!
i see you moved it to https://github.com/FortyTwoEng/keepit/tree/play22 right?

**Comment by andrewconner** [comment]
Yeah. Stephen said he'd help. I figured out the configuration issue (I think :)) and am on other stuff right now. We are probably not very far from something we can put on the canary instance.

**Comment by raymondng** [comment]
Excellent use of test instance :)

**Pull request closed without merging**
