### PR TITLE
Remove ncid (Net Caller ID) from query parameters

### PR DESCRIPTION
**Pull request by leogrim**
@raymondng @ymatsuda 
@yingjieMiao we need a renormalization

### CODE REVIEW

**Comment by ymatsuda** [comment]
thanks!

**Comment by raymondng** [comment]
Nice :+1: -- so the "duplicate" keeps I had will be renormalized to the same one?

**Comment by leogrim** [comment]
Yep!

2014-05-28 14:56 GMT-07:00 Raymond Ng notifications@github.com:

**Comment by raymondng** [comment]
Cool. Mystery revealed -- Net Caller ID :)

**Comment by leogrim** [comment]
Fixing the data will require a renormalization. Yingjie is currently
working on a new endpoint to make this possible by regex.

2014-05-28 15:16 GMT-07:00 Raymond Ng notifications@github.com:

> Cool. Mystery revealed -- Net Caller ID :)
>

**Pull request merged**
