### PR TITLE
[ext-msg] uri image architecture (part 1)

### PR DESCRIPTION
**Pull request by martinraison**
@stkem @andrewconner 
This contains the following components (I'll probably continue to modify them): 
- URIImageRepo (& URIImage) (for keeping track of the images we have)
- EmbedlyClient,
- PagePeekerClient
- S3URIImageStore (for storing data on S3)

The two main parts I have yet to write are the URIImageCommander and URIImageController
After this works I'll try to modify S3ScreenshotStore to use the new code

### CODE REVIEW

**Comment by andrewconner** [comment]
Awesome. As a head's up, we need to make sure we can't break existing API endpoints. I'll overview what's there and we can make sure we have a clear migration path.

**Comment by martinraison** [comment]
Sure - right now the old code is still there so the behavior shouldn't change. We need to be careful when modifying S3ScreenshotStore.

**Comment by martinraison** [comment]
Added the commander (+controllers) to the mix - not merging yet, I'd like to test it a little bit and figure out what is missing

**Comment by martinraison** [comment]
Added tests. FYI I just found about this way of dealing with futures in tests: https://groups.google.com/forum/#!topic/specs2-users/HkPJqH83I5Y (OP is James Roper, funny coincidence)
This allowed me to drop TestKitScope and to resolve the weird potentially-concurrency-related bugs I had this afternoon.
@leogrim

**Comment by leogrim** [comment]
Good find! That's awesome! 
I'll refactor a few tests I wrote and use this.

**Comment by yingjieMiao** [comment]
nice!

**Comment by raymondng** [comment]
Good stuff :+1:

**Pull request merged**
