### PR TITLE
Remove support for including org participants in discussions

### PR DESCRIPTION
**Pull request by ryanpbrewster**
@leogrim @andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Cool, what does this change?

**Comment by ryanpbrewster** [comment]
If this is merged, we will no longer accept org ids in the set of user participants (when first starting a discussion or adding participants).

Current behavior: add "ozusIbCoQ9Od" --> all members of Brewstercorp added to discussion
Behavior once merged: add "ozusIbCoQ9Od" --> BadRequest

**Comment by andrewconner** [comment]
Ah cool. Are we still adding them to old typeaheads?

**Comment by ryanpbrewster** [comment]
Not sure about old typeaheads. Neither the current extension nor the current android app have orgs in the typeaheads.

**Comment by andrewconner** [comment]
We swapped the endpoint, so need to make sure older clients don't break. I'll check.

**Comment by andrewconner** [comment]
Yep they still do. Give me a sec and I'll remove them.

**Comment by andrewconner** [comment]
#21370

**Pull request merged**
