### PR TITLE
index keywords in the url

### PR DESCRIPTION
**Pull request by gmethvin**
@ymatsuda 

This lets us search domain names by splitting the domain into keywords and searching a field, "site_keywords" in Lucene. We use the siteBoost parameter to weight that query.

In addition, if a keyword looks like a domain name, we search the "site" field.

I'm not sure if this is fully mergeable right now, but I wanted to get some feedback.

### CODE REVIEW

**Comment by ymatsuda** [comment]
Looks good!

**Comment by eishay** [comment]
are there unit tests along with the url indexing?

**Comment by gmethvin** [comment]
We have an ArticleIndexerTest which I think tests the indexing code. I'm going to try adding a test to make sure this new functionality works. A bunch of the tests in ArticleIndexerTest are commented out, so maybe I can get the old code working again as well.

**Comment by eishay** [comment]
The commented out tests are my bad. There was a problem when migrating to
Play2.1 and I had to comment them out and didn't get back to uncomment
them, it was actually on my today's todo list. Yea, please re-enable them
if you're at it.

**Pull request merged**
