### PR TITLE
Org avatar commander no longer reuses images

### PR DESCRIPTION
**Pull request by ryanpbrewster**
Every time a user uploads an org avatar, it gets processed and uploaded to S3.
It is unlikely that we will be able to reuse anything from the image store
given how many degrees of freedom a cropped scaled image has.

Also changed all the subclasses of ProcessImageRequest into case classes
so we can actually match on them.

Lastly, added URL parameters to the endpoint that specify the `(x,y)` offset and the `(width, height)` of the crop. Sorry if that makes your life horrible, @cvializ 

@andrewconner @leogrim

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
There is no greater feeling in the world than submitting a pull request with more code removed than added.

**Comment by andrewconner** [comment]
Seems reasonable. @cvializ The API change for org avatars is that is all happens in one call (instead of two). Provide the `x`, `y`, `width`, and `height` as url params in the POST upload file request

**Comment by ryanpbrewster** [comment]
@cvializ let me know when I should merge this. I don't want to break the (admittedly fragile) stuff we have kind of working.

**Comment by cvializ** [comment]
(working on other higher-priority tasks for Orgs right now)

**Comment by cvializ** [comment]
Let's do this now, since we've knocked out a lot of the MVP tasks

**Pull request merged**
