### PR TITLE
[DO NOT MERGE] removes dead and deprecated code

### PR DESCRIPTION
**Pull request by joshm1**
i'm still testing

@stkem @andrewconner @yipingliao @ahsu1230

### CODE REVIEW

**Comment by andrewconner** [comment]
Wahoo!

**Comment by ahsu1230** [comment]
@yipingliao, did we have a situation where if you kept a duplicate keep into a library, the old keep card would show up. Was that ever fixed, or would we still have that problem?

**Comment by stkem** [comment]
:+1:

**Comment by yipingliao** [comment]
Wow, nice. I'll need lots of help with merge conflicts. :)

**Comment by joshm1** [comment]
closing, going to use @yipingliao's pull request

**Pull request closed without merging**
