### PR TITLE
Firefox validation

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Wahoo! Mind sharing the key to a few people?

**Comment by cvializ** [comment]
sure, I can pass it on to you and anybody else. who else do you think ought to have it?

**Comment by andrewconner** [comment]
I suppose @eishay, but that's a good start

**Comment by cvializ** [comment]
kk, @eishay you can grab the key from https://addons.mozilla.org/en-US/developers/addon/api/key/ after logging in with the dev@42go.com credentials and save it in a `amo_secret.key` file

**Pull request merged**
