### PR TITLE
Sleeping in onStop so the load balancer gets the message (temporary measure)

### PR DESCRIPTION
**Pull request by stkem**

### CODE REVIEW

**Comment by eishay** [comment]
is 10 seconds enough?

**Comment by stkem** [comment]
Not to guarantee, no, but it should mitigate the problem quite a bit. Currently our init scripts kill the process if it doesn't shut down properly after 15 seconds, so I'll need to change those first, before making the wait bigger.

**Comment by eishay** [comment]
lets do it then, I would like to get bad api calls to ZERO please.
From: Stephen Kemmerling Stephen Kemmerling
Reply: FortyTwoEng/keepit reply@reply.github.com
Date: November 21, 2013 at 11:29:36 AM
To: FortyTwoEng/keepit keepit@noreply.github.com
Subject:  Re: [keepit] Sleeping in onStop so the load balancer gets the message (temporary measure) (#4857)  
Not to guarantee, no, but it should mitigate the problem quite a bit. Currently our init scripts kill the process if it doesn't shut down properly after 15 seconds, so I'll need to change those first, before making the wait bigger.

**Comment by stkem** [comment]
Working on it. I just pushed this to reduce the problem while I go through all the machines and update the init script.

**Comment by eishay** [comment]
great, thanks!

From: Stephen Kemmerling Stephen Kemmerling
Reply: FortyTwoEng/keepit reply@reply.github.com
Date: November 21, 2013 at 11:37:08 AM
To: FortyTwoEng/keepit keepit@noreply.github.com
Subject:  Re: [keepit] Sleeping in onStop so the load balancer gets the message (temporary measure) (#4857)  
Working on it. I just pushed this to reduce the problem while I go through all the machines and update the init script.

**Pull request merged**
