### PR TITLE
toggle slack digest notifications

### PR DESCRIPTION
**Pull request by camhashemi**
@leogrim @ryanpbrewster I'm trying to figure out the spec on this, it seems to make more sense to mute digest notifs on a per channel basis, but right now it's spec'd to mute on a per integration (i.e. library) basis. this one is to-spec, waiting on clarification. https://app.asana.com/0/32728208409723/80921334334285

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
Seems reasonable. Did you think about making `Muted` a status instead of a separate boolean flag?

**Comment by ryanpbrewster** [comment]
Thought about it more and I think the way you have it is better.

**Comment by camhashemi** [comment]
it could be a `Status` data type, but that's misleading since the two are independent of each other.

**Comment by camhashemi** [comment]
since we decided to go with org-global settings re: digest notifs, this is nixed. will add a `Feature` instead.

**Pull request closed without merging**
