### PR TITLE
Adding sourcemap to JS minification workflow

### PR DESCRIPTION
**Pull request by adamjgrant**
Want to give this a try, @andrewconner @cvializ ?

### CODE REVIEW

**Comment by adamjgrant** [comment]
Theoretically, this will automatically start working in Airbrake once deployed.

**Comment by andrewconner** [comment]
Does this expose our pre-uglified source?

**Comment by andrewconner** [comment]
But sure, let's try it.

**Comment by adamjgrant** [comment]
No, just the .map file.

So if you run `gulp assets:local-prod:rev` you'll see kifi.min.js.map and lib.min.js.map in dist

**Pull request merged**
