### PR TITLE
auth controllers!

### PR DESCRIPTION
**Pull request by raymondng**
Almost there. Only did the requisite to migrate things over. Will need a bit more work later on (including sending extra info back, etc.)

No attempt to do any major re-write at this point. I tried to preserve original code/structure as much as possible (to minimize risks/bugs). Nonetheless I think the result is simpler that's easier to understand and reason about.

`MaybeUserAction` is pretty much now the new base `Action` -- it's probably a bit too heavy for that. Should revisit it later for simpler/lighter code (e.g. `CORSAction` as suggested, something along those lines)

Yes tests passed. Doing some ad hoc testing as well.

@andrewconner please take a look.

### CODE REVIEW

**Comment by andrewconner** [comment]
Looks good, my eyeball compiler didn't see anything bad :)

**Comment by raymondng** [comment]
Awesome. That's good enough for me :)

**Comment by andrewconner** [comment]
Feel free to merge when ready. I can help test everything.

**Comment by raymondng** [comment]
Thanks. Will do.

**Comment by raymondng** [comment]
Looks like I am not done. There are some indirect dependencies on identityOpt that's hidden by `MaybeAuthenticatedRequest`. I was thinking I'd remove code after migration -- will need to remove this one now.

**Comment by raymondng** [comment]
AFAIK issue fixed. Will merge and push.
Please let me know if you spot any issues.

**Pull request merged**
