### PR TITLE
Moved Eliza's MessageThread into common

### PR DESCRIPTION
**Pull request by ryanpbrewster**
It's time to link keeps and message threads

@leogrim

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
@andrewconner @stkem

**Comment by andrewconner** [comment]
Why is this needed? If just for `Id` references, Léo has a more elegant solution for graph (it deals with typed `Id`s of models it can't see)

**Comment by stkem** [comment]
What Andrew said

**Comment by ryanpbrewster** [comment]
Okay, I'll grab Leo and make him reveal his secrets.

**Pull request closed without merging**
