### PR TITLE
Fixing reference to unminified kifi.js

### PR DESCRIPTION
**Pull request by adamjgrant**

### CODE REVIEW

**Comment by adamjgrant** [comment]
Still doesn't quite link to the rev-hashed kifi.js

**Comment by andrewconner** [comment]
Oh interesting, what happened?

**Comment by adamjgrant** [comment]
Looks like it's working in airbrake but it links to "/source/kifi.js" a
nonexistent file.

Not the end of the world, the line number provided is still correct and
helpful but it would be nice to be able to click into the unminified file
in Airbrake.
Le Fri, Jul 10, 2015 à 1:50 AM, Andrew Conner notifications@github.com a
écrit :

**Comment by adamjgrant** [comment]
To be clear, this PR doesn't fix that yet but it's bedtime so I'll see if I
can get further tomorrow.

**Comment by adamjgrant** [comment]
Might not merge this one. It involves submitting the unminified js to the CDN which kind of defeats the purpose of minifying.

**Pull request closed without merging**
