### PR TITLE
Feature/read only view header

### PR DESCRIPTION
**Pull request by adamjgrant**
Check it @cvializ @andrewconner

### CODE REVIEW

**Comment by adamjgrant** [comment]
Asana: [https://app.asana.com/0/42816489233171/44249098003175](44249098003175)

**Comment by cvializ** [comment]
repetitive, but lightweight. nice

**Comment by adamjgrant** [comment]
Can you suggest some ways to reduce repetition?

**Comment by adamjgrant** [comment]
I added some changes that make the `linkable` syntax more understandable. If you have other ideas, let me know and we can discuss.

**Comment by cvializ** [comment]
If I was more familiar with Angular and could whip this up in no time, I would do something allowing us to inject the desired DOM for the value.

Instead of passing `alink`, we'd pass DOM to the directive with the correct value to be shown when it's not being edited.

```
<span kf-click-to-edit on-save="save" readonly="readonly" input-placeholder="'e.g. http://example.com'" value="profile.site">
  <a href="{{profile.site}}">{{profile.site}}</a>
</span>
```

but I don't know how you'd actually implement it, because I'm lacking in some deeper Angular knowledge

**Comment by adamjgrant** [comment]
Yeah, so something like

```
<[element] class="kf-click-to-edit" ...>
  {{ value }}
</[element]>
```

Where we could specify the DOM element?

**Comment by adamjgrant** [comment]
React might be able to do something like this :)

**Comment by cvializ** [comment]
Haha yeah that's where I'm getting this feeling from, I used React heavily at my last place

**Pull request merged**
