### PR TITLE
library share (typeahead) result

### PR DESCRIPTION
**Pull request by raymondng**
This should address the library share typeahead issue of email contact name not being displayed.
Added bonus: no changes to frontend required.

Note that I didn't change `MaybeLibraryUser` as there are other dependencies.

@andrewconner @leogrim

### CODE REVIEW

**Comment by leogrim** [comment]
Why do we need to introduce yet another class from `MaybeLibraryMember`, can't we just modify to use a `BasicContact` instead of an `EmailAddress`?

**Comment by raymondng** [comment]
As discussed, there are other dependencies ... but maybe it's not too bad. Will take another look.

**Comment by raymondng** [comment]
Thanks for the feedback. Will merge to build on it. Looks like we need an additional API for `BasicContact`

**Comment by leogrim** [comment]
Awesome thanks!

**Pull request merged**
