### PR TITLE
removing cache invalidation for global bookmark count

### PR DESCRIPTION
**Pull request by eishay**
The reason for the timeouts bookmarks count we're getting in prod is that we reset the cache of global bookmark count whenever we add a new bookmark. Counting from the db is taking a very long time and we don't really have to have the most accurate number.

I'm going to have a one day ttl on the global counter cache and not invalidate it so the count of bookmarks is going to be at most one day old and once a day we'll have a slow query. 
If we'll see that more accurate numbers are important we can maintain a count approximation in memcached. 
Let me know if you have a simpler/better solution.

[fortytwo@b01 log]$ grep "count bookmarks" app.log
00:40:37.167 [play-akka.actor.default-dispatcher-104] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 45376.699348
00:45:15.155 [play-akka.actor.default-dispatcher-121] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 1.919791
01:34:15.771 [play-akka.actor.default-dispatcher-250] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 31254.075501
01:38:10.078 [play-akka.actor.default-dispatcher-254] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 37775.47149
01:38:48.205 [play-akka.actor.default-dispatcher-261] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 1.845231
01:38:48.216 [play-akka.actor.default-dispatcher-265] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 1.886363
01:39:05.385 [play-akka.actor.default-dispatcher-260] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 60550.180193
02:43:52.902 [play-akka.actor.default-dispatcher-446] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 28376.271887
02:55:50.942 [play-akka.actor.default-dispatcher-486] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 1.977794
03:31:03.957 [play-akka.actor.default-dispatcher-582] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 43022.322606
03:32:34.265 [play-akka.actor.default-dispatcher-586] INFO  c.k.c.performance.package$Stopwatch - [count bookmarks] elapsed milliseconds: 1.869838

### CODE REVIEW

**Comment by gmethvin** [comment]
Wouldn't it be possible to simply increment the value for the key when we add a new bookmark and decrement it when we deactivate/remove one?

**Comment by gmethvin** [comment]
Given what the bookmark count is used for I think this is a reasonable solution.

**Comment by eishay** [comment]
yes its possible, but its going to be a bit hard to avoid race condition with distributed system.
we can use stored proc as well, but its a bit more complex

**Comment by ymatsuda** [comment]
Why don't we maintain the counter asynchronously using the sequence number we have on bookmarks? There will be a delay, but it will be eventually consistent.

**Pull request merged**
