### PR TITLE
Be still my beating heart

### PR DESCRIPTION
**Pull request by stkem**
Responsive “learn more” footer part for mobile to prevent the heart icon from moving to its own row. Two hours of my life I will never get back.
@martinraison @andrewconner

### CODE REVIEW

**Comment by 2is10** [comment]
My hat’s off to you, good sir!

**Comment by andrewconner** [comment]
Oh my goodness. I raise my green bouncy ball to you.

**Comment by stkem** [comment]
:-P

**Comment by martinraison** [comment]
:thumbsup:

**Pull request merged**
