### PR TITLE
set author = null when messages + notifications are from system events

### PR DESCRIPTION
**Pull request by camhashemi**
@andrewconner 

due to the nice work by @cvializ on Friday, things should be okay. But we should keep an eye out.

### CODE REVIEW

**Comment by andrewconner** [comment]
Sweet, nice job.

**Comment by andrewconner** [comment]
Verify that mobile doesn't depend on this. Also, we'll need to wait for extensions to fully update. Usually we wait at least a week (preferably longer for something like this)

**Comment by camhashemi** [comment]
talked with @DerekBurch, he said mobile is explicitly looking for that "Kifi" user. so it'll break things, nice catch @andrewconner. I will do some extension work to get the desired behavior from system messages on the ext.

**Comment by DerekBurch** [comment]
Mobile depends on that 4242... user being there. I can fix it to not depend on it, but we will be stuck supporting old clients for a while :(.

**Comment by camhashemi** [comment]
It's not a big deal, I noticed that the ext wasn't using it and that it'd be more straightforward to just leave it out. There is some desired behavior I'm aiming for but it can be achieved on the frontend. What would help is looking for `.auxData` on messages / notifications from here on out (can't look for `author = None` since we're leaving it in) to work away from that dependency. Seems like we're going to add some emphasis on these system messages in the future, https://app.asana.com/0/32728208409723/89477821075071, so maybe we can transition when that makes its way to mobile.

**Pull request closed without merging**
