### PR TITLE
add last_activity_at and added_at single-col indices

### PR DESCRIPTION
**Pull request by camhashemi**
@leogrim @ryanpbrewster @andrewconner 

both of these columns are referenced many times in the `KeepRepo.getRecentKeeps` queries, but they don't have their own indices. Since we do sorts and aggregates on them, this could help.

### CODE REVIEW

**Comment by andrewconner** [comment]
Would a multi-column index work better than these single-column indices? Also, just as a reminder, this will lock the tables for 10+ minutes, so best to be done late.

**Comment by camhashemi** [comment]
I'm not sure. These tables already have multi-column indices on e.g. `organization_id, last_activity_at` and `user_id, last_activity_at`, but `last_activity_at` doesn't have a leftmost index on any of them.

**Comment by andrewconner** [comment]
Do we ever query by just `last_activity_at` and `added_at`? I'm not sure these would help then.

**Comment by camhashemi** [comment]
just for the `last_activity_at` query, on `bookmark`. so we can keep that one. maybe adding one on `ktl.keep_id` for these queries could help since we `group by(ktl.keep_id)` but it doesn't seem to have a usable index in this context.

**Comment by leogrim** [comment]
We should first do some testing / `explain` to figure out which indices would help

**Comment by camhashemi** [comment]
bueno, will do. thanks guys.

**Pull request closed without merging**
