### PR TITLE
unset as primary inactivated keeps

### PR DESCRIPTION
**Pull request by camhashemi**
@andrewconner @leogrim @ryanpbrewster seems like this will fix https://fortytwo.airbrake.io/projects/91268/groups/1081513854301130421/notices/1555526903015163758

it already finds a primary for that uri/lib, we need to set one of the keeps to be inactive

### CODE REVIEW

**Comment by andrewconner** [comment]
Eesh, not sure. I think primary should exist throughout inactive, but @leogrim may know better

**Comment by ryanpbrewster** [comment]
:+1: this is a good idea (although the fact that it is necessary points to a bug somewhere else in our codebase, since inactive keeps are supposed to be set to non-primary).

**Comment by camhashemi** [comment]
it's fine to keep primary throughout inactive, the thing is that we already find a uri_id, isPrimary combo for that library. so we should either make the new, definitely inactive keep not primary, or make the existing, possibly active keep not primary. seems like the latter is equivalent or better than the former.

**Comment by ryanpbrewster** [comment]
We haven't. At the point you've changed, all we know is that we're renormalizing a URI, and there is at least one keep that needs to be renormalized, and that one keep happens to be inactive.

If everything is good and right in the world, the fact that the keep is inactive necessarily implies that it is non-primary, so migrating it cannot possibly cause any issues. However, we have a bug elsewhere in our code, so we can be extra safe and set the (probably already non-primary) dead keep to be non-primary.

**Pull request merged**
