### PR TITLE
limit number of concurrent eliza requests

### PR DESCRIPTION
**Pull request by martinraison**
@eishay @andrewconner @leogrim @stkem 
I am opening this for suggestion - it may be better and a bit more flexible than falling back to using Await
Feel free to close if not a good solution (and merge if it is a good solution :) ).

### CODE REVIEW

**Comment by eishay** [comment]
wow, great idea!
I think @ymatsuda should review it

**Comment by martinraison** [comment]
Note: I was also wondering if we could achieve a similar effect with an Akka dispatcher. Our codebase already has a SlowRunningExecutionContext that limits the maximum number of threads to 1. However it is global to the application, so my understanding (I may be mistaken) is that calling Await on it would prevent it from being used for any other purpose.

**Comment by leogrim** [comment]
To be confirmed by @andrewconner, we had a discussion about having more flexible throttling in our data piping controllers a few days ago, Akka routers / dispatchers indeed sounded like a good way to go.

**Comment by raymondng** [comment]
Curious: why not use ExecutionContext.fj (ForkJoinPool) with some small number (you probably want < 4) as parallelism factor?

**Comment by martinraison** [comment]
Actually, after discussion with @leogrim, this may not solve our problem. Since we're just doing IO, we would still be issuing many concurrent calls, and just queuing the corresponding futures on that one thread. I'm implementing a more customized solution instead, that doesn't use Await. Thanks @leogrim for the suggestion!

**Comment by andrewconner** [comment]
Agreed, ForkJoinPool and this wouldn't necessarily help since we're making non-blocking requests. This could be fairly easily accomplished with Actors.

**Comment by andrewconner** [comment]
i.e., fairly easily create a `MaxParallelActor` that takes jobs that return Futures, and enqueues them if more than `x` are unresolved. If you're interested I can sketch out how it might work.

**Comment by raymondng** [comment]
:) I don't know enough about the context of this problem, and whether it's applicable or not. 
Just wondering how this differs from a customized FJPool ... maybe not, then.

**Pull request closed without merging**
