### PR TITLE
factor out private methods

### PR DESCRIPTION
**Pull request by yingjieMiao**
@raymondng 

essentially nothing changed at all.

### CODE REVIEW

**Comment by raymondng** [comment]
you never know :) lgtm

**Comment by yingjieMiao** [comment]
we shall know. going to deploy and monitor a while ;-)

**Comment by raymondng** [comment]
if you really want to be sure, you can deploy once per change, and then monitor -- up to you :)

**Comment by yingjieMiao** [comment]
thanks for the tip.

**Pull request merged**
