### PR TITLE
using field injection into a trait for better locality of dependencies

### PR DESCRIPTION
**Pull request by 2is10**
@eishay @andrewconner @stkem 

Look at all the cruft this removes from `SharedWsMessagingController`. Are we philosophically opposed to field injection into traits?

### CODE REVIEW

**Comment by stkem** [comment]
I like this. Didn't know it was possible.

**Comment by andrewconner** [comment]
I didn't either. You know, we have several very messy constructors and traits because of this. If I remember right, DbRepos and caching suffer from it.

**Comment by andrewconner** [comment]
How does this handle an injection failure?

**Comment by eishay** [comment]
It does make these classes harder to instantiate when we want to test them. Though most cases we use guice to do it when they get very complex with lots of dependencies.
I'm ok with it.

**Comment by 2is10** [comment]
> How does this handle an injection failure?

Throwing a injection exception, same as constructor injection failures, I imagine.

If scala vals are implemented as final fields, we may want to write tests for this and watch for NPEs in production. [This page](https://code.google.com/p/google-guice/wiki/Injections#Field_Injection) says “Avoid using field injection with final fields, which has [weak semantics](http://docs.oracle.com/javase/7/docs/api/java/lang/reflect/Field.html#set%28java.lang.Object, java.lang.Object%29).”

I ran the eliza tests, but now that I look, it appears that neither the controller nor the trait has any test coverage.

**Comment by 2is10** [comment]
If the finality of the fields is an issue, then a potentially less risky approach would be using setter (a.k.a. “method”) injection on non-final fields, but that’s more verbose.

**Comment by 2is10** [comment]
I’ll close this for now, since I can’t vouch for its safety.

**Comment by 2is10** [comment]
(or just using `var` instead of `val`, I guess)

**Pull request closed without merging**
