### PR TITLE
Alternative design for profile widget

### PR DESCRIPTION
**Pull request by adamjgrant**
screen shot 2015-07-30 at 1 52 46 pm

### CODE REVIEW

**Comment by adamjgrant** [comment]
screen shot 2015-07-30 at 1 53 47 pm

**Comment by adamjgrant** [comment]
screen shot 2015-07-30 at 1 56 47 pm

**Comment by adamjgrant** [comment]
Going with the last one. @camhashemi @andrewconner @cvializ @ryanpbrewster

**Comment by cvializ** [comment]
:+1: The last one was my fave

**Comment by ryanpbrewster** [comment]
Can we reduce the `border-radius` of the bounding circle for the avatar? 50% is extreme. I honestly think it should be 0%.

**Comment by adamjgrant** [comment]
@ryanpbrewster Aesthetically, the problem is actually the image being used. Because it has empty space around it, it doesn't appear as a circle. The `border-radius: 50%` is meant to render a perfect circle as it does for the user profile image.

**Comment by adamjgrant** [comment]
Merging for now but we can continue discussions about the display of the org profile image and return to this.

**Pull request merged**
