### PR TITLE
[LAUNCH PULL REQUEST] DON'T MERGE, JUST REVIEW

### PR DESCRIPTION
**Pull request by eishay**

### CODE REVIEW

**Comment by eishay** [comment]
DONT MERGE

**Comment by eishay** [comment]
@andrewconner

**Comment by stkem** [comment]
@eishay as discussed (for the record) this needs the libraries experiment for everyone

**Comment by eishay** [comment]
@stkem added

**Comment by andrewconner** [comment]
"See how it works" link broken. https://www.kifi.com/how_it_works is a 404

Edit: nevermind, the link goes to kifi.com, not dev.ezkeep.com. So just broken in dev mode.

Google Play store links need to be fixed.

Team page is outdated, I believe we have a newer one from Alexandru. 

Should we replace the out dated Kifi?

**Comment by andrewconner** [comment]
Looks good! No major issues found so far.

**Comment by andrewconner** [comment]
It would help in dev mode for links to go to `/signup/facebook` and such (instead of forcing kifi.com). Though I imagine this is a marketing page issue?

**Comment by eishay** [comment]
team page will be updated with https://www.kifi.com/marketing/about/team
we'll add the new team members this week

**Comment by eishay** [comment]
@jaredpetker do you know what will be the new play store links?

**Comment by eishay** [comment]
@andrewconner regarding the `/signup/facebook` links - sure I agree. lets do it after launch

**Comment by jaredpetker** [comment]
https://play.google.com/store/apps/details?id=com.kifi

**Comment by andrewconner** [comment]
Good to know, I'll update the site too.

**Comment by andrewconner** [comment]
Should that link work now for the beta app? @jaredpetker (ie, opening it)

**Comment by jaredpetker** [comment]
No. It won't work until we are launched in the store

**Comment by eishay** [comment]
Thanks, i'll update the marketing site

**Pull request merged**
