### PR TITLE
Memcached Caching for hot queries

### PR DESCRIPTION
**Pull request by andrewconner**

### CODE REVIEW

**Comment by andrewconner** [comment]
Please review, but hold on merging. I want to make sure this connects in production as intended first (with AWS's security zones).

**Comment by eishay** [comment]
cool!
lets have the type features in :-)

**Comment by 2is10** [comment]
This is great. Do we want to invalidate memcache entries on writes? (e.g. when saving changes to a User)

**Comment by andrewconner** [comment]
Yes. I'm adding that with some better serialization too.

**Pull request closed without merging**
