### PR TITLE
I'm so sorry

### PR DESCRIPTION
**Pull request by stkem**
Really hacked fake “organization” page for a investor demo tomorrow morning. Will (hopefully) be reverted after.
(Only takes effect if you are an admin and go to a non www subdomain on kifi, specifically <username>.kifi.com)
@eishay @andrewconner @2is10

### CODE REVIEW

**Comment by andrewconner** [comment]
I cannot forgive.

**Comment by stkem** [comment]
well....

**Comment by 2is10** [comment]
:no_mouth:

**Comment by andrewconner** [comment]
Time to revert?

**Comment by eishay** [comment]
i'm ok with it

**Pull request merged**
