### PR TITLE
a few more logging

### PR DESCRIPTION
**Pull request by yingjieMiao**
@raymondng @leogrim 

I deployed scraper and shoebox. seems that the problem persist. Add some logging for now. Will remove them later.

### CODE REVIEW

**Comment by raymondng** [comment]
It appears that @leogrim's fix is working, at least for some of the identified issues about normalization loop. Of course, there might be remaining (new?) bugs to be squashed -- can you share your findings (probably not on github) about your observations wrt latest problems?

**Comment by yingjieMiao** [comment]
for example these two guys:

select \* from normalized_uri where id = 3429 or id = 1059893

If I convert UTC time correctly, the looping are still going on.

You can go to shoebox-demand-1 to see the log. search for 1059893

**Comment by yingjieMiao** [comment]
1. 3429 migrate to 1059893

02:56:33.789 [prod-actor-system-akka.actor.default-dispatcher-2] INFO  
c.keepit.model.NormalizedURIRepoImpl - 
[save(NormalizedUri(Some(3429),18053260,/_REDIRECTED_/,N/A,Some(Normaliz
ation(canonical)),Some(1059893),http://wiki.opscode.com/display/chef/Home))] 
mark scrapeInfo as INACTIVE; si=[ScrapeInfo(id=Some(358), uriId=3429, 
worker=Some(642)): state=inacti
ve, lastScrape=2014-06-05T02:55:14.000Z, 
nextScrape=9999-01-01T08:00:00.000Z, interval=24.0, failures=0, 
dstUrl=Some(https://wiki.opscode.com/display/chef/Home)]
1. orphan cleaner:

03:04:34.266 [prod-actor-system-akka.actor.default-dispatcher-8] INFO  
com.keepit.integrity.OrphanCleaner - /_orphan cleaner: processing 
bookmark with uriId 1059893_/
1. schedule scraping

03:04:34.324 [prod-actor-system-akka.actor.default-dispatcher-8] INFO  
com.keepit.integrity.OrphanCleaner - [checkIntegrity(1059893, false, 
true)]/_scheduling scrape_/ for 
uri=NormalizedUri(Some(1059893),18054059,ACTIVE,N/A,Some(Normalization(https://)),None,https://wiki.opscode.com/display/chef/Home)
1. scraper call back:

03:04:45.599 [play-akka.actor.default-dispatcher-15] INFO 
c.k.c.internal.ScraperCallbackHelper - /_scraper callback: save uri: 
1059893_//*
*/

03:04:45.600 [play-akka.actor.default-dispatcher-15] INFO 
c.keepit.model.NormalizedURIRepoImpl - about to persist 
NormalizedURI(Some(1059893),2014-02-06T01:01:12.000Z,2014-06-05
T03:04:34.306Z,3f98d7bc-37a2-4078-876b-8011737b0ad5,Some(Home - Chef - 
Chef Open Source 
Wiki),https://wiki.opscode.com/display/chef/Home,UrlHash(OZzixt4Tapc950gyy2aPCg==),scraped
,18054059,Some(2014-05-09T22:00:40.000Z),None,Some(Normalization(https://)),None,None)
1. another normalization service call, NormalizationServiceImpl.update():

03:04:45.854 [play-akka.actor.default-dispatcher-27] INFO 
c.k.n.NormalizationServiceImpl - 
/_[update(_/NormalizationReference(id=1059893, 
url=https://wiki.opscode.com/display/chef/H
ome, isNew=false, persistedNorm=Some(Normalization(https://)), 
correctedNorm=Some(Normalization(https://))),/_ScrapedCandidate(http://wiki.opscode.com/display/chef/Home,Normalizati_//*
_//_on(canonical)))]*/ 
relevantCandidates=ScrapedCandidate(http://wiki.opscode.com/display/chef/Home,Normalization(canonical))
1. 1059893 redirected to 3429

03:04:46.751 [play-akka.actor.default-dispatcher-32] INFO 
c.k.n.NormalizationServiceImpl - Better reference 3429: 
http://wiki.opscode.com/display/chef/Home found for 1059893: 
https://wiki.opscode.com/display/chef/Home

**Comment by yingjieMiao** [comment]
alright, what happened between 4 and 5: when scraper scraped the page, it reports canonical url, and shoebox will call `normalizationServiceProvider.get.update()`, in `shoeboxController`.

**Pull request merged**
