### PR TITLE
Adding older syntax to support IE

### PR DESCRIPTION
**Pull request by adamjgrant**
@andrewconner @cvializ

### CODE REVIEW

**Comment by cvializ** [comment]
I looked into this and got a strange error in IE11. It said "Assignment to read-only properties is not allowed in strict mode." Did you try this in IE?

**Comment by cvializ** [comment]
(I had to use `element[0].setAttribute('class',...)` to make it work)

**Comment by adamjgrant** [comment]
_smacks own hand_

**Comment by adamjgrant** [comment]
Getting a proper VM set up. I was being adventurous. Thanks, @cvializ

**Comment by cvializ** [comment]
I merged a fix for this earlier this week from another branch

**Pull request closed without merging**
