### PR TITLE
[#64639851641025] Consume the new api's enabling plan preview

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner @leogrim @JRuff42

### CODE REVIEW

**Comment by andrewconner** [comment]
Nice :+1:

**Comment by andrewconner** [comment]
Looks awesome! Nice @cvializ @leogrim @JRuff42

**Comment by cvializ** [comment]
@JRuff42 let me know what you think of the wording here before I ship it. I can put it under admin while we QA it today if you want.
screen shot 2015-11-13 at 9 20 31 am

**Comment by andrewconner** [comment]
> Your credit card... charged for -$155...

Should this hide if the balance is negative?

**Comment by cvializ** [comment]
Good catch, that line was in to make sure it looked good even though I
don't have a team that owes money.

**Comment by leogrim** [comment]
Note that you should show this only if the balance is negative _and_ the
payment status is `pending`, then you will be charged `-balance`

**Comment by leogrim** [comment]
Awesome! Small typo => I believe it should say `You *will* have a credit of...`, future tense :)

**Comment by cvializ** [comment]
I don't understand, why does it show that I (will) have more credit after I change to an annual plan?

https://www.kifi.com/kifi/settings/plan

**Comment by leogrim** [comment]
We're going to refund you the rest of your current plan, then charge you for the new one on the renewal date

**Comment by cvializ** [comment]
Thanks Léo, I hadn't noticed that til now!

**Pull request merged**
