### PR TITLE
Script to download a build from S3

### PR DESCRIPTION
**Pull request by stkem**
You'll need to have AWS access credentials env vars set up to make this
work. See at the very bottom here: https://github.com/boto/boto
@andrewconner

### CODE REVIEW

**Comment by eishay** [comment]
wohoo :-)

**Comment by andrewconner** [comment]
Who's eddie? :)

**Comment by andrewconner** [comment]
A friend of jenkins and marvin?

**Comment by stkem** [comment]
http://en.wikipedia.org/wiki/List_of_minor_The_Hitchhiker's_Guide_to_the_Galaxy_characters#Eddie

**Pull request merged**
