### PR TITLE
activity email (still a WIP - this is for internal testing and PR feedback)

### PR DESCRIPTION
**Pull request by joshm1**
.. and to keep from amassing a huge PR as I add more features

@stkem

### CODE REVIEW

**Comment by andrewconner** [comment]
Nice!

**Comment by stkem** [comment]
Sweet! That was quick! Will go through it in more detail soon.

**Comment by joshm1** [comment]
there's a good bit left (many TODO's). only added recos so far :)

**Comment by eishay** [comment]
nice, please have me on the experiment when its on

**Pull request merged**
