### PR TITLE
mobile feed

### PR DESCRIPTION
**Pull request by yingjieMiao**
@ebfio 

`expected2` in Line 51 of `MobileFeedControllerTest.scala` illustrates the json format.

Please let me know if this meets your need.

### CODE REVIEW

**Comment by ebfio** [comment]
@yingjieMiao Almost! I just need the page title... and we're ready to roll :)

**Comment by yingjieMiao** [comment]
Sure. not a problem. 

Also, please review the uri fields, I imagine many of them are not interesting for you. I should not send them to you. (e.g. createdAt, updatedAt, urlHash, state, seqNum)

**Comment by ebfio** [comment]
Ok! At a first glance, I don't need: updatedAt, urlHash, state and seq. (What it seq?)

**Comment by yingjieMiao** [comment]
seq = sequenceNumber. 

I believe createdAt is not relevant for you. That's the creation time for the uri, not the keep.

**Comment by ebfio** [comment]
Thanks! I need the creation date of the keep. Where can I find it?

**Comment by yingjieMiao** [comment]
"firstKeptAt". the first time this uri is kept in your social circle.

**Comment by yingjieMiao** [comment]
@ebfio 

updated.

**Pull request merged**
