### PR TITLE
Implement invite header for library card.

### PR DESCRIPTION
**Pull request by yipingliao**
https://app.asana.com/0/15523651812135/18412051444297

@andrewconner @ahsu1230 

Note that although calls to the "decline" endpoint succeed (200, with "success" in the response), when I reload the page the declined library still appears in my list of invited libraries. Not sure if this is intended behavior.

### CODE REVIEW

**Comment by ahsu1230** [comment]
I looked at the backend - it's a backend bug. When we get library & invite summaries, we forget to exclude `DECLINED` invites. Will fix it in next PR =)

**Comment by ahsu1230** [comment]
Thanks for this! It looked great :cake:

**Comment by andrewconner** [comment]
Great, awesome

**Comment by yipingliao** [comment]
Thanks for looking into the backend, @ahsu1230 :)

**Pull request merged**
