### PR TITLE
Stylus + smart file reload

### PR DESCRIPTION
**Pull request by martinraison**
@2is10 @andrewconner I suggest transforming all the *.css files into *.styl files and getting rid of the *.less ones. Since compiling Stylus files takes a bit of time, I also setup per-file reload using the gulp-watch plugin (this is a bit tricky for now, we might be able to simplify the logic as gulp evolves). Sending the reload message to the extension after saving a Stylus file takes under a second for me.

### CODE REVIEW

**Comment by martinraison** [comment]
Also, I separated this pull request in two commits: one for the *styl files generation (they are automatically generated) and another one for the live reload logic. Easier to review this way.

**Comment by 2is10** [comment]
Sweet, thanks for continuing to work on this. Let’s not merge this quite yet. I need some more time to review the entire gulp setup and to try it out for myself for at least a day before I feel confident enough to scrap the old workflow.

Also, I have another branch for the keeper redesign right now (`black`).

It would be fantastic if we could configure the .styl processing to output Chrome and Firefox flavors into their respective output directories.

Also, we’ll need to do a good bit of manual testing (or careful .css file diff examination) to make sure the .styl processing is not breaking anything. The prefixes can be tricky (e.g. using transitions with transforms). I found problems with LESS that shook my confidence in these tools.

**Comment by andrewconner** [comment]
Awesome! This work is really helping future extension development.

@2is10 Agreed on all points about being careful. Fortunately, Stylus supports CSS literals. After working with it for a few months, I do like it a bit more than LESS / SCSS. It's gaining community momentum as well.

**Comment by martinraison** [comment]
Agreed - we'll probably have to polish a few rough edges before before getting rid of the old workflow. I didn't remove the old css/less files on purpose in order not to break the old workflow, but I'm still not merging this yet.
The stylus files were generated with `stylus --css filename.styl filename.css`. For some reason I had to manually add quotes around data urls - other than that I didn't find any issues (apart from unnecessary commas or vendor prefixes).

**Comment by martinraison** [comment]
@2is10 we can definitely configure the build to only add `moz-` (resp `webkit-`) prefixes for the Firefox (resp Chrome) output directory. Right now I configured stylus to use both `moz-` and `webkit-` in all cases, because I'm still trying to figure out the best way to branch a stream without doing the initial work twice (there is `gulp-clone` but I couldn't use it in all cases)

**Comment by martinraison** [comment]
Closing this one, since we're pushing back Stylus a bit. Ported non Stylus-related changes of this pull request to #9712

**Pull request closed without merging**
