### PR TITLE
pointing out tests that tries to init db tables after the scope of the t...

### PR DESCRIPTION
**Pull request by eishay**
...est is closed

### CODE REVIEW

**Comment by eishay** [comment]
This PR is also demonstrating the right pattern to use `withDb() { implicit injector =>`.
If we aggregate few test cases with in the same injector context then we potentially spill state from one test to the other.
While doing it some tests broke, I fixed some and some which I didn't know how to quickly fix I commented out.

**Comment by eishay** [comment]
Please check it out @andrewconner @stkem @yingjieMiao @leogrim

**Comment by stkem** [comment]
- @ahsu1230

**Comment by 2is10** [comment]
good find

**Comment by ahsu1230** [comment]
nice! thanks!

**Pull request merged**
