### PR TITLE
Add a set of bot users to SlackTeam, ignore messages from them during…

### PR DESCRIPTION
**Pull request by ryanpbrewster**
… ingestion

@leogrim

### CODE REVIEW

**Comment by leogrim** [comment]
Do you think we should keep track of our own bot id separately? Could be useful in future APIs who knows?

**Comment by leogrim** [comment]
Also this means maintaining this list of bot users up-to-date, perhaps we should decouple this from ignoring Kifi bot which is straightforward?

**Comment by ryanpbrewster** [comment]
I can restrict the field to be just `bot_user_id`, and have `other_bot_ids` if we want to go forward with restricting other bot users.

**Comment by leogrim** [comment]
Yep

**Pull request merged**
