### PR TITLE
Refresh the org data when an org invite is accepted.

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner @ajkochanowicz  I think it's time to have a more centralized location for managing access to org data. Enter: the `orgProfileService`.

I'll be moving all the `net` calls into the service to keep all the knowledge in one place.

### CODE REVIEW

**Comment by andrewconner** [comment]
:+1:

**Comment by adamjgrant** [comment]
Glorius!

**Comment by adamjgrant** [comment]
Actually, do you get a 'userProfileService' is not defined error from jslint? @cvializ 
in route.js

**Comment by cvializ** [comment]
Oops my fingers slipped up, I'll fix that

**Pull request merged**
