### PR TITLE
Added a more robust test for org member listing

### PR DESCRIPTION
**Pull request by ryanpbrewster**
@camhashemi

### CODE REVIEW

**Comment by camhashemi** [comment]
@ryanpbrewster do these pass? Thanks. There's a bug in the `getMembersAndUniqueInvitees` method, because anonymous invites are considered `active` invites (they are retrieved from the repo and then filtered out in the commander, we should be filtering in the repo).

I was in the middle of adding an `ignoreAnonymous` boolean to the repo method before invites took over, but it needs fixing. Alternatively, we can consider anonymous invites as `accepted` or `inactive` as soon as they're created. That way, we don't have `pending` invites with no invitee.

**Comment by ryanpbrewster** [comment]
Right now they are only testing members. No invite logic yet.

I'm a big fan of these tests, and if you want to add one for invites I'd be thrilled. You can look at `LibraryCommanderTest` for `"get library invites"` for a test (and associated helper methods) that I wrote for library invites.

**Comment by camhashemi** [comment]
@ryanpbrewster still curious to your opinion on the anonymous invite solution

> I was in the middle of adding an ignoreAnonymous boolean to the repo method before invites took over, but it needs fixing. Alternatively, we can consider anonymous invites as accepted or inactive as soon as they're created. That way, we don't have pending invites with no invitee.

**Comment by ryanpbrewster** [comment]
For now, I'd say we should just ignore those when displaying org invites. Maybe we can add a specific query to find only the anonymous invites and the frontend can display those separately.

**Pull request merged**
