### PR TITLE
removing media queries

### PR DESCRIPTION
**Pull request by martinraison**
@andrewconner After discussion with product, we've decided to have the same layout on all email clients (this is what Twitter, Quora, etc seem to be doing), i.e. fixed width for the email. This should make the email problem much much (much) simpler. I'm starting by removing all media queries and will move on from there.

### CODE REVIEW

**Comment by martinraison** [comment]
(merging now, it's hard to test outside prod and I'll need to iterate fast)

**Comment by 2is10** [comment]
poor @stkem will never get those dark hours of his life back​

**Comment by stkem** [comment]
You won't hear any complaints form me about this. :-)

**Comment by martinraison** [comment]
Actually, media queries are back #8609 @stkem

**Comment by stkem** [comment]
Hmpf. I should perhaps read the pull requests in the other order. It looks like the embedded look here's were also removes (i.e. they are all at the end of the message again), correct?

**Comment by martinraison** [comment]
Yes - we got many design discussions/headaches last week

**Comment by martinraison** [comment]
Actually, now that everything seems to behave reasonably on all platforms, it _might be_ possible to have the look heres in the body of the message again.

**Comment by stkem** [comment]
Ok, I'll wait with further comment until I'm up to speed tomorrow :-/

**Pull request merged**
