### PR TITLE
server-side amplitude events will passthrough the device_id from the client

### PR DESCRIPTION
**Pull request by joshm1**
the `device_id` for user events has been "user_<id>" but this is redundant since we also send a separate `user_id` property and it also makes it difficult to link events between a visitor and a user after registration. this change will extract the device_id from a request cookie (if supplied) so events from a visitor that turns into a user will be linked to the same device id. this will also affect visitor events that pass through heimdal to ensure they set the client's device_id instead of the ip address (which is bad anyway).

@jaredpetker  For iOS/Android app events, is there a request header I can check for thats unique to the actual device?

@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Works for me

**Comment by jaredpetker** [comment]
I think we always send an "X-Kifi-Client" Header which would have
information as to what the client is, probably some code somewhere that
already handles this on the server and give some insight.

**Comment by joshm1** [comment]
@jaredpetker I see the code you're talking about. Is the value of this header unique even if different users have the same exact same phone and app server? The code below just extracts client, clientVersion, and clientBuild from that.

``` scala
  private def addKifiClientAndVersion(request: RequestHeader): Unit = {

    val clientVersion = request.headers.get("X-Kifi-Client") getOrElse ""

    def add(clientName: String, version: KifiVersion): Unit = {
      this += ("client", clientName)
      this += ("clientVersion", version.toStringWithoutBuild)
      this += ("clientBuild", version.toString)
    }

    val parts = clientVersion.trim.split("\\s")
    if (parts.size == 2) {
      val (client, version) = (parts(0), parts(1))
      client match {
        case "BE" => add("browserExtension", KifiExtVersion(version))
        case "iOS" => add("iOSApp", KifiIPhoneVersion(version))
        case "iOS Extension" => add("iOSExtension", KifiIPhoneVersion(version))
        case "Android" => add("androidApp", KifiAndroidVersion(version))
        case _ => log.error(s"unsupported X-Kifi-Client header: ${clientVersion}")
      }
    }
  }
```

**Comment by jaredpetker** [comment]
Oh for something unique, the most unique thing we give is something to
register the push token, but there isn't any perfect way to get a unique id
nowadays for a device.

**Pull request merged**
