### PR TITLE
Using ModelWithState

### PR DESCRIPTION
**Pull request by andrewconner**
@yingjieMiao made an awesome catch: we're caching inactive objects. He added a `ModelWithState` trait, and proposed that we do the following.

This adds it to all models that use a `state: State[T]`. On transaction complete, if it's a `ModelWithState` and the state is inactive, call `deleteCache` instead of `invalidateCache`.

@ymatsuda @eishay @leogrim @stkem @martinraison @raymondng

### CODE REVIEW

**Comment by stkem** [comment]
:+1:

**Comment by ymatsuda** [comment]
nice!

**Comment by raymondng** [comment]
good catch!

**Comment by yingjieMiao** [comment]
thanks! I am going to remove the duplicate logic in bookmarkRepo and uriRepo.

**Comment by leogrim** [comment]
Boom!

**Comment by yingjieMiao** [comment]
@andrewconner 

Just a reminder that bookmark and normalizedUri are not extending that trait yet.

**Comment by andrewconner** [comment]
Ah good catch. I'll add them.

**Pull request merged**
