### PR TITLE
more logging

### PR DESCRIPTION
**Pull request by yingjieMiao**

### CODE REVIEW

**Comment by yingjieMiao** [comment]
@stkem  this logging reveals some interesting problems...

**Comment by stkem** [comment]
like what?

**Comment by yingjieMiao** [comment]
[lrgc] total num of libraries for sorting: 32, lucky ones: 6

[lrgc] returing 32 reco libraries.
20:54:34.866 [play-akka.actor.default-dispatcher-8] INFO  

[lrgc] not enough lib recos userId=27875 actual=32 max=40 top 2 => ArrayBuffer(LibraryRecoInfo(27875,27545,8.6352,s:1.00-i:1.00-r:1.00-p:1.00-si:1.00-c:1.00), LibraryRecoInfo(27875,50874,8.52938,s:1.00-i:1.00-r:1.00-p:1.00-si:1.00-c:1.00))

This is for my fake user. Everything up to this point looks right: 6 lucky libraries. The top2 with high fake scores 8.xxx. 

looking into the database, there is only 1 special library is marked as delivered. (score = 8.5147. Not in the top 2 list!)

**Comment by yingjieMiao** [comment]
other things like:

total retrieved recos: 803. context = null
[lrgc] total num of libraries for sorting: 5, lucky ones: 0

Majority libraries are filtered out.

**Comment by stkem** [comment]
Very odd. Any idea what might be happening? Nonlinear scoring problem?

**Comment by yingjieMiao** [comment]
i think i find the problem:

shoebox side recoCommander Line 241:

```
  val libraries = db.readOnlyReplica { implicit s =>
    libRepo.getLibraries(libIds).toSeq.filter(_._2.visibility == LibraryVisibility.PUBLISHED)
  }.take(limit)
```

Orders are not preserved here. 

This is exactly where we just get result from curator, and just before we send 'delivered items analytics'!

**Comment by stkem** [comment]
Ahh, good find!

**Comment by stkem** [comment]
Can you fix it?

**Pull request merged**
