### PR TITLE
tune classifier

### PR DESCRIPTION
**Pull request by yingjieMiao**

### CODE REVIEW

**Comment by yingjieMiao** [comment]
@ymatsuda 

Does this look better?

**Comment by ymatsuda** [comment]
ok with me. but in don't know why the result was collapsed even after a few clicks of result. I suspect that the user might not describe the symptom precisely...

**Comment by yingjieMiao** [comment]
I heard there was a time shoeboxes were both down (not registered with zookeeper). Maybe related?

I will merge the code.

**Comment by yingjieMiao** [comment]
@ymatsuda 

I still  need to figure out a way to extract siteQuery scores using NamedQuery

**Pull request merged**
