### PR TITLE
make PostOffice require an implicit RWSession

### PR DESCRIPTION
**Pull request by gmethvin**
This should fix a lot of our current issues.

### CODE REVIEW

**Comment by 2is10** [comment]
Should we be concerned that this puts the actual sending of the emails within a r/w transaction?

```
    mailer.processMail(prepared)
```

How long can that take? Can it fail? (Might be bad to have to rollback/restart/retry an entire DB transaction just because there was an error persisting an email.) Might it be better to move any `PostOffice` calls that are inside database transactions out?

If `.processMail` always returns quickly and isn't likely to ever fail (e.g. by delegating to an actor), and so it's okay to do inside a database transaction, then I have one other suggestion: it would make the `PostOffice` API nicer to support both kinds of calls — either in a database transaction or not. (I was a bit sad to see a bunch of `db.readWrite` blocks introduced around `.sendMail` calls.)

**Comment by gmethvin** [comment]
@2is10 `mailer.processMail()` is run asynchronously. We synchronously commit the message to the database (which is relatively fast) so we know it's in the queue of messages to be sent out, and deal with the more expensive operation of sending the mail in MailSenderActor.

I agree with you about introducing the `readWrite`/`readOnly` blocks. It seems like a huge pain to have to change all calls to a service just because we now require a database session or a `readWrite` instead of a `readOnly`. It could also make it more difficult to modularize our code. I was thinking we should just make versions of `db.readWrite` and `db.readOnly` that use the existing session if one exists. I think this will probably make our code cleaner and more abstracted from database requirements. What do you think?

**Comment by eishay** [comment]
I rather be explicit on db sessions. I.e. whoever writes code should know if they're in a context of a sessions or not.

**Comment by 2is10** [comment]
Yes, I agree with Eishay in thinking it's important for us to be conscious of where db sessions begin and end. Also, `db.readWrite` inside of `db.readOnly` might fail (or at least block).

**Pull request merged**
