### PR TITLE
api integration testing

### PR DESCRIPTION
**Pull request by stkem**
@eishay @jaredpetker 
I'm currently working on the Jenkins side of this
cc @davoda @ebfio @2is10

### CODE REVIEW

**Comment by stkem** [comment]
Merging this to test the jenkins side of things. Happy to still address any comments you may have.
Also, probably slightly wider interest: cc @martinraison @andrewconner

**Comment by eishay** [comment]
looks great, guys, please take a look!

**Comment by stkem** [comment]
Note that this does _not_ natively support websocket request testing. Looking into that.

**Comment by 2is10** [comment]
Cool. `.toss()` is my favorite part.

**Comment by martinraison** [comment]
Great!

**Pull request merged**
