### PR TITLE
rolling out new "html-plain" library invite emails

### PR DESCRIPTION
**Pull request by camhashemi**
@stkem Sterling gave the thumbs up.

### CODE REVIEW

**Comment by stkem** [comment]
:+1: Go for it!

**Comment by eishay** [comment]
did you test it in production?

**Comment by camhashemi** [comment]
@eishay last night and today were spent doing so.

**Comment by eishay** [comment]
great, looking forward to see responses. wonder if we can see now open
rates on sendgrid. did you use a unique category for them?

**Comment by camhashemi** [comment]
I'm not 100% sure what you mean right now but I'm looking into it.

**Comment by eishay** [comment]
`category = NotificationCategory.User.WELCOME` its fine, just remembered we're not a/b testing it so its not an issue.

**Comment by camhashemi** [comment]
I see now via https://team42.atlassian.net/wiki/display/ENG/Email+Overview. I'll send you a library invite so you can see what it looks like.

**Pull request merged**
