### PR TITLE
google drive normalization

### PR DESCRIPTION
**Pull request by ymatsuda**
@yingjieMiao and @leogrim , does this seem ok?

### CODE REVIEW

**Comment by yingjieMiao** [comment]
lgtm. We can later manually trigger a renormalization for google drive urls.

**Comment by raymondng** [comment]
Is this urgent? I'd appreciate if we can hold off on merging this until later today -- moving stuff around trying to kill off old code.

**Comment by leogrim** [comment]
lgtm

2013/12/4 Raymond Ng notifications@github.com

**Comment by raymondng** [comment]
Cool. Thanks much @ymatsuda!

**Pull request merged**
