### PR TITLE
moved default page normalization from URI to Prenormalizer

### PR DESCRIPTION
**Pull request by ymatsuda**
@leogrim and @yingjieMiao , please review this change.

### CODE REVIEW

**Comment by yingjieMiao** [comment]
sure.

**Comment by leogrim** [comment]
Given that normalizers are now URI => URI partial functions, we could probably move this logic to its own normalizer, outside of Prenormalizer and simply call it from there.

**Comment by ymatsuda** [comment]
Good idea. I will create DefaultPageNormalizer.

**Comment by ymatsuda** [comment]
created DefaultPageNormalizer. Prenormalizer calls it (if applicable) before calling other normalizer.

**Comment by yingjieMiao** [comment]
lgtm

**Pull request merged**
