### PR TITLE
faster decay after selection of persona

### PR DESCRIPTION
**Pull request by yingjieMiao**
@eishay @stkem 

per discussion with Eishay, persona induced interest score decays much faster now.

### CODE REVIEW

**Comment by yingjieMiao** [comment]
decay

**Comment by yingjieMiao** [comment]
image above shows the weight of keep induced interest score W. vertical indicates num of days since user selected persona. horizontal indicates number of keeps (1 unit = 20 keeps). W is from 0 to 1 (dark to white)

**Comment by stkem** [comment]
What motivated this?

**Comment by yingjieMiao** [comment]
One investor found after selection of persona, recommendation quality drops. @eishay thinks it makes sense to let the persona effect drops faster (perviously, it takes about 6 ~ 8 weeks to fade out), now it's like a week. 

Of course, if the user hasn't kept anything, the persona effect is still there (the PNG image is misleading on the left boundary)

**Pull request merged**
