### PR TITLE
Adds a Wikipedia normalizer and removes RemoveWWWNormalizer (static sche...

### PR DESCRIPTION
**Pull request by leogrim**
...me normalization rules to be used instead)

### CODE REVIEW

**Comment by leogrim** [comment]
@yingjieMiao 
This can be merged, can we run a renormalization on Wikipedia to apply these static changes? 
(the scheme normalization could be taken care of by the dynamic normalizer, but there are a few urls concerned by the specific mobile scheme)

**Comment by yingjieMiao** [comment]
lgtm.

What are your concerns for the mobile case?

We can always try readOnly mode first.

**Comment by leogrim** [comment]
No concern, just saying that thepure http/https renormalizations could be
processed lazily by the normalization plugin, but there are 6 mobile urls
that need your renormalization magic :)

2013/10/29 yingjieMiao notifications@github.com

**Comment by yingjieMiao** [comment]
Oh I see. I can do that later. Should be OK.

**Pull request merged**
