### PR TITLE
clean prod conf. move things to scraper conf

### PR DESCRIPTION
**Pull request by yingjieMiao**
@raymondng @eishay @martinraison 

this configs are used in `ScraperConfigModule`.

### CODE REVIEW

**Comment by raymondng** [comment]
`ScraperConfigModule` is in common -- move to scraper too?

**Comment by yingjieMiao** [comment]
as discussed, this is used in shoebox. Shoebox needs some of the scraper configs. Potentially we can split the scraper configs in to two parts.

**Comment by eishay** [comment]
What was the final decision on scraper conf?

**Comment by yingjieMiao** [comment]
Shoebox side did use a small portion of scraper configs.  The scraper 
config module provides ScraperConfig instance to both shoebox and scraper.
The dependency prevents us to move this to scraper.

I can spend some time today to split the config class into two parts, 
then we can move most of the configs to scraper.

**Comment by eishay** [comment]
Please do, prod.conf should not have things that are not shared between
services.
Thanks!

**Pull request merged**
