### PR TITLE
Do not store JsNull in the database

### PR DESCRIPTION
**Pull request by leogrim**
@stkem @ryanpbrewster

### CODE REVIEW

**Comment by stkem** [comment]
What was the problem here?

**Comment by leogrim** [comment]
we prefer to store a real `null` over a `Jsnull`

**Comment by stkem** [comment]
But now you have two nulls, effectively. `None` and `Some(JsNull)`

**Comment by leogrim** [comment]
Nope, `Some(JsNull)` should not be in there.

**Comment by stkem** [comment]
My point is that the type now has two null cases.

**Comment by ryanpbrewster** [comment]
Having just come from Eliza, where we had a bunch of `JsNull` entries in the db, it's kind of a pain to work with. Although technically it more ambiguous with both `null` and `JsNull` as possible entries, in practice there shouldn't be any `JsNull` entries anywhere.

**Comment by ryanpbrewster** [comment]
I don't like `JsNull` specifically because I like `Option[T]` so much. IMO it's much like having Java's `null` around: technically using an `Option[T]` is allowing two null cases (either `None` or Java `null`), but in practice if we just possibility of `null` then it's way better to encode the semantics of nullability into the type.

**Pull request merged**
