### PR TITLE
Firefox/review feedback

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner I get intermittent errors on Google search, and I can't tell if it's Chrome's devtools/livereload being whack or if there a legitimate error, but could you pull and test this before I merge? Thank you!

### CODE REVIEW

**Comment by andrewconner** [comment]
Sure. Will do today.

**Comment by cvializ** [comment]
I figured it out, it's in the google_inject require. Chrome doesn't like api.require when it pre-loads the page. Trying to figure a workaround.

**Comment by andrewconner** [comment]
Oh, is it too soon? I know google_inject is special in that it gets injected earlier than other scripts normally do (so we can be super fast)

**Comment by cvializ** [comment]
I figured out why Chrome was being weird: if you want to load a dependency in `google_inject.js`, you need to add it to the `manifest.json` entry for it. I think it's because `manifest.json` automatically loads the dependencies of scripts that run at `document_start`, while our normal mechanism runs after `api.js` has been loaded.

Anyway I'm ready to merge it unless you have any comments

**Pull request merged**
