### PR TITLE
Fix suggested searches

### PR DESCRIPTION
**Pull request by leogrim**
@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Nice. :+1:

**Comment by leogrim** [comment]
I'm afraid the whole library search suggestion is really slow. We're like
2.4k libraries behind and there's no priority queues, new libraries are
treated the same as existing ones.

**Comment by andrewconner** [comment]
How often are existing libraries recalculated?

**Comment by leogrim** [comment]
I'm pretty sure they're queued based on keeps' sequence number

**Comment by andrewconner** [comment]
Oh wow, so on every keep? We could do a lot better.

**Pull request merged**
