### PR TITLE
play23 -- merge into master

### PR DESCRIPTION
**Pull request by raymondng**
Okay so this should do it.

It's a mostly by-the-book migration (see https://www.playframework.com/documentation/2.3.x/Migration23) for details, with some additional fixes and workarounds due to dependency upgrades (akka/specs/mongo), etc.

Current status: 
unit/integration tests -- ok
local ad hoc tests -- ok
prod deployment (heimdal/scraper/abook/shoebox) -- ok

Aside from typical procedure, we have conducted rather extensive ad hoc testing and pre-merge prod deployment validation. There might still be issues but thus far things look to be in reasonable shape.

@andrewconner @eishay -- please feel free to merge.

CC: @42eng

### CODE REVIEW

**Comment by andrewconner** [comment]
Awesome. I will wait until you're out of the interview.

**Comment by eishay** [comment]
wohooo! Congrats

**Comment by andrewconner** [comment]
Closing (no merge) for safety. Please merge in my PR (and pull parent), and take a look at the cast class exception.

**Comment by raymondng** [comment]
Thanks. Will take care of it.

**Pull request merged**
