### PR TITLE
scraper: more clean-up (-SyncScraper)

### PR DESCRIPTION
**Pull request by raymondng**
A simple rename. Async already removed so no need to call this SyncScraper. It's just a worker now :)

@leogrim @yingjieMiao @martinraison -- please take a quick look. Thanks!

### CODE REVIEW

**Comment by yingjieMiao** [comment]
lgtm

**Comment by yingjieMiao** [comment]
merge conflicts?

**Comment by raymondng** [comment]
no way :) let me check

**Comment by martinraison** [comment]
:thumbsup:

**Pull request merged**
