### PR TITLE
not showing the "kill it" button on releases newer than the golden one

### PR DESCRIPTION
**Pull request by 2is10**
@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Nice, cool.

**Comment by andrewconner** [comment]
Is that what we want? So if we kill a version, we always want to increase the golden past it?

**Comment by andrewconner** [comment]
I can think of a few times we had a bad release, and we specifically wanted clients of just that.

**Comment by 2is10** [comment]
only hiding it on the first row and updated the protocol, as we discussed

**Pull request merged**
