### PR TITLE
Rework Firefox's script loading to comply with addon review

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner This should remove the biggest obstacle to putting Kifi in the Mozilla addon site.

It removes the need to eval the lazy loaded scripts by wrapping the dependencies in module functions, loading the scripts, then calling the modules functions instead of evaling the code.

Wrapping the files in module functions would violate the script's expectations of setting globals with `var`, so I wrote a tool that reads the files for globals, then directly prepends a `window.` to explicitly reference these as globals.

The main changes are to the `gulpfile`, so the risk should be low, and it doesn't affect the Chrome extension at all. Let me know what you think

### CODE REVIEW

**Comment by cvializ** [comment]
Here's the `explicit-globals` package. It's on my GitHub account now, but we can move it wherever https://github.com/cvializ/explicit-globals

**Comment by andrewconner** [comment]
Pretty cool. Should I pull this and do testing?

**Comment by cvializ** [comment]
Yes, please. It works in Firefox Nightly and 43 (and probably most versions in use now)

**Comment by cvializ** [comment]
@andrewconner I've been testing this regularly and everything seems kosher so far. I'll merge it tomorrow unless you have any objections. I'll submit it for formal review by Mozilla and hopefully they'll give us a :+1: for review and we'll be in the addon store :smiley:

**Comment by andrewconner** [comment]
Oh sweet. Go for it. Does this rid us of the `eval` hack?

**Comment by cvializ** [comment]
Alright, will do. This does indeed get rid of eval so we should pass their review

**Pull request merged**
