### PR TITLE
Fixes to previous Notifications PR

### PR DESCRIPTION
**Pull request by maxov**
@ryanpbrewster

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
Keep this open. Don't merge it.

**Comment by ryanpbrewster** [comment]
Ignore that, misclick.

**Comment by maxov** [comment]
@ryanpbrewster ready to merge?

**Comment by ryanpbrewster** [comment]
@gratimax I think so. Github doesn't make this (reviewing a merged PR) as easy as I'd like. I wish there were some way to create a "fake" PR that was just this rebased on top of your previous one, so we could comment on the "up-to-date" code while still seeing all of the new code.

**Comment by andrewconner** [comment]
Looks good to me :+1:

**Pull request merged**
