### PR TITLE
rename orgs to teams in all copies

### PR DESCRIPTION
**Pull request by camhashemi**
@leogrim for https://app.asana.com/0/42816489233171/63432238353151

### CODE REVIEW

**Comment by camhashemi** [comment]
@andrewconner

**Comment by camhashemi** [comment]
there's additionally https://www.kifi.com/teams, but I think it's acceptable there as to diversify the vocab between header and subheader

**Comment by andrewconner** [comment]
:us:

**Comment by camhashemi** [comment]
"America Means Yes"

I'm gonna put that on a trucker hat

**Comment by ryanpbrewster** [comment]
:+1: nice

**Comment by leogrim** [comment]
:+1:

**Pull request merged**
