### PR TITLE
Takes the already existing ability to get keep updates from followed …

### PR DESCRIPTION
**Pull request by jaredpetker**
…libraries and pulls it out into it's own request

### CODE REVIEW

**Comment by jaredpetker** [comment]
This isn't really the final version that we would use, but something to get us started with, doesn't support paging, etc.

**Comment by jaredpetker** [comment]
@stkem @eishay @andrewconner

**Comment by stkem** [comment]
:+1: :-D

**Comment by jaredpetker** [comment]
I guess ignore this for now, working on support for querying before a time with count (paging)

**Comment by jaredpetker** [comment]
Ok, I think this is ready for merge, as far as I can tell at least - very possible I'm wrong. Doesn't alter any existing endpoints / live code

**Comment by andrewconner** [comment]
Awesome @jaredpetker. Merging

**Pull request merged**
