### PR TITLE
Renamed (Refactor) all Database.readOnly => Database.readOnlyMaster

### PR DESCRIPTION
**Pull request by ahsu1230**
Refactoring Database.readOnly to split readOnly's for easier choices between reading from Master or Slaves

@eishay @andrewconner @martinraison @leogrim @lawzlo @stkem

### CODE REVIEW

**Comment by 2is10** [comment]
This will make it harder to tell where we’ve intentionally chosen `readOnlyMaster` and where we haven’t yet considered where we should be reading from.

I’d recommend just deprecating `readOnly` for now and leaving all call sites alone. Then we can gradually, intentionally and carefully replace each `readOnly` call with either `readOnlyMaster` or `readOnlySlave`.

**Comment by ahsu1230** [comment]
Gotcha. I'll revert back to leaving readOnly calls as they were
and add in a readOnlyMaster & readOnlySlave

**Comment by eishay** [comment]
I actually like to get rid or readOnly in one shot. If we won't do it, it may take a long while until we'll get there and I rather not have deprecated code for a long while.

Its actually not too hard to trace the `readOnlySlave`, in most places we have it explicit in the code as in 

``` scala
db.readOnly(dbMasterSlave = Slave) { implicit ro =>
```

There are only five places in the code where we use the implicit option as in 

``` scala
implicit val dbMasterSlave = Database.Slave
```

and even if we error by using master instead of slave (we should always opt to that error then the other option), then no harm done.

**Comment by 2is10** [comment]
Okay. I had forgotten there was already a way to specify "slave" and didn’t
realize that this was just changing the calling syntax.

**Pull request closed without merging**
