### PR TITLE
Entertaining a design for org attribution

### PR DESCRIPTION
**Pull request by adamjgrant**
screen shot 2015-07-31 at 10 25 48 am

### CODE REVIEW

**Comment by andrewconner** [comment]
Nice! Though,



looks a bit like someone with a large forehead.

**Comment by adamjgrant** [comment]
You're right to use the metaphor of a face for these cards. As an alternative, could we limit titles for org cards to two lines?

**Comment by adamjgrant** [comment]
Steering the conv. into https://app.asana.com/0/42816489233171/42988592277573

**Comment by adamjgrant** [comment]
screen shot 2015-07-31 at 3 33 35 pm

**Comment by andrewconner** [comment]
Favorite so far.

**Comment by adamjgrant** [comment]
Eishay reminded me orgs should be rounded rectangles.
screen shot 2015-07-31 at 3 38 09 pm

**Comment by ryanpbrewster** [comment]
Even better! I really like that design.

**Comment by cvializ** [comment]
beautimous

**Pull request merged**
