### PR TITLE
Feature/ext org priv

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner @adamjgrant 

| Non-org-user | Org-user, selected a personal space | Org-user, selected an org space | Org-user, private |
| --- | --- | --- | --- |
| screen shot 2015-09-03 at 11 14 47 am | screen shot 2015-09-03 at 10 54 09 am | screen shot 2015-09-03 at 10 54 25 am | screen shot 2015-09-03 at 11 21 09 am |

### CODE REVIEW

**Comment by adamjgrant** [comment]
Epic!

**Comment by adamjgrant** [comment]
Actually, could we color the text as well?

**Comment by cvializ** [comment]
Totally, the same shade? I couldn't tell if that would seem too cartoony.

**Comment by adamjgrant** [comment]
Yeah, that might...What if we kept the font weight the same but made the color darker? Either way, whatever you decide on is fine.

**Comment by cvializ** [comment]
@adam, I think this looks OK, but I'm still open to just gray+bold text when selected. With the color it's bold enough to still seem informative
screen shot 2015-09-03 at 12 39 07 pm

**Pull request merged**
