### PR TITLE
double hashtag on keep cards on site

### PR DESCRIPTION
**Pull request by eishay**
does keep.sourceAttribution.slack.message.channel.name supposed to hold the hashtag of the slack channel name now?

https://app.asana.com/0/86762801523563/103352990742774

### CODE REVIEW

**Comment by eishay** [comment]
@leogrim @andrewconner @cvializ 
That should fix the https://app.asana.com/0/86762801523563/103352990742774 bug, but is it the right solution?

**Comment by cvializ** [comment]
I know in the extension, the data  coming down does not have the # prefixed, and its code has to add the #. I am not sure why the site is receiving different data. @leogrim ? @ryanpbrewster ?

**Comment by leogrim** [comment]
:+1:

**Comment by leogrim** [comment]
@cvializ there were issues over the weekend with Slack API, I reworked the code so that the backend deals with channel names more clearly and systematically adds the `#` when necessary, that means only for public channels like Slack does.

**Pull request merged**
