### PR TITLE
remove super special user

### PR DESCRIPTION
**Pull request by yingjieMiao**
@stkem

### CODE REVIEW

**Comment by stkem** [comment]
Huh?

**Comment by yingjieMiao** [comment]
you still want to keep him there? I thought he has caught up?
Otherwise I will just remove logs.

**Comment by stkem** [comment]
yeah, let's keep him there. He has indeed caught up, but this way he'll also update quicker when hi profile changes.

**Comment by yingjieMiao** [comment]
ok.

**Pull request merged**
