### PR TITLE
upgrading to play 2.3.5

### PR DESCRIPTION
**Pull request by stkem**
mostly to fix a security vulnerability (see https://www.playframework.com/changelog)
thanks @andrewconner (or should I say typesafe subscription) for discovering
@raymondng @eishay

### CODE REVIEW

**Comment by andrewconner** [comment]
Of note, we're not exposed, but it's good to not have open holes around.

**Comment by raymondng** [comment]
Thanks. Should eng@42go.com be subscribed to the subscription mailing list?

**Comment by andrewconner** [comment]
It's an alias, so can't be a member of a google group. If we changed it, we could.

**Comment by andrewconner** [comment]
This is a good thing to subscribe to: https://groups.google.com/forum/#!forum/play-framework-security

**Pull request merged**
