### PR TITLE
Better linkifier!

### PR DESCRIPTION
**Pull request by andrewconner**
Test cases I used:

http://foo.com/blah_blah.html
http://foo.com/blah(d)_blahas
bob.co/page(1).html.

http://www.google.com/asd?asdasd=asdadsasd.
google.com/asd(asd)a.
I tried google.com.
I tried google.com, but
I tried google.com/sdf, but
www.microsoft.com/article_(13).aspx.asdasdasd.asd.
(jdfhds.com/asd)
bob.co.uk
http://bob.co.uk.co.com asdsadasddsasd
www.sdfsdf.co/dfg
not.asite

(and now http://en.ei.com/Com_(2)d(d) daas

### CODE REVIEW

**Comment by 2is10** [comment]
how does this involve kifi_logo.png exactly?

**Comment by andrewconner** [comment]
Whoops, I can move to a separate commit if you'd prefer. It's a new image (changed colors)

**Comment by 2is10** [comment]
yay!

**Comment by 2is10** [comment]
nice work

**Pull request merged**
