### PR TITLE
Admin can change ownership

### PR DESCRIPTION
**Pull request by adamjgrant**

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
Be careful, you only want the owner to be able to transfer ownership. And just as with the option to delete an organization, we should probably have a bunch of safeguards.

**Comment by adamjgrant** [comment]
@ryanpbrewster Good tip. I think I'm going to implement an "Are you sure" somewhere in the process so owners understand the implications of what they're doing.

**Comment by ryanpbrewster** [comment]
:+1: definitely a good call.

**Comment by adamjgrant** [comment]
screen shot 2015-08-10 at 5 01 33 pm

Hmm, struggling with these icons.

**Comment by andrewconner** [comment]
:+1:

**Comment by adamjgrant** [comment]
Finally ready @camhashemi @andrewconner @ryanpbrewster

**Comment by adamjgrant** [comment]
screen shot 2015-08-11 at 4 23 02 pm
screen shot 2015-08-11 at 4 23 08 pm
screen shot 2015-08-11 at 4 23 12 pm

**Comment by andrewconner** [comment]
:+1:

**Pull request merged**
