### PR TITLE
fix /integrations bugs

### PR DESCRIPTION
**Pull request by camhashemi**
@cvializ @jaredpetker 

reproduced whenever I wasn't able to see the page (/settings/integrations) for an org I'm not a member of. that's why the `config` object isn't there, but seems like we should error before generating the controller?

also changed a permission since it's up in the air right now

### CODE REVIEW

**Comment by cvializ** [comment]
:mag: excellent investigation, I'm surprised it didn't error sooner too

**Comment by andrewconner** [comment]
Mind checking out https://app.asana.com/0/42816489233169/83829915524510 ?

Carlos thinks the issue is here. So: if the user can edit integrations (which I _think_ is everyone by default, right?), they see the link on the sidebar and they can see the page.

**Comment by jaredpetker** [comment]
Yea, apparently different logic is gating the showing of the link vs the
showing of the page.

**Comment by camhashemi** [comment]
@jaredpetker @andrewconner the spec wasn't agreed upon, so the implementation wasn't unified. should be fixed in prod now.

**Pull request merged**
