### PR TITLE
@json macro annotation for case classes + example

### PR DESCRIPTION
**Pull request by martinraison**
@andrewconner 
sbt reload required - added 2 small prod examples (could be used in many other places)

### CODE REVIEW

**Comment by andrewconner** [comment]
Tests to verify it works?

**Comment by eishay** [comment]
:clap::clap::clap::clap::clap::clap::clap:

**Comment by martinraison** [comment]
added tests

**Comment by leogrim** [comment]
Sweet!

**Comment by martinraison** [comment]
I removed the tests and put them in https://github.com/kifi/json-annotation instead

**Pull request merged**
