### PR TITLE
make the response type be html in popup so the relevant script will run.

### PR DESCRIPTION
**Pull request by eishay**
i think this was broken for couple of months now since the UserAction refactoring
Thanks to @2is10 for pointing the problem

### CODE REVIEW

**Comment by eishay** [comment]
@raymondng @andrewconner 
need to review UserController#576

**Comment by 2is10** [comment]
Andrew & Ray, it seems the refactoring changed our default content type from `text/html` to `text/plain`.

**Comment by andrewconner** [comment]
There is no default type in Play. It's just based on the type you pass to the Status class — `Html` is `text/html`, `String` is `text/plain`, etc.

**Comment by andrewconner** [comment]
Previously, we basically overrode whatever Play decided it would be with `text/html`. Not a good pattern in general.

**Comment by 2is10** [comment]
Agreed.

**Pull request merged**
