### PR TITLE
Adding moving box icon

### PR DESCRIPTION
**Pull request by adamjgrant**
@cvializ Here is your moving box.

Use the symbol-sprite directive with the `box-open` icon

### CODE REVIEW

**Comment by cvializ** [comment]
:clap:

**Comment by andrewconner** [comment]
I wish github had svg previews so I could marvel at your handywork.

**Comment by cvializ** [comment]
I read they had some sort of SVG viewer, at least for diffing

https://github.com/blog/1902-svg-viewing-diffing

**Comment by cvializ** [comment]
@andrewconner https://github.com/kifi/keepit/blob/feature/moving-box/kifi-backend/modules/shoebox/angular/img/symbol-sprites/lib/box-open.svg

**Comment by adamjgrant** [comment]
Just press "View" on the code preview @andrewconner

**Comment by andrewconner** [comment]
You guyyysss

**Pull request merged**
