### PR TITLE
[DO NOT MERGE] Twitter Auth (pre-liminary)

### PR DESCRIPTION
**Pull request by raymondng**
Bare bones Twitter integration (essentially a cleaned-up version of what Eishay saw in person). 

Many things are currently broken, but this is a first step. 

Note that the current `TwitterProvider` diverges from `FacebookProvider` and `LinkedInProvider` due to different OAuth version used (1.0a vs 2.0).

Also, token-based sigin-up/login (including library share) is _not_ covered. 

Configuration is real and provisioned via `kifi` Twitter account.

I believe this set of changes is pretty safe -- I have removed all user-facing elements (i.e. local hack). 

Feedback appreciated. Feel free to pull it and play with it should you decide to do so.

@andrewconner @eishay 
cc: @jaredpetker @thassss

### CODE REVIEW

**Comment by raymondng** [comment]
token-based code paths are also well in progress (testing locally). To minimize risk I'd prefer to merge this in first, do some testing to ensure nothing's broken, and then add token-based signup/login code path.

**Comment by andrewconner** [comment]
Looks good, good start.

**Comment by andrewconner** [comment]
What would you like help with testing? I'll help or will find someone.

**Comment by raymondng** [comment]
Thanks!

I will be testing twitter signup/login/logout manually, and log bugs.

I need help on performing sanity check that nothing is broken: i.e. going through FB and LNKD checklist manually -- we can probably skip email on the checklist as it has automated coverage.

**Comment by andrewconner** [comment]
Let me know when you need help if any.

**Comment by raymondng** [comment]
Thanks. Will do.

**Pull request merged**
