### PR TITLE
Harsh timeout for discussion decoration. Time for a cache?

### PR DESCRIPTION
**Pull request by andrewconner**
@leogrim @ryanpbrewster I'm seeing 10s timeouts, which sucks (that eliza can take 10 seconds), but also means keep responses take that long as well. This sets a much more aggressive timeline. We'll still get airbrakes when it times out.

### CODE REVIEW

**Comment by andrewconner** [comment]
This PR also has the airbrake error trimming that we talked about @leogrim

**Comment by leogrim** [comment]
Adding a few caches in a coming PR

**Comment by andrewconner** [comment]
Wahoo. This timeout okay, though? Don't want to stall keep decoration too much if possible.

**Comment by leogrim** [comment]
Nothing should take 10 seconds :)

**Pull request merged**
