### PR TITLE
Adds ability to get notifications before a time on mobile

### PR DESCRIPTION
**Pull request by jaredpetker**
- Refactors MobileMessagingController.getNotifications to take in an optional
  non-inclusive timestamp to get notifications older than.

### CODE REVIEW

**Comment by jaredpetker** [comment]
Think this is actually ready to go, @stkem could you take a look?

**Comment by stkem** [comment]
lgtm. Merge away!

**Comment by stkem** [comment]
I assume you tested it in dec mode too, right?

**Comment by jaredpetker** [comment]
I only tested it locally in dev mode, if there is another way to go about
testing I can do that too!

**Comment by stkem** [comment]
Nope, locally in dev mode is what I meant. "dec":="dev" :-P

**Comment by jaredpetker** [comment]
OK great, does the issuer usually pull in the request here after being reviewed?

**Comment by stkem** [comment]
We don't really have a clear process. Sometimes the issuer merges, sometimes the reviewer.

**Pull request merged**
