### PR TITLE
throttling assignScrapeTasks on the scraper

### PR DESCRIPTION
**Pull request by eishay**

### CODE REVIEW

**Comment by eishay** [comment]
@ymatsuda @andrewconner this is timing out again, what do you think about throttling on the scraper side?

**Comment by ymatsuda** [comment]
I think it is better to delay qSize checking until assignTasks is about to be executed by putting it in withLockFuture
- to minimize the time difference between getQueueSize and assignTasks, and
- to avoid calling assignTasks when the queue is full

**Comment by andrewconner** [comment]
Agreed with Yasu

**Comment by eishay** [comment]
fixed with yasu, the new code will come soon

**Pull request merged**
