### PR TITLE
Only execute a prefix search for a trailing query term

### PR DESCRIPTION
**Pull request by leogrim**
@stkem @andrewconner 
Basically, if there's something (including a whitespace) after a term, we should consider that the user is done typing that term and shouldn't use it for a prefix search.

Previously: 
- `Léo Grim` would do a prefix search with both `Léo` and `Grim` and `Léon Grimaldi` would match.

Now:
- `Léo Grim` will do a prefix search on `Grim` but not `Léo`, e.g. `Léon Grimaldi` won't match
- `Léo_` (_ representing a trailing whitespace) will not do a prefix search at all

### CODE REVIEW

**Comment by ryanpbrewster** [comment]
The way that `IntelliJ` searches for things is the opposite of this, and in a way that I find useful.

Does `stats` match `statistics`? I guess that is a separate issue...

What about "org endpoints" matching "organization endpoints"?

**Comment by stkem** [comment]
code lgtm. What was the motivation here? Doesn't the old way let you find more things. e.g, if you know only part of the first name. Say I'm looking for Tom, and I don't remember his last name, but I know it starts with a D. I search for "Tom D", and as it might turn out he's in the system as "Tomas D...". New way won't find him, right? Contrived example I admit.

**Comment by leogrim** [comment]
Well, sometimes let's say I search for `Stephen Kemmerling`, it can be annoying if `Stephenie Kemmerling` is a match, not a great example either :)

**Comment by leogrim** [comment]
What about simply boosting a trailing term prefix query as opposed to remove non-trailing ones?

**Comment by stkem** [comment]
Yeah, I think that makes sense. If you type "Léo Grim", "Léo Grimaldi" should show up before "Leonardo Grimaldi", since you had one exact match.

**Pull request merged**
