### PR TITLE
deploying firefox extension to new shoebox: shoebox-demand-2

### PR DESCRIPTION
**Pull request by 2is10**
cc @stkem

### CODE REVIEW

**Comment by 2is10** [comment]
@stkem @andrewconner @eishay any better ideas where we could host the Firefox extension?

**Comment by andrewconner** [comment]
Yeah we can use b01 and host on 42go.com

**Comment by 2is10** [comment]
or s3, I guess

**Comment by eishay** [comment]
I'll be happy to see b01 gone

**Pull request merged**
