### PR TITLE
use scraper embedly in shoebox

### PR DESCRIPTION
**Pull request by yingjieMiao**
@raymondng @martinraison

### CODE REVIEW

**Comment by martinraison** [comment]
looks good!

**Comment by yingjieMiao** [comment]
merging. will deploy shoebox to see if any problems.

**Comment by raymondng** [comment]
Question: URISummaryCommander will also move to scraper, right?

**Comment by yingjieMiao** [comment]
@raymondng : not at this point. Right now, we save some resource in fetching from Embedly and parse the json in scraper. The package from scraper to shoebox is much smaller. 

We need much more work to move URISummaryCommander to scraper. The Commander has mixed access to S3 and shoeboxDB.

**Comment by martinraison** [comment]
I thought the main problem was that page_info and image_info are in shoebox. If we move these two tables to scraper, is it still difficult to move URISummaryCommander? I think it is the only classes that accesses page_info and image_info.

**Comment by yingjieMiao** [comment]
That's exactly what Ray told me. That's something to consider next.

**Comment by eishay** [comment]
The main problem was that 
1. we're going to an external service that may block threads in shoebox that needs to deal with real time requests.
2. we're parsing large amounts of json and loading images to memory from these services and they effect the gc and cpu, starving real time calls 
The db is another problem, less urgent then the first two and as you know I feel strongly about removing tables from shoebox.

Scraper db is the right place for tables like `scrape_info`, but is it the right place for `page_info` and `image_info`?

**Comment by raymondng** [comment]
I don't think we block threads while dealing with embedly ... please
correct me if I am mistaken.

Nonetheless -- valid points. I think a lot of it depends on anticipated use
cases/patterns.

Should probably discuss this outside of github :)

**Pull request merged**
