### PR TITLE
Unescape HTML entities

### PR DESCRIPTION
**Pull request by andrewconner**
@leogrim

### CODE REVIEW

**Comment by andrewconner** [comment]
``` scala
scala> StringEscapeUtils.unescapeHtml4("nickhanauer &gt; MW won't solve this. but &gt; invest in edu &amp; train -&gt; US skills that command $15/hr or more.")
res0: String = nickhanauer > MW won't solve this. but > invest in edu & train -> US skills that command $15/hr or more.
```

**Comment by leogrim** [comment]
Is it actually HTML4? If these are the only 3 problematic characters, I find suspicious that this is exactly the same set of escapable characters as Slack, see https://api.slack.com/docs/formatting
Any chance Twitter is doing what they're doing for the same reason Slack is? 

Then that's what we have to do to format for Slack in `DescriptionElements.scala 119`:
`def escapeSegment(segment: String): String = segment.replaceAllLiterally("<" -> "&lt;", ">" -> "&gt;", "&" -> "&amp;")`

**Comment by andrewconner** [comment]
Since we're decoding, there's no difference. I can switch it if you prefer.

**Comment by leogrim** [comment]
Not really a matter of preference, just wondering what Twitter is doing on the other end so that we do what matches that

**Comment by andrewconner** [comment]
It's not documented. Switched to use your suggestion.

**Pull request merged**
