### PR TITLE
sending message to client without waiting on the db and logging userThread.notificationUpdatedAt and userThread.notificationLastSeen

### PR DESCRIPTION
**Pull request by eishay**
to understand a high latency emails bug

@andrewconner & @stkem what is the rule that we should send emails on? Is it exactly 15 minutes after notificationUpdatedAt provided that notificationEmailed is false and unread is true?

I would like to document it and create a check before sending verifying that the email sent it within the boundaries of time we expect it to be sent (e.g. not more then three minutes after the time it should have been sent).

### CODE REVIEW

**Comment by andrewconner** [comment]
Yep, I believe that's the rule. It can be over 15 mins (product was fine if we process every few minutes).

**Comment by eishay** [comment]
@andrewconner @stkem 
in an email thread, should we show the user only messages he didn't see yet?

**Comment by eishay** [comment]
Checking on the db I think we stopped updating the `notification_last_seen` field few months ago:

``` sql
mysql> select max(created_at) from user_thread where  notification_last_seen is not null;
+-------------------------+
| max(created_at)         |
+-------------------------+
| 2013-12-09 04:24:02.743 |
+-------------------------+
```

And I don't see any write in the code. Should we drop it? We do read it, is it a bug?

**Comment by stkem** [comment]
-What Andrew said regarding timing is correct.
-I'm somewhat opposed to only showing messages the user hasn't seen yet. I think they help with context. I periodically get annoyed with github for sending me emails about comment on a pull request with no context.
-Yes, we did stop setting last seen a while ago (so it's not a bug). There has been periodic talk of reviving it (specifically to highlight _unseen_ notifications in the UI), which is why the column is still there.

**Comment by andrewconner** [comment]
I think historically we've sent the messages since the last time they saw the thread — so everything "new", but we do resent ones that were already sent (so there is a logical summary from the last time they did see the thread).

**Pull request merged**
