### PR TITLE
[#73312381895351] Slack and Twitter attribution in Google inject

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner @leogrim @JRuff42 @eishay 
1. Adds one slack and twitter attribution if it is present
2. Attribution links to the original message/tweek
3. Changed keeper limit from 8 to 5 to make room for the attribution

screen shot 2015-12-14 at 4 30 12 pm

### CODE REVIEW

**Comment by andrewconner** [comment]
How about cutting users only if there's no attribution?

I seem to remember `makeWhyFit` doing a lot of work trying to fit attribution into a fixed pixel width. Wonder if this should be plugged into that. (Well, it probably should... I guess more importantly, how much to plug it in and improve it).

What do you think?

**Comment by andrewconner** [comment]
Besides that, UX wise, the only thing that sticks out is the attribution being somewhat arbitrary (based on the primary keep search is returning). Seems a lot of common sites will get twitter handles from people's Twitter import libraries. I'll pull in locally and see how common it.

**Comment by cvializ** [comment]
kk. It looks like makeWhyFit will remove users and libraries until the width is correct, so I don't need to do anything manually to plug this in. I'll undo the "8 users to 5 users" change.

Hmm I see your point. Are you saying you had something in mind we could do UX wise to prevent low-quality attributions from showing?

**Comment by cvializ** [comment]
merging now and fixing any issues later

**Pull request merged**
