### PR TITLE
getting guice graph from a live service instance

### PR DESCRIPTION
**Pull request by eishay**
see https://github.com/google/guice/wiki/Grapher

### CODE REVIEW

**Comment by eishay** [comment]
@ryanpbrewster @gratimax @andrewconner @stkem @leogrim

**Comment by ryanpbrewster** [comment]
You are my favorite person, assuming this works. I'm really excited to see this graph.

**Comment by stkem** [comment]
:+1: :+1: :+1:

**Comment by maxov** [comment]
:+1:

**Comment by andrewconner** [comment]
I'm scared to see it. :+1:

**Pull request merged**
