### PR TITLE
[DO NOT MERGE] Return true for all checks on profiles_beta experiment.

### PR DESCRIPTION
**Pull request by yipingliao**
@2is10 @andrewconner cc @eishay @ahsu1230 

This will turn profiles on for everyone.

AFAIK there is only one issue left: links on related library cards are not pointing to user profiles yet. Going to work on that right now.

### CODE REVIEW

**Comment by eishay** [comment]
yey!

**Comment by ahsu1230** [comment]
yoohoo!

**Comment by 2is10** [comment]
:+1: :balloon:

**Comment by yipingliao** [comment]
Updated a protractor test for our new profile pages (it was checking for the old settings page). Merging...

**Pull request merged**
