### PR TITLE
more recall of related libraries

### PR DESCRIPTION
**Pull request by yingjieMiao**
@eishay 
As long as the library contains 1 classifiable URI, we will consider it as a vertex in the graph. 

cc: @stkem

### CODE REVIEW

**Comment by yingjieMiao** [comment]
don't know the impact on the graph size, and quality impact. let's see.

**Comment by yingjieMiao** [comment]
better recall now. But graph size also grew considerably. Computing the full graph, trimming and saving takes about 14 minutes now.

I can tweak up the threshold to 2 keeps. A library with 1 keep is trivial

**Comment by stkem** [comment]
Could you start a google doc similar to the one for recos to track algorithm changes? That way we can correlate changes with patterns in the analytics after the fact much easier.
Maybe make it sub sheet in the recos tracking doc?

**Comment by yingjieMiao** [comment]
sure.

**Comment by yingjieMiao** [comment]
added a few.

**Pull request merged**
