### PR TITLE
marketing site

### PR DESCRIPTION
**Pull request by joshm1**
@stkem

### CODE REVIEW

**Comment by stkem** [comment]
why are we doing this?

**Comment by joshm1** [comment]
because the old landing page is blank and goes nowhere after the redirect, this at least give the user something to see if they navigate back to the page or click not to open the app (as it does in facebook's embedded browser)

we can discuss with jen

**Comment by stkem** [comment]
ok, fine with me

**Comment by stkem** [comment]
code looks good

**Pull request merged**
