### PR TITLE
Truly fixing email opt outs. Been broken for a while, since launch.

### PR DESCRIPTION
**Pull request by andrewconner**
Only an integration test would have caught this, UI issue only. @stkem @martinraison Hrmph. Maybe we need more of those?

### CODE REVIEW

**Comment by andrewconner** [comment]
Self merging to get this rolled out in prod.

**Comment by 2is10** [comment]
thanks for fixing. you (or someone else?) might consider adding a unit test.

**Comment by andrewconner** [comment]
Unit test would be hard. This was a views issue where we were doing a `set.contains(x)` with the wrong type. Scala allows this, so the compiler didn't complain. The fix is just converting it to the right type (`NotificationCategory`).

**Comment by andrewconner** [comment]
Presentation only. :/

**Comment by 2is10** [comment]
I see. So I guess Play doesn’t yet make it as easy as, say, Rails to test a controller action by making simple assertions about the response.

**Comment by 2is10** [comment]
Hmm.. looks like Play does make it easy. In both Rails and Play, these are called “functional tests”.
http://www.playframework.com/documentation/2.0/ScalaFunctionalTest

**Comment by andrewconner** [comment]
Yep, that's what I meant by integration tests above.

**Pull request merged**
