### PR TITLE
Possibly temporary? Allowing a power user to import.

### PR DESCRIPTION
**Pull request by andrewconner**
@eishay

### CODE REVIEW

**Comment by eishay** [comment]
good, maybe we should have an experiment of "legit power user" and/or minumum time on kifi

**Comment by eishay** [comment]
for now its great

**Comment by andrewconner** [comment]
Agreed. Would be helpful about many restrictions, including friend requests.

**Comment by andrewconner** [comment]
Let's talk about it tomorrow morning.

**Pull request merged**
