### PR TITLE
reactive lock uptake

### PR DESCRIPTION
**Pull request by stkem**
@yingjieMiao @lawzlo @andrewconner

### CODE REVIEW

**Comment by yingjieMiao** [comment]
:+1:

**Comment by lawzlo** [comment]
Can you explain what happen here? Just want to learn. I searched in Google for reactiveLock and couldn't find useful thing.

**Comment by stkem** [comment]
I actually wrote the reactive lock. I don't think it's a thing on the internet yet. Check out this PR https://github.com/kifi/keepit/pull/9636
I'd be happy to walk you through it tomorrow.

**Comment by lawzlo** [comment]
Nice. Thanks!

**Comment by eishay** [comment]
so you're TradeMarking it?

**Comment by stkem** [comment]
perhaps :-)

**Comment by stkem** [comment]
I'll sell it to typesafe if the money is right

**Pull request merged**
