### PR TITLE
fix library keep count (during copy/move keeps)

### PR DESCRIPTION
**Pull request by yingjieMiao**
@ahsu1230 @eishay

### CODE REVIEW

**Comment by eishay** [comment]
Thanks!
Does that really take care of all the edge cases?
Shouldn't we do it always at the same place we're updating the `Library.lastKept` field?

**Comment by yingjieMiao** [comment]
It's consistent here. It appears not in the same place b/c I want to make sure we have cleared the cache.

**Comment by ahsu1230** [comment]
the logic looks good. `LibraryRepo.updateLastKept` is also used in `KeepInterner.internRawBookmark` & `internRawBookmarksWithStatus`. Both of which are eventually called by the private function `internKeep` that updates a library's `keep_count`. 

Note: There's a comment in `KeepInterner.internKeep` that recommends us to change how we're counting keeps in a library since it's not only super expensive, but also prone to deadlocks @stkem

**Comment by yingjieMiao** [comment]
The situation is better here (I hope). In keepInterner, we update libraryKeepCount for every keep we intern. Here, we update only after a batch operation is done. (and those batch operations from users are low frequency anyway)

**Comment by yingjieMiao** [comment]
merging. will babysit for a while.

**Pull request merged**
