### PR TITLE
Stream new connections to the client on creation

### PR DESCRIPTION
**Pull request by andrewconner**

### CODE REVIEW

**Comment by gmethvin** [comment]
I guess this is a reasonable solution to the problem, but I don't like the idea of having stuff in our database repositories depend on components of the actual interface with the client.

It might be better to have a way to register an event listener for events like this. This will also make it easier to test.

**Comment by andrewconner** [comment]
Yeah, I felt the same way. Unfortunately, the other option is to move it to the call site, but that makes it super easy to forget when we have new ways to make connections between people. Creating a listener has the same issue: you either put the hook at the user connection creator (and have to deal with missing it in the future), or put it inside the model again. Other ideas?

**Comment by 2is10** [comment]
`UserConnectionCreator` (one level up) feels like a better layer for this.

**Comment by andrewconner** [comment]
Alright. I wasn't sure if that would always be used, but I can move it.

**Comment by andrewconner** [comment]
Moved.

**Pull request merged**
