### PR TITLE
remove play23/akka23 warning

### PR DESCRIPTION
**Pull request by raymondng**
play23/akka23 update

never mind about the change history -- I tried to rebase and apparently made things worse (?!)

@andrewconner

### CODE REVIEW

**Comment by andrewconner** [comment]
Interesting, `BroadcastGroup` vs `RoundRobinGroup`. We want to broadcast to all scraping actors?

**Comment by raymondng** [comment]
For scrape agents, its only (current) use is for broadcast. I was thinking about getting rid of the router all together, but this (appears to be) a simpler change.

**Comment by andrewconner** [comment]
Looks good

**Comment by andrewconner** [comment]
Merging to rid the warnings — since you're out, if there's problems, I'll revert this PR.

**Pull request merged**
