### PR TITLE
Reformatting source with Scalariform

### PR DESCRIPTION
**Pull request by andrewconner**
You will need to restart sbt.

If you have a merge conflict, choose yours, then compile.

@eishay @ymatsuda @yingjieMiao @leogrim @lawzlo @ahsu1230 @2is10 @martinraison @stkem @raymondng

### CODE REVIEW

**Comment by andrewconner** [comment]
Tested locally, tests should pass on jenkins without issue.

**Comment by eishay** [comment]
:scream::scream::scream::scream::scream::scream:

**Comment by eishay** [comment]
merge worked

**Comment by martinraison** [comment]
fyi, if you have tons of merge conflicts you can do `git checkout --ours .` to solve everything at once by picking your version

**Pull request merged**
