### PR TITLE
bigger curator batch size

### PR DESCRIPTION
**Pull request by stkem**
@yingjieMiao

### CODE REVIEW

**Comment by yingjieMiao** [comment]
what does this do? user in the reactive lock queue will wait longer?

**Comment by stkem** [comment]
No, more URIs per time a user is processed (i.e. we will now process 350 uris for a user until they go back to the end of the line)

**Comment by yingjieMiao** [comment]
That's what I meant: each user now costs more time, so increasing wait time for other guys in the queue.

**Comment by stkem** [comment]
Yeah, but that is minimal. A batch takes less than 1 second on average. I'm hoping larger batches will reduce overhead.

**Pull request merged**
