### PR TITLE
[#96760355925057] Add keep link, edit keep button

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner just a preview of the symbol-sprites sharing. see also https://github.com/kifi/symbol-sprites

### CODE REVIEW

**Comment by andrewconner** [comment]
Interesting, cool. To share with the extension?

**Comment by cvializ** [comment]
Yep
add to library 2

**Comment by andrewconner** [comment]
Oh sweet.

**Comment by cvializ** [comment]
now with special library dropdown
add to library 3

**Comment by andrewconner** [comment]
Slick! :+1:

**Pull request merged**
