### PR TITLE
Feature/paginate add participants

### PR DESCRIPTION
**Pull request by cvializ**
@andrewconner 📜 📜 📜

### CODE REVIEW

**Comment by andrewconner** [comment]
Works for me!

Some suggestions:
1. Weird bug: Normally, if I click in the search box then click out, it closes the list (I actually would prefer that it doesn't do this, and always stays open...). However, if I scroll down once, then click out, it flashes back to the pre-scrolled version.
2. Could you fetch before the last one, so for instance, the first batch is fetched and displayed, and the next is ready to go? You may want to use a local cache, staying one batch ahead of where they've actually gotten to (same technique the inbox pane uses so it appears to scroll a lot faster)
3. Any way to fetch more than 7 at a time after the first batch?
4. Every new batch causes a faint flash as the whole list is re-built. Easy to fix?

**Comment by andrewconner** [comment]
If any of those aren't clear I can make a gif.

**Comment by cvializ** [comment]
@ac thanks for the feedback, those are good finds
1. Fixed
2. That's a good idea. What do you think about making that v2 since the typeahead is still the same speed?
3. It should be fetching 10 at a time. Is it only grabbing 7 for you?
4. I believe that the flash is the existing behavior. Maybe you could show me what you mean if you think it's a regression?

**Comment by andrewconner** [comment]
2 Sure
3 Yeah. Actually sometimes it's 8 and sometimes 9 as well.
4 Before, every time it drew, it was a different result set, so would be unexpected to flash. Now, with pagination, it feels odd that it flashes again since all I'm doing is scrolling.

**Comment by cvializ** [comment]
Alrighty, fixed 4. I haven't encountered 3 yet, but I will let you know if I do

**Comment by andrewconner** [comment]
Alright, it's not a big deal, could be the backend is shorting you.

**Comment by cvializ** [comment]
kk I'll 🚢 and QA then

**Pull request merged**
