### PR TITLE
locking normalized uri interning on raw full url.

### PR DESCRIPTION
**Pull request by eishay**
Locking since there may be few calls coming at the same time from the client with the same url (e.g. get page info, and record visited).
The lock is on the exact same url and using intern so we can have a globally unique object of the url.
Possible downside is that the permgen will fill up with these urls.
@leogrim @raymondng please review

### CODE REVIEW

**Comment by eishay** [comment]
backgroud is the exceptions we're getting with 
`com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'M71SpeAD5NZusiZSJ6Ec1Q==' for key 'normalized_uri_u_url_hash':0:in
NativeConstructorAccessorImpl.java:-2:in com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'M71SpeAD5NZusiZSJ6Ec1Q==' for key 'normalized_uri_u_url_hash'`

**Comment by 2is10** [comment]
Could you use a WeakHashMap of URLs to locks instead, to avoid interning?

**Comment by leogrim** [comment]
Yasu's request consolidator maybe?

**Comment by 2is10** [comment]
If you like the WeakHashMap route, we could use Guava’s MapMaker to make it
thread-safe:
http://stackoverflow.com/questions/2255950/is-there-java-concurrent-util-or-equivalent-for-weakhashmap

**Comment by eishay** [comment]
WeakHashMap is a good idea

**Comment by ymatsuda** [comment]
RequestConsolidator?

**Comment by eishay** [comment]
oh, RequestConsolidator is much a better approach and more efficient. added a todo for that. Its a bit more involved since we'll need to convert the code to use futures and its a good opportunity to get some of the code out of the repo to a controller level.

**Pull request merged**
