### PR TITLE
integrity check inside uriIntegrityPlugin

### PR DESCRIPTION
**Pull request by yingjieMiao**
@leogrim @ymatsuda 

@leogrim  suggested have this sanity check in integrityPlugin (to reduce 10+ minutes delay)
@ymatsuda : any performance concerns? Any side effects? race conditions?

I cannot directly refer to `orphanCleaner` in the plugin, circular dependency. So I made up a trait. 

tests passed

### CODE REVIEW

**Comment by leogrim** [comment]
@andrewconner @stkem

**Comment by andrewconner** [comment]
Ah this fixes the rescrape issue?

**Comment by yingjieMiao** [comment]
hope so!
we used to explicitly handle scrapeInfo inside the plugin, but the logic was taken out long ago.
this brings it back.

One concern I have is that this may cause spikes in scraper activities. Maybe?

**Comment by yingjieMiao** [comment]
shall we merge this one, except the merge confilcts?

**Comment by andrewconner** [comment]
If it fixes the scraper issue for imported urls, then yes! :)

**Comment by yingjieMiao** [comment]
OK. I will give it a try.

**Pull request merged**
