### PR TITLE
Fixes drafts bug in ext

### PR DESCRIPTION
**Pull request by andrewconner**
@cvializ Fixes drafts bug. We had a regex that required IDs to be in basically UUID form (specifically, all lowercase). Not true anymore, so widen regex.

Since most people now have a thread keyed by `"undefined"`, refuse to read out `"undefined"` keys.

Your call, but since this PR is very simple, we may want to do some git magic and release a bugfix extension with this before we release the keep-notifcations-comment stuff (which is in master now). What do you think?

### CODE REVIEW

**Comment by cvializ** [comment]
It'd probably be a good idea to minimize risk and just ship this and exclude the new stuff

**Comment by andrewconner** [comment]
Alright. I'll do it, based on your last 3.5.0 commit: https://github.com/kifi/keepit/commit/d690157a That good?

**Comment by andrewconner** [comment]
Merging to master, but will release 3.5.1 with this commit on top of the linked one above if you approve.

**Comment by cvializ** [comment]
consider it approved

**Pull request merged**
