### PR TITLE
Do not show tag list on keep cards for logged-out users.

### PR DESCRIPTION
**Pull request by yipingliao**
@andrewconner cc @ahsu1230 
https://app.asana.com/0/19898402862947/20950859174981

### CODE REVIEW

**Comment by ahsu1230** [comment]
:+1:

**Comment by 2is10** [comment]
We don’t want search engines indexing tags?

**Comment by yipingliao** [comment]
The plan is to put them back in when we deploy public library search. How does that sound?

**Comment by 2is10** [comment]
Fine with me. I was just curious about the reasoning. Thanks for explaining
in person.

**Pull request merged**
