### PR TITLE
Clutch, a data caching library

### PR DESCRIPTION
**Pull request by andrewconner**
The beginnings of Clutch, a library that caches server responses. Still lots to do. Would like to open source eventually.

### CODE REVIEW

**Comment by andrewconner** [comment]
@martinraison @stkem

**Comment by ymatsuda** [comment]
nice!

**Comment by andrewconner** [comment]
To elaborate a bit more, it's $q (Promise) based, and has the property of returning the same object for the same request. The API is pleasant and embraces JS's dynamic nature. No boilerplate to get set up.

``` javascript
var someService = new Clutch(function (a, b) {
  // fetch something using `a` and `b`, return a promise.
});

someService.get(1,2) // delegates to the function above, passing in a=1, b=2.
someService.get(1,2) // returns the same promise

someService.get(2,'a') // new request
```

**Comment by stkem** [comment]
:+1:

**Comment by martinraison** [comment]
great!

**Pull request merged**
