### PR TITLE
Adding AdRoll (retargeting) tracker to the angular app

### PR DESCRIPTION
**Pull request by stkem**
@andrewconner

### CODE REVIEW

**Comment by stkem** [comment]
Is there a better place to put this? Needs to be on both public and logged in library and profile pages.

**Comment by stkem** [comment]
Getting this out so sterling can test. Happy to move it somewhere else later.

**Comment by andrewconner** [comment]
Ew, do we really need to add it to every angular load?

**Comment by stkem** [comment]
That is what I was told. Or rather "Every profile and library page" which is nearly all of the app (in terms of pages hit)

**Comment by 2is10** [comment]
How about only if the viewer is logged out?

**Comment by andrewconner** [comment]
I proposed that, but this PR got reverted because there's a few issues with this implementation. Sterling will decide what's next.

**Pull request merged**
