### PR TITLE
respect the user

### PR DESCRIPTION
**Pull request by yingjieMiao**
@leogrim @andrewconner 

per @sterlingz 's comments. This is a naive combination of user's hashtags and auto tags. Actual logic is easy to change. 

We can either merge it now, or merge it when search is fixed.

### CODE REVIEW

**Comment by andrewconner** [comment]
Yeah let's merge when the site correctly searches.

**Comment by yingjieMiao** [comment]
@andrewconner , do you think client need to convert a #scala query into "tag: scala"?

**Comment by andrewconner** [comment]
Yeah probably. I'll do some testing

**Comment by leogrim** [comment]
Search is fixed re: this

**Comment by yingjieMiao** [comment]
@andrewconner  
is frontend ready to convert #query to "tag: query"?

**Comment by andrewconner** [comment]
Not yet. Still on the list

**Pull request merged**
