### PR TITLE
Fix incorrect width of dropdown on Firefox

### PR DESCRIPTION
**Pull request by cvializ**

### CODE REVIEW

**Comment by cvializ** [comment]
@andrewconner @ajkochanowicz

**Comment by adamjgrant** [comment]
Which dropdown is this?

**Comment by cvializ** [comment]
The dropdown on the user library page. I made a ticket here
https://trello.com/c/HAkt7HCV/61-library-page-cover-image-dropdown-style-broken-in-firefox

**Comment by adamjgrant** [comment]
Oh cool. Good to merge. :+1:

**Pull request merged**
