### PR TITLE
use one modelPublicId and authToken for PostRegIntents

### PR DESCRIPTION
**Pull request by camhashemi**
@ryanpbrewster @andrewconner @cvializ 

should simplify things going forward

### CODE REVIEW

**Comment by camhashemi** [comment]
tested in dev mode, auto joining orgs and libraries still works (through email and social). going to deploy and QA, then push the code for auto-joining via keeps.

**Comment by andrewconner** [comment]
I ran into this PR when looking into something unrelated. Sorry for being so slow on feedback.

I typed up a bit, but realized I may be missing the point. What's the goal here? To cut down on unique parameters passed around?

Outside of the general idea of this, things like `generateRegIntent` require all possible parameters to be passed in to it. `SecureSocialControllers` should basically never be touched, because it's a copy from SecureSocial at one specific point.

**Comment by camhashemi** [comment]
The goal was to clean up APIs, once I saw I was going to add `keepPubId` and `keepAuthToken`. It's not a necessity. `SecureSocialControllers` wasn't persisting those cookies through signup, so pretty sure `PostRegIntents` are broken for social without passing those cookies through.

**Comment by andrewconner** [comment]
Cookies stick around, so if they have them, unless someone explicitly clears it, should be fine. Were you seeing them getting cleared out if they were there previously?

**Pull request merged**
