### PR TITLE
[angular] stub: drag-and-drop tags on keeps

### PR DESCRIPTION
**Pull request by martinraison**
A tag can be added to a keep by dragging the tag onto the keep. I still need to give visual hints that something is actually happening during the drag.
Also there seems to be a bug with tags that happens when dragging a tag onto a keep that already has this tag. I haven't yet investigated where the bug is coming from exactly, I'll try to do it.

### CODE REVIEW

**Comment by martinraison** [comment]
@andrewconner @joonho1101 btw I added the angular drag & drop library that we talked about to the project (http://ganarajpr.github.io/angular-dragdrop/) so you may have to refresh your bower dependencies.

**Comment by andrewconner** [comment]
Awesome. Are you planning on doing dragging a keep to a tag too?

What sort of control do we have over how it looks mid-drag? Right now, it looks like I'm dragging a normal link, which (UX wise) I wouldn't expect to work.

**Comment by martinraison** [comment]
Yes, this is really a stub, I'll improve the UI and try to make it work both ways.

**Comment by andrewconner** [comment]
Cool, thanks. Glad the library worked out.

**Pull request merged**
