### PR TITLE
ansible - separate ec2 launch & provision playbooks - add search/graph instances; update documentation

### PR DESCRIPTION
**Pull request by joshm1**
@andrewconner

### CODE REVIEW

**Comment by yingjieMiao** [comment]
@joshm1 does the new launched graph machines have correct JVM setting? In particular, XMX. We have many memory warnings.

**Comment by joshm1** [comment]
@yingjieMiao do you know what the value is it supposed to be? below is an excerpt from the init.d script in source control:

```
javaArgs="$yourkit $newrelic $jmxArgs $javaGc -Dhttp.port=9000 -Xms2048M -Xmx24g -server -Dconfig.resource=prod/$serviceNameLo.conf -Duser.dir=$applDir/ -Dlogger.resource=prod/logger.prod.xml -cp $classpath play.core.server.NettyServer $applDir"
```

On an old instance I see that the value is -Xmx12288m. Have these been manually changed recently? I synced the init.d file with what was on the server a few months ago.

Is this right? these graph servers can handle a lot more than 12 GB.  This is from graph-demand-5 (old instance)

```
eng@graph-demand-5:~$ free -m
             total       used       free     shared    buffers     cached
Mem:         30679       3162      27517          0         36        536
-/+ buffers/cache:       2589      28090
Swap:            0          0          0
```

if it matters, I saw the memory warnings. They started 1-2 hours before the new graph machines were launched.

**Comment by joshm1** [comment]
here is the memory info on one of the new graph instances that's been up for more than an hour.  At 13 GB used total, the Xmx24g gives the JVM plenty of room to grow

```
[eng@graph-demand-8 ~]$ free -m
             total       used       free     shared    buffers     cached
Mem:         30679      13861      16818          0         21        922
-/+ buffers/cache:      12917      17762
Swap:            0          0          0
```

**Comment by joshm1** [comment]
I just noticed the low memory exceptions are all from graph-demand-5, which is an older instance so I think the new instances are fine.

**Comment by yingjieMiao** [comment]
thanks @joshm1 . I thought the graph machine usually uses around 20~25g. `init.d` should be fine.

**Comment by joshm1** [comment]
i see. yeah those errors must be because the init.d from the old graph-demand-5 was only 12 GB

**Comment by andrewconner** [comment]
Looks good

**Pull request merged**
